package com.tyust.dao.user;

import com.tyust.bean.user.BaseUserInfo;
import com.tyust.bean.user.BaseUserInfoExample;
import com.tyust.bean.user.TBaseUserInfo;
import com.tyust.dao.user.BaseUserInfoDAO;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BaseUserInfoDAOImpl extends SqlMapClientDaoSupport implements BaseUserInfoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    public BaseUserInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    public int countByExample(BaseUserInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("T_BASE_USER_INFO.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    public int deleteByExample(BaseUserInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("T_BASE_USER_INFO.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(String userId) {
        BaseUserInfo key = new BaseUserInfo();
        key.setUserId(userId);
        int rows = getSqlMapClientTemplate().delete("T_BASE_USER_INFO.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    public void insert(BaseUserInfo record) {
        getSqlMapClientTemplate().insert("T_BASE_USER_INFO.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    public void insertSelective(BaseUserInfo record) {
        getSqlMapClientTemplate().insert("T_BASE_USER_INFO.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<BaseUserInfo> selectByExample(BaseUserInfoExample example) {
        List<BaseUserInfo> list = getSqlMapClientTemplate().queryForList("T_BASE_USER_INFO.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    public BaseUserInfo selectByPrimaryKey(String userId) {
        BaseUserInfo key = new BaseUserInfo();
        key.setUserId(userId);
        BaseUserInfo record = (BaseUserInfo) getSqlMapClientTemplate().queryForObject("T_BASE_USER_INFO.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(BaseUserInfo record, BaseUserInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("T_BASE_USER_INFO.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    public int updateByExample(BaseUserInfo record, BaseUserInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("T_BASE_USER_INFO.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(BaseUserInfo record) {
        int rows = getSqlMapClientTemplate().update("T_BASE_USER_INFO.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(BaseUserInfo record) {
        int rows = getSqlMapClientTemplate().update("T_BASE_USER_INFO.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends BaseUserInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, BaseUserInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	public List<TBaseUserInfo> selectUserWithUnit(String mUserId) {
		List<TBaseUserInfo> list = getSqlMapClientTemplate().queryForList("UserInfo.selectUserWithUnit", mUserId);
        return list;
	}
    
}