package com.tyust.dao.user;

import com.tyust.bean.user.BaseUserInfo;
import com.tyust.bean.user.BaseUserInfoExample;
import com.tyust.bean.user.TBaseUserInfo;

import java.util.List;

public interface BaseUserInfoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    int countByExample(BaseUserInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    int deleteByExample(BaseUserInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    void insert(BaseUserInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    void insertSelective(BaseUserInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    List<BaseUserInfo> selectByExample(BaseUserInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    BaseUserInfo selectByPrimaryKey(String userId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(BaseUserInfo record, BaseUserInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    int updateByExample(BaseUserInfo record, BaseUserInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(BaseUserInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table T_BASE_USER_INFO
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(BaseUserInfo record);

	List<TBaseUserInfo> selectUserWithUnit(String userId);
}