package com.tyust.bean.device;

import java.util.Date;

public class DeviceTestApplyAttach {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_ID
     *
     * @ibatorgenerated
     */
    private String devAttachId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_APPLY_ID
     *
     * @ibatorgenerated
     */
    private String devApplyId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_URL
     *
     * @ibatorgenerated
     */
    private String devAttachUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_NAME
     *
     * @ibatorgenerated
     */
    private String devAttachName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_TYPE
     *
     * @ibatorgenerated
     */
    private String devAttachType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_DATE
     *
     * @ibatorgenerated
     */
    private Date devAttachDate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_ID
     *
     * @return the value of NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_ID
     *
     * @ibatorgenerated
     */
    public String getDevAttachId() {
        return devAttachId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_ID
     *
     * @param devAttachId the value for NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_ID
     *
     * @ibatorgenerated
     */
    public void setDevAttachId(String devAttachId) {
        this.devAttachId = devAttachId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_APPLY_ID
     *
     * @return the value of NT_DEVICE_TEST_APPLY_ATTACH.DEV_APPLY_ID
     *
     * @ibatorgenerated
     */
    public String getDevApplyId() {
        return devApplyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_APPLY_ID
     *
     * @param devApplyId the value for NT_DEVICE_TEST_APPLY_ATTACH.DEV_APPLY_ID
     *
     * @ibatorgenerated
     */
    public void setDevApplyId(String devApplyId) {
        this.devApplyId = devApplyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_URL
     *
     * @return the value of NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_URL
     *
     * @ibatorgenerated
     */
    public String getDevAttachUrl() {
        return devAttachUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_URL
     *
     * @param devAttachUrl the value for NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_URL
     *
     * @ibatorgenerated
     */
    public void setDevAttachUrl(String devAttachUrl) {
        this.devAttachUrl = devAttachUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_NAME
     *
     * @return the value of NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_NAME
     *
     * @ibatorgenerated
     */
    public String getDevAttachName() {
        return devAttachName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_NAME
     *
     * @param devAttachName the value for NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_NAME
     *
     * @ibatorgenerated
     */
    public void setDevAttachName(String devAttachName) {
        this.devAttachName = devAttachName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_TYPE
     *
     * @return the value of NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_TYPE
     *
     * @ibatorgenerated
     */
    public String getDevAttachType() {
        return devAttachType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_TYPE
     *
     * @param devAttachType the value for NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_TYPE
     *
     * @ibatorgenerated
     */
    public void setDevAttachType(String devAttachType) {
        this.devAttachType = devAttachType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_DATE
     *
     * @return the value of NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_DATE
     *
     * @ibatorgenerated
     */
    public Date getDevAttachDate() {
        return devAttachDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_DATE
     *
     * @param devAttachDate the value for NT_DEVICE_TEST_APPLY_ATTACH.DEV_ATTACH_DATE
     *
     * @ibatorgenerated
     */
    public void setDevAttachDate(Date devAttachDate) {
        this.devAttachDate = devAttachDate;
    }
}