package com.tyust.bean.device;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.tyust.common.IbatorGenExamplePageHelper;

public class DeviceTestApplyAttachExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public DeviceTestApplyAttachExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    protected DeviceTestApplyAttachExample(DeviceTestApplyAttachExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andDevAttachIdIsNull() {
            addCriterion("DEV_ATTACH_ID is null");
            return this;
        }

        public Criteria andDevAttachIdIsNotNull() {
            addCriterion("DEV_ATTACH_ID is not null");
            return this;
        }

        public Criteria andDevAttachIdEqualTo(String value) {
            addCriterion("DEV_ATTACH_ID =", value, "devAttachId");
            return this;
        }

        public Criteria andDevAttachIdNotEqualTo(String value) {
            addCriterion("DEV_ATTACH_ID <>", value, "devAttachId");
            return this;
        }

        public Criteria andDevAttachIdGreaterThan(String value) {
            addCriterion("DEV_ATTACH_ID >", value, "devAttachId");
            return this;
        }

        public Criteria andDevAttachIdGreaterThanOrEqualTo(String value) {
            addCriterion("DEV_ATTACH_ID >=", value, "devAttachId");
            return this;
        }

        public Criteria andDevAttachIdLessThan(String value) {
            addCriterion("DEV_ATTACH_ID <", value, "devAttachId");
            return this;
        }

        public Criteria andDevAttachIdLessThanOrEqualTo(String value) {
            addCriterion("DEV_ATTACH_ID <=", value, "devAttachId");
            return this;
        }

        public Criteria andDevAttachIdLike(String value) {
            addCriterion("DEV_ATTACH_ID like", value, "devAttachId");
            return this;
        }

        public Criteria andDevAttachIdNotLike(String value) {
            addCriterion("DEV_ATTACH_ID not like", value, "devAttachId");
            return this;
        }

        public Criteria andDevAttachIdIn(List<String> values) {
            addCriterion("DEV_ATTACH_ID in", values, "devAttachId");
            return this;
        }

        public Criteria andDevAttachIdNotIn(List<String> values) {
            addCriterion("DEV_ATTACH_ID not in", values, "devAttachId");
            return this;
        }

        public Criteria andDevAttachIdBetween(String value1, String value2) {
            addCriterion("DEV_ATTACH_ID between", value1, value2, "devAttachId");
            return this;
        }

        public Criteria andDevAttachIdNotBetween(String value1, String value2) {
            addCriterion("DEV_ATTACH_ID not between", value1, value2, "devAttachId");
            return this;
        }

        public Criteria andDevApplyIdIsNull() {
            addCriterion("DEV_APPLY_ID is null");
            return this;
        }

        public Criteria andDevApplyIdIsNotNull() {
            addCriterion("DEV_APPLY_ID is not null");
            return this;
        }

        public Criteria andDevApplyIdEqualTo(String value) {
            addCriterion("DEV_APPLY_ID =", value, "devApplyId");
            return this;
        }

        public Criteria andDevApplyIdNotEqualTo(String value) {
            addCriterion("DEV_APPLY_ID <>", value, "devApplyId");
            return this;
        }

        public Criteria andDevApplyIdGreaterThan(String value) {
            addCriterion("DEV_APPLY_ID >", value, "devApplyId");
            return this;
        }

        public Criteria andDevApplyIdGreaterThanOrEqualTo(String value) {
            addCriterion("DEV_APPLY_ID >=", value, "devApplyId");
            return this;
        }

        public Criteria andDevApplyIdLessThan(String value) {
            addCriterion("DEV_APPLY_ID <", value, "devApplyId");
            return this;
        }

        public Criteria andDevApplyIdLessThanOrEqualTo(String value) {
            addCriterion("DEV_APPLY_ID <=", value, "devApplyId");
            return this;
        }

        public Criteria andDevApplyIdLike(String value) {
            addCriterion("DEV_APPLY_ID like", value, "devApplyId");
            return this;
        }

        public Criteria andDevApplyIdNotLike(String value) {
            addCriterion("DEV_APPLY_ID not like", value, "devApplyId");
            return this;
        }

        public Criteria andDevApplyIdIn(List<String> values) {
            addCriterion("DEV_APPLY_ID in", values, "devApplyId");
            return this;
        }

        public Criteria andDevApplyIdNotIn(List<String> values) {
            addCriterion("DEV_APPLY_ID not in", values, "devApplyId");
            return this;
        }

        public Criteria andDevApplyIdBetween(String value1, String value2) {
            addCriterion("DEV_APPLY_ID between", value1, value2, "devApplyId");
            return this;
        }

        public Criteria andDevApplyIdNotBetween(String value1, String value2) {
            addCriterion("DEV_APPLY_ID not between", value1, value2, "devApplyId");
            return this;
        }

        public Criteria andDevAttachUrlIsNull() {
            addCriterion("DEV_ATTACH_URL is null");
            return this;
        }

        public Criteria andDevAttachUrlIsNotNull() {
            addCriterion("DEV_ATTACH_URL is not null");
            return this;
        }

        public Criteria andDevAttachUrlEqualTo(String value) {
            addCriterion("DEV_ATTACH_URL =", value, "devAttachUrl");
            return this;
        }

        public Criteria andDevAttachUrlNotEqualTo(String value) {
            addCriterion("DEV_ATTACH_URL <>", value, "devAttachUrl");
            return this;
        }

        public Criteria andDevAttachUrlGreaterThan(String value) {
            addCriterion("DEV_ATTACH_URL >", value, "devAttachUrl");
            return this;
        }

        public Criteria andDevAttachUrlGreaterThanOrEqualTo(String value) {
            addCriterion("DEV_ATTACH_URL >=", value, "devAttachUrl");
            return this;
        }

        public Criteria andDevAttachUrlLessThan(String value) {
            addCriterion("DEV_ATTACH_URL <", value, "devAttachUrl");
            return this;
        }

        public Criteria andDevAttachUrlLessThanOrEqualTo(String value) {
            addCriterion("DEV_ATTACH_URL <=", value, "devAttachUrl");
            return this;
        }

        public Criteria andDevAttachUrlLike(String value) {
            addCriterion("DEV_ATTACH_URL like", value, "devAttachUrl");
            return this;
        }

        public Criteria andDevAttachUrlNotLike(String value) {
            addCriterion("DEV_ATTACH_URL not like", value, "devAttachUrl");
            return this;
        }

        public Criteria andDevAttachUrlIn(List<String> values) {
            addCriterion("DEV_ATTACH_URL in", values, "devAttachUrl");
            return this;
        }

        public Criteria andDevAttachUrlNotIn(List<String> values) {
            addCriterion("DEV_ATTACH_URL not in", values, "devAttachUrl");
            return this;
        }

        public Criteria andDevAttachUrlBetween(String value1, String value2) {
            addCriterion("DEV_ATTACH_URL between", value1, value2, "devAttachUrl");
            return this;
        }

        public Criteria andDevAttachUrlNotBetween(String value1, String value2) {
            addCriterion("DEV_ATTACH_URL not between", value1, value2, "devAttachUrl");
            return this;
        }

        public Criteria andDevAttachNameIsNull() {
            addCriterion("DEV_ATTACH_NAME is null");
            return this;
        }

        public Criteria andDevAttachNameIsNotNull() {
            addCriterion("DEV_ATTACH_NAME is not null");
            return this;
        }

        public Criteria andDevAttachNameEqualTo(String value) {
            addCriterion("DEV_ATTACH_NAME =", value, "devAttachName");
            return this;
        }

        public Criteria andDevAttachNameNotEqualTo(String value) {
            addCriterion("DEV_ATTACH_NAME <>", value, "devAttachName");
            return this;
        }

        public Criteria andDevAttachNameGreaterThan(String value) {
            addCriterion("DEV_ATTACH_NAME >", value, "devAttachName");
            return this;
        }

        public Criteria andDevAttachNameGreaterThanOrEqualTo(String value) {
            addCriterion("DEV_ATTACH_NAME >=", value, "devAttachName");
            return this;
        }

        public Criteria andDevAttachNameLessThan(String value) {
            addCriterion("DEV_ATTACH_NAME <", value, "devAttachName");
            return this;
        }

        public Criteria andDevAttachNameLessThanOrEqualTo(String value) {
            addCriterion("DEV_ATTACH_NAME <=", value, "devAttachName");
            return this;
        }

        public Criteria andDevAttachNameLike(String value) {
            addCriterion("DEV_ATTACH_NAME like", value, "devAttachName");
            return this;
        }

        public Criteria andDevAttachNameNotLike(String value) {
            addCriterion("DEV_ATTACH_NAME not like", value, "devAttachName");
            return this;
        }

        public Criteria andDevAttachNameIn(List<String> values) {
            addCriterion("DEV_ATTACH_NAME in", values, "devAttachName");
            return this;
        }

        public Criteria andDevAttachNameNotIn(List<String> values) {
            addCriterion("DEV_ATTACH_NAME not in", values, "devAttachName");
            return this;
        }

        public Criteria andDevAttachNameBetween(String value1, String value2) {
            addCriterion("DEV_ATTACH_NAME between", value1, value2, "devAttachName");
            return this;
        }

        public Criteria andDevAttachNameNotBetween(String value1, String value2) {
            addCriterion("DEV_ATTACH_NAME not between", value1, value2, "devAttachName");
            return this;
        }

        public Criteria andDevAttachTypeIsNull() {
            addCriterion("DEV_ATTACH_TYPE is null");
            return this;
        }

        public Criteria andDevAttachTypeIsNotNull() {
            addCriterion("DEV_ATTACH_TYPE is not null");
            return this;
        }

        public Criteria andDevAttachTypeEqualTo(String value) {
            addCriterion("DEV_ATTACH_TYPE =", value, "devAttachType");
            return this;
        }

        public Criteria andDevAttachTypeNotEqualTo(String value) {
            addCriterion("DEV_ATTACH_TYPE <>", value, "devAttachType");
            return this;
        }

        public Criteria andDevAttachTypeGreaterThan(String value) {
            addCriterion("DEV_ATTACH_TYPE >", value, "devAttachType");
            return this;
        }

        public Criteria andDevAttachTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DEV_ATTACH_TYPE >=", value, "devAttachType");
            return this;
        }

        public Criteria andDevAttachTypeLessThan(String value) {
            addCriterion("DEV_ATTACH_TYPE <", value, "devAttachType");
            return this;
        }

        public Criteria andDevAttachTypeLessThanOrEqualTo(String value) {
            addCriterion("DEV_ATTACH_TYPE <=", value, "devAttachType");
            return this;
        }

        public Criteria andDevAttachTypeLike(String value) {
            addCriterion("DEV_ATTACH_TYPE like", value, "devAttachType");
            return this;
        }

        public Criteria andDevAttachTypeNotLike(String value) {
            addCriterion("DEV_ATTACH_TYPE not like", value, "devAttachType");
            return this;
        }

        public Criteria andDevAttachTypeIn(List<String> values) {
            addCriterion("DEV_ATTACH_TYPE in", values, "devAttachType");
            return this;
        }

        public Criteria andDevAttachTypeNotIn(List<String> values) {
            addCriterion("DEV_ATTACH_TYPE not in", values, "devAttachType");
            return this;
        }

        public Criteria andDevAttachTypeBetween(String value1, String value2) {
            addCriterion("DEV_ATTACH_TYPE between", value1, value2, "devAttachType");
            return this;
        }

        public Criteria andDevAttachTypeNotBetween(String value1, String value2) {
            addCriterion("DEV_ATTACH_TYPE not between", value1, value2, "devAttachType");
            return this;
        }

        public Criteria andDevAttachDateIsNull() {
            addCriterion("DEV_ATTACH_DATE is null");
            return this;
        }

        public Criteria andDevAttachDateIsNotNull() {
            addCriterion("DEV_ATTACH_DATE is not null");
            return this;
        }

        public Criteria andDevAttachDateEqualTo(Date value) {
            addCriterion("DEV_ATTACH_DATE =", value, "devAttachDate");
            return this;
        }

        public Criteria andDevAttachDateNotEqualTo(Date value) {
            addCriterion("DEV_ATTACH_DATE <>", value, "devAttachDate");
            return this;
        }

        public Criteria andDevAttachDateGreaterThan(Date value) {
            addCriterion("DEV_ATTACH_DATE >", value, "devAttachDate");
            return this;
        }

        public Criteria andDevAttachDateGreaterThanOrEqualTo(Date value) {
            addCriterion("DEV_ATTACH_DATE >=", value, "devAttachDate");
            return this;
        }

        public Criteria andDevAttachDateLessThan(Date value) {
            addCriterion("DEV_ATTACH_DATE <", value, "devAttachDate");
            return this;
        }

        public Criteria andDevAttachDateLessThanOrEqualTo(Date value) {
            addCriterion("DEV_ATTACH_DATE <=", value, "devAttachDate");
            return this;
        }

        public Criteria andDevAttachDateIn(List<Date> values) {
            addCriterion("DEV_ATTACH_DATE in", values, "devAttachDate");
            return this;
        }

        public Criteria andDevAttachDateNotIn(List<Date> values) {
            addCriterion("DEV_ATTACH_DATE not in", values, "devAttachDate");
            return this;
        }

        public Criteria andDevAttachDateBetween(Date value1, Date value2) {
            addCriterion("DEV_ATTACH_DATE between", value1, value2, "devAttachDate");
            return this;
        }

        public Criteria andDevAttachDateNotBetween(Date value1, Date value2) {
            addCriterion("DEV_ATTACH_DATE not between", value1, value2, "devAttachDate");
            return this;
        }
    }
}