/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.tyust.web.action.unit;

import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts2.ServletActionContext;

import com.tyust.common.OpertionType;
import com.tyust.common.SaveLog;
import com.tyust.service.unit.UnitService;

/**
 * MyEclipse Struts Creation date: 07-15-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class DelUnitAction{

	private UnitService unitService;
	/*
	 * Generated Methods
	 */

	public UnitService getUnitService() {
		return unitService;
	}

	public void setUnitService(UnitService unitService) {
		this.unitService = unitService;
	}

	/**
	 * Method execute
	 * 
	 * 删除机构，先检查该机构下有无下级机构和成员，该机构无成员和下级机构才可以删除
	 * 删除顺序依次为：T_BASE_UNIT_ROLE_MODULE-->T_BASE_UNIT_ROLE-->T_BASE_UNIT_INFO
	 * @throws Exception 
	 */
	public String execute() throws Exception {
		HttpServletRequest request=ServletActionContext.getRequest();
		PrintWriter printWriter = ServletActionContext.getResponse().getWriter();
	
		String unitId = request.getParameter("unitId");
		if (unitId == null || unitId.equals("")) {
			return null;
		} else {		
			try {									
				String[] unitIdArr = unitId.split(",");
				for(int i=0;i<unitIdArr.length;i++){
					List listUint = unitService.findByUpid(unitIdArr[i]);
					if(listUint != null && listUint.size() > 0){
						printWriter.print(1);//1为有下属机构
						return null;
					}else{
						List listUser = unitService.selectUserInfoByUnitId(unitIdArr[i]);
						if (listUser != null && listUser.size() > 0) {
							printWriter.print(2);//2为机构里有成员
							return null;					
						}else{
							unitService.delUnitRoleModule(unitIdArr[i]);
							unitService.delUnitRoleByUnitId(unitIdArr[i]);															
							unitService.delUnit(unitIdArr[i]);
						}
					}
				}
				printWriter.print(0);//0删除成功
				SaveLog.saveLog(request, "删除单位", OpertionType.State.DELETE, "删除成功");
				return null;
			} catch (Exception e) {
				e.printStackTrace();
				SaveLog.saveLog(request, "删除单位", OpertionType.State.DELETE, "删除失败");
				return "input";
			} 
		}
	}
}