/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.tyust.web.action.unit;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts2.ServletActionContext;

import com.tyust.bean.unit.TBaseUnitInfo;
import com.tyust.common.OpertionType;
import com.tyust.common.SaveLog;
import com.tyust.service.unit.UnitService;

/**
 * 更新部门
 */
public class UpdateUnitAction {
	private UnitService unitService;
	// 机构ID
	private String updateunitId;
	// 部门级别
	private String updateunitClass;
	// 部门名称
	private String updateunitName;
	// 地址
	private String updateaddress;
	// 电话
	private String updatetelephone;
	// 联系人
	private String updatecontactPerson;
	// EMAIL
	private String updateemail;
	// 负责人
	private String updateheader;

	public String getUpdateunitId() {
		return updateunitId;
	}

	public void setUpdateunitId(String updateunitId) {
		this.updateunitId = updateunitId;
	}

	public String getUpdateunitClass() {
		return updateunitClass;
	}

	public void setUpdateunitClass(String updateunitClass) {
		this.updateunitClass = updateunitClass;
	}

	public String getUpdateunitName() {
		return updateunitName;
	}

	public void setUpdateunitName(String updateunitName) {
		this.updateunitName = updateunitName;
	}

	public String getUpdateaddress() {
		return updateaddress;
	}

	public void setUpdateaddress(String updateaddress) {
		this.updateaddress = updateaddress;
	}

	public String getUpdatetelephone() {
		return updatetelephone;
	}

	public void setUpdatetelephone(String updatetelephone) {
		this.updatetelephone = updatetelephone;
	}

	public String getUpdatecontactPerson() {
		return updatecontactPerson;
	}

	public void setUpdatecontactPerson(String updatecontactPerson) {
		this.updatecontactPerson = updatecontactPerson;
	}

	public String getUpdateemail() {
		return updateemail;
	}

	public void setUpdateemail(String updateemail) {
		this.updateemail = updateemail;
	}

	public String getUpdateheader() {
		return updateheader;
	}

	public void setUpdateheader(String updateheader) {
		this.updateheader = updateheader;
	}

	public UnitService getUnitService() {
		return unitService;
	}

	public void setUnitService(UnitService unitService) {
		this.unitService = unitService;
	}

	public String execute() {
		TBaseUnitInfo unitInfo = new TBaseUnitInfo();
		HttpServletRequest request = ServletActionContext.getRequest();
		try {
			System.out.println(updateaddress);
			unitInfo.setUnitId(updateunitId);
			unitInfo.setAddress(updateaddress);
			unitInfo.setContactPerson(updatecontactPerson);
			unitInfo.setEmail(updateemail);
			unitInfo.setHeader(updateheader);
			unitInfo.setTelephone(updatetelephone);
			unitInfo.setUnitName(updateunitName);
			unitInfo.setUnitClass(updateunitClass);

			unitService.updateUnit(unitInfo);
			SaveLog.saveLog(request, "修改部门", OpertionType.State.UPDATE, "修改成功");
		} catch (Exception e) {
			e.printStackTrace();
			System.out.println("修改部门异常");
			SaveLog.saveLog(request, "修改部门", OpertionType.State.UPDATE, "修改失败");
		}
		request.setAttribute("message", "部门修改成功");
		return "success";
	}
}