/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.tyust.web.action.user;


import javax.servlet.http.HttpServletRequest;

import org.apache.struts2.ServletActionContext;

import com.tyust.bean.unit.TBaseUnitInfo;
import com.tyust.bean.unit.TBaseUnitRoleModule;
import com.tyust.bean.user.TBaseUserInfo;
import com.tyust.common.OpertionType;
import com.tyust.common.SaveLog;
import com.tyust.service.unit.UnitService;
import com.tyust.service.user.RoleService;

public class EditRoleModuleAction{
	//角色服务层接口
	private RoleService roleService;
	//机构服务层接口
	private UnitService unitService;
	
	private String roleId;
	
	private String unitId;

	public String getUnitId() {
		return unitId;
	}

	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}

	public RoleService getRoleService() {
		return roleService;
	}

	public void setRoleService(RoleService roleService) {
		this.roleService = roleService;
	}

	public UnitService getUnitService() {
		return unitService;
	}

	public void setUnitService(UnitService unitService) {
		this.unitService = unitService;
	}

	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/** 
	 * Method execute
	 */
	public String execute() {
		HttpServletRequest request=ServletActionContext.getRequest();
		String unitId = request.getParameter("unitId");
		//YjUnitInfo unit = yjUnitInfoDAO.selectByPrimaryKey(unitId);
		 TBaseUnitInfo unit=unitService.findUnit(unitId);
		 String unitName=unit.getUnitName();
		 String[] moduleIds=request.getParameterValues("menuId");
		 request.setAttribute("unitid", unitId);
		 request.setAttribute("unitname", unitName);
		TBaseUnitRoleModule rModule=new TBaseUnitRoleModule();
		roleService.deleteRoleModule(roleId);
		 TBaseUserInfo user=(TBaseUserInfo)request.getSession().getAttribute("user");
		 
		if(moduleIds==null){
			 SaveLog.saveLog(request, "分配权限", OpertionType.State.DELETE, "删除成功");
			 return "success";
		}
	    for(int i=0;i<moduleIds.length;i++){
			rModule.setRoleId(roleId);
			rModule.setUnitId(unitId);
			rModule.setModuleId(moduleIds[i]);
			roleService.insertRoleModule(rModule);
		}
	   
	    //插入一条日志
	   
		     if(request.getParameter("roleModuleList").trim().length()>2){
		    	 SaveLog.saveLog(request, "分配权限", OpertionType.State.UPDATE, "分配成功");
			  }else{
		    SaveLog.saveLog(request, "分配权限", OpertionType.State.ADD, "分配成功");
		     }
		return "success";
	}
}