/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.tyust.web.action.user;


import javax.servlet.http.HttpServletRequest;

import org.apache.struts2.ServletActionContext;

import com.tyust.bean.user.TBaseUnitUserRole;
import com.tyust.common.OpertionType;
import com.tyust.common.SaveLog;
import com.tyust.service.user.UserService;

/** 
 * MyEclipse Struts
 * Creation date: 07-16-2010
 * 
 * XDoclet definition:
 * @struts.action parameter="param" validate="true"
 */
public class EditUserRoleAction {
	//用户服务层接口
	private UserService userService;
	private String roleId ;
	private String unitId ;
	private String userId ;
		public UserService getUserService() {
		return userService;
	}
	public void setUserService(UserService userService) {
		this.userService = userService;
	}
	public String getRoleId() {
		return roleId;
	}
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}
	public String getUnitId() {
		return unitId;
	}
	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}
	public String getUserId() {
		return userId;
	}
	public void setUserId(String userId) {
		this.userId = userId;
	}
	/*
	 * Generated Methods
	 */
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public String addUserRole(){
		HttpServletRequest request=ServletActionContext.getRequest();
		    TBaseUnitUserRole unituserrole =  new TBaseUnitUserRole();
		    
		    unituserrole.setRoleId(roleId);
		    unituserrole.setUnitId(unitId);
		    String[] userIds = userId.split(",");
		  try{
			    for(int i=0;i<userIds.length;i++){
			    	if(userService.selectIsExistUserRole(userIds[i])>0){//判断该用户是否已分配角色
			    		userService.deleteUserRole(userIds[i]); //清除角色
			    	}
			    	unituserrole.setUserId(userIds[i]);
			    	userService.insertUserRole(unituserrole);//给用户分配角色
			    }
			    SaveLog.saveLog(request, "用户角色管理", OpertionType.State.ADD, "添加角色成功");
		  }catch(Exception e){
			  e.printStackTrace();
			  SaveLog.saveLog(request, "用户角色管理", OpertionType.State.ADD,"异常："+e.toString() );
		  }
		return "success";
	}
	
	
}