/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.tyust.web.action.user;

import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts2.ServletActionContext;

import com.tyust.common.OpertionType;
import com.tyust.common.SaveLog;

/** 
 * MyEclipse Struts
 * Creation date: 07-21-2010
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="logout" path="/login.jsp"
 */
public class LogoutAction{
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public String execute(){
		HttpServletRequest request=ServletActionContext.getRequest();
		
		try{
			request.getSession().invalidate();
			SaveLog.saveLog(request, "用户退出", OpertionType.State.LOGOUT, "退出成功");
			PrintWriter out = ServletActionContext.getResponse().getWriter();
			//out.println("<script>window.location='"+request.getContextPath()+"'</script>");
			out.println("<script>window.location='/'</script>");
		}catch(Exception e){
			e.printStackTrace();
			SaveLog.saveLog(request, "用户退出",  OpertionType.State.LOGOUT, e.getMessage());
		}
		
		
		return null;
	}
}