/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.tyust.web.action.user;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts2.ServletActionContext;

import com.tyust.bean.unit.TBaseUnitRoleModule;
import com.tyust.bean.user.TBaseDefinedUrl;
import com.tyust.bean.user.TBaseUserInfo;
import com.tyust.service.user.RoleService;

/**
 * MyEclipse Struts Creation date: 07-15-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class SelectRoleModuleAction {
	// 角色服务层接口
	private RoleService roleService;
	/*
	 * Generated Methods
	 */

	public RoleService getRoleService() {
		return roleService;
	}

	public void setRoleService(RoleService roleService) {
		this.roleService = roleService;
	}

	/**
	 * Method execute 查询某角色所拥有的权限
	 */
	public String execute() {
		HttpServletRequest request = ServletActionContext.getRequest();
		TBaseUserInfo user = (TBaseUserInfo) request.getSession().getAttribute("user");
		String userId = user.getUserId();

		// 获得当前用户拥有的权限
		List<TBaseDefinedUrl> modules = null;
		if (user.getUserName().equals("root") || user.getUserName().equals("ROOT")) {
			modules = roleService.selectModule(user.getTecduty());
		} else {
			modules = roleService.selectModuleByRoleId(userId);
		}
		List<TBaseDefinedUrl> modulesList = new ArrayList<TBaseDefinedUrl>();
		for (int i = 0; i < modules.size(); i++) {
			modulesList.add((TBaseDefinedUrl) modules.get(i));
		}

		request.setAttribute("ModulesList", modulesList);
		// 获得t_base_unit_role_module中的数据 查看某角色所拥有的权限
		List<TBaseUnitRoleModule> roleModules = roleService.findRoleModules(request.getParameter("roleId").trim());
		List<TBaseUnitRoleModule> roleModuleList = new ArrayList<TBaseUnitRoleModule>();
		for (int i = 0; i < roleModules.size(); i++) {
			roleModuleList.add((TBaseUnitRoleModule) roleModules.get(i));
		}
		request.setAttribute("roleModuleList", roleModuleList);
		request.setAttribute("roleId", request.getParameter("roleId").trim());
		request.setAttribute("unitId", request.getParameter("unitId").trim());
		return "select";
	}
}