/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.tyust.web.action.user;
import javax.servlet.http.HttpServletRequest;

import org.apache.struts2.ServletActionContext;

import com.tyust.bean.unit.TBaseUnitRole;
import com.tyust.bean.user.TBaseUserInfo;
import com.tyust.common.OpertionType;
import com.tyust.common.SaveLog;
import com.tyust.service.user.RoleService;

/** 
 * MyEclipse Struts
 * Creation date: 07-14-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UpdateRoleAction{
	//角色服务层接口
	private RoleService roleService;
	
	private String roleName;
	
	private String roleId;

	private int inuse;
	
	private String unitId;
	
	private String description;

	public RoleService getRoleService() {
		return roleService;
	}

	public void setRoleService(RoleService roleService) {
		this.roleService = roleService;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public int getInuse() {
		return inuse;
	}

	public void setInuse(int inuse) {
		this.inuse = inuse;
	}

	public String getUnitId() {
		return unitId;
	}

	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	/** 
	 * Method execute
	 */
	public String execute() {
		HttpServletRequest request=ServletActionContext.getRequest();
		 TBaseUnitRole role=new TBaseUnitRole();
		 role.setRoleName(roleName);
		 role.setRoleId(roleId);
		 role.setUnitId(unitId);
		 request.setAttribute("unitid", unitId);
			role.setInuse(inuse);
			role.setDescription(description);
			TBaseUserInfo user=(TBaseUserInfo)request.getSession().getAttribute("user");
			role.setCreateUnitId(user.getUnitId());
			roleService.updateRole(role);
		
			 //插入一条日志
	    SaveLog.saveLog(request, "更新角色", OpertionType.State.UPDATE, "更新成功");
		return "success"; 
	}
}