package com.tyust.bean.dic;

public class SystemDictionary {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column DIC_SYSTEM_DICTIONARY.DICTIONARY_OPTION_ID
	 * @ibatorgenerated
	 */
	private String dictionaryOptionId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column DIC_SYSTEM_DICTIONARY.DICTIONARY_OPTION_NAME
	 * @ibatorgenerated
	 */
	private String dictionaryOptionName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column DIC_SYSTEM_DICTIONARY.UP_DICTIONARY_OPTION_ID
	 * @ibatorgenerated
	 */
	private String upDictionaryOptionId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column DIC_SYSTEM_DICTIONARY.IS_USE
	 * @ibatorgenerated
	 */
	private Short isUse;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column DIC_SYSTEM_DICTIONARY.DESCRIPTIONS
	 * @ibatorgenerated
	 */
	private String descriptions;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column DIC_SYSTEM_DICTIONARY.SORT_NO
	 * @ibatorgenerated
	 */
	private Short sortNo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column DIC_SYSTEM_DICTIONARY.FLAG
	 * @ibatorgenerated
	 */
	private Short flag;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column DIC_SYSTEM_DICTIONARY.ENGLISH_NAME
	 * @ibatorgenerated
	 */
	private String englishName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column DIC_SYSTEM_DICTIONARY.DATA_TYPE
	 * @ibatorgenerated
	 */
	private String dataType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column DIC_SYSTEM_DICTIONARY.REMARK1
	 * @ibatorgenerated
	 */
	private String remark1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column DIC_SYSTEM_DICTIONARY.REMARK2
	 * @ibatorgenerated
	 */
	private String remark2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column DIC_SYSTEM_DICTIONARY.MATCH_DIC_ID
	 * @ibatorgenerated
	 */
	private String matchDicId;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column DIC_SYSTEM_DICTIONARY.DICTIONARY_OPTION_ID
	 * @return  the value of DIC_SYSTEM_DICTIONARY.DICTIONARY_OPTION_ID
	 * @ibatorgenerated
	 */
	public String getDictionaryOptionId() {
		return dictionaryOptionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column DIC_SYSTEM_DICTIONARY.DICTIONARY_OPTION_ID
	 * @param dictionaryOptionId  the value for DIC_SYSTEM_DICTIONARY.DICTIONARY_OPTION_ID
	 * @ibatorgenerated
	 */
	public void setDictionaryOptionId(String dictionaryOptionId) {
		this.dictionaryOptionId = dictionaryOptionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column DIC_SYSTEM_DICTIONARY.DICTIONARY_OPTION_NAME
	 * @return  the value of DIC_SYSTEM_DICTIONARY.DICTIONARY_OPTION_NAME
	 * @ibatorgenerated
	 */
	public String getDictionaryOptionName() {
		return dictionaryOptionName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column DIC_SYSTEM_DICTIONARY.DICTIONARY_OPTION_NAME
	 * @param dictionaryOptionName  the value for DIC_SYSTEM_DICTIONARY.DICTIONARY_OPTION_NAME
	 * @ibatorgenerated
	 */
	public void setDictionaryOptionName(String dictionaryOptionName) {
		this.dictionaryOptionName = dictionaryOptionName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column DIC_SYSTEM_DICTIONARY.UP_DICTIONARY_OPTION_ID
	 * @return  the value of DIC_SYSTEM_DICTIONARY.UP_DICTIONARY_OPTION_ID
	 * @ibatorgenerated
	 */
	public String getUpDictionaryOptionId() {
		return upDictionaryOptionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column DIC_SYSTEM_DICTIONARY.UP_DICTIONARY_OPTION_ID
	 * @param upDictionaryOptionId  the value for DIC_SYSTEM_DICTIONARY.UP_DICTIONARY_OPTION_ID
	 * @ibatorgenerated
	 */
	public void setUpDictionaryOptionId(String upDictionaryOptionId) {
		this.upDictionaryOptionId = upDictionaryOptionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column DIC_SYSTEM_DICTIONARY.IS_USE
	 * @return  the value of DIC_SYSTEM_DICTIONARY.IS_USE
	 * @ibatorgenerated
	 */
	public Short getIsUse() {
		return isUse;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column DIC_SYSTEM_DICTIONARY.IS_USE
	 * @param isUse  the value for DIC_SYSTEM_DICTIONARY.IS_USE
	 * @ibatorgenerated
	 */
	public void setIsUse(Short isUse) {
		this.isUse = isUse;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column DIC_SYSTEM_DICTIONARY.DESCRIPTIONS
	 * @return  the value of DIC_SYSTEM_DICTIONARY.DESCRIPTIONS
	 * @ibatorgenerated
	 */
	public String getDescriptions() {
		return descriptions;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column DIC_SYSTEM_DICTIONARY.DESCRIPTIONS
	 * @param descriptions  the value for DIC_SYSTEM_DICTIONARY.DESCRIPTIONS
	 * @ibatorgenerated
	 */
	public void setDescriptions(String descriptions) {
		this.descriptions = descriptions;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column DIC_SYSTEM_DICTIONARY.SORT_NO
	 * @return  the value of DIC_SYSTEM_DICTIONARY.SORT_NO
	 * @ibatorgenerated
	 */
	public Short getSortNo() {
		return sortNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column DIC_SYSTEM_DICTIONARY.SORT_NO
	 * @param sortNo  the value for DIC_SYSTEM_DICTIONARY.SORT_NO
	 * @ibatorgenerated
	 */
	public void setSortNo(Short sortNo) {
		this.sortNo = sortNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column DIC_SYSTEM_DICTIONARY.FLAG
	 * @return  the value of DIC_SYSTEM_DICTIONARY.FLAG
	 * @ibatorgenerated
	 */
	public Short getFlag() {
		return flag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column DIC_SYSTEM_DICTIONARY.FLAG
	 * @param flag  the value for DIC_SYSTEM_DICTIONARY.FLAG
	 * @ibatorgenerated
	 */
	public void setFlag(Short flag) {
		this.flag = flag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column DIC_SYSTEM_DICTIONARY.ENGLISH_NAME
	 * @return  the value of DIC_SYSTEM_DICTIONARY.ENGLISH_NAME
	 * @ibatorgenerated
	 */
	public String getEnglishName() {
		return englishName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column DIC_SYSTEM_DICTIONARY.ENGLISH_NAME
	 * @param englishName  the value for DIC_SYSTEM_DICTIONARY.ENGLISH_NAME
	 * @ibatorgenerated
	 */
	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column DIC_SYSTEM_DICTIONARY.DATA_TYPE
	 * @return  the value of DIC_SYSTEM_DICTIONARY.DATA_TYPE
	 * @ibatorgenerated
	 */
	public String getDataType() {
		return dataType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column DIC_SYSTEM_DICTIONARY.DATA_TYPE
	 * @param dataType  the value for DIC_SYSTEM_DICTIONARY.DATA_TYPE
	 * @ibatorgenerated
	 */
	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column DIC_SYSTEM_DICTIONARY.REMARK1
	 * @return  the value of DIC_SYSTEM_DICTIONARY.REMARK1
	 * @ibatorgenerated
	 */
	public String getRemark1() {
		return remark1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column DIC_SYSTEM_DICTIONARY.REMARK1
	 * @param remark1  the value for DIC_SYSTEM_DICTIONARY.REMARK1
	 * @ibatorgenerated
	 */
	public void setRemark1(String remark1) {
		this.remark1 = remark1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column DIC_SYSTEM_DICTIONARY.REMARK2
	 * @return  the value of DIC_SYSTEM_DICTIONARY.REMARK2
	 * @ibatorgenerated
	 */
	public String getRemark2() {
		return remark2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column DIC_SYSTEM_DICTIONARY.REMARK2
	 * @param remark2  the value for DIC_SYSTEM_DICTIONARY.REMARK2
	 * @ibatorgenerated
	 */
	public void setRemark2(String remark2) {
		this.remark2 = remark2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column DIC_SYSTEM_DICTIONARY.MATCH_DIC_ID
	 * @return  the value of DIC_SYSTEM_DICTIONARY.MATCH_DIC_ID
	 * @ibatorgenerated
	 */
	public String getMatchDicId() {
		return matchDicId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column DIC_SYSTEM_DICTIONARY.MATCH_DIC_ID
	 * @param matchDicId  the value for DIC_SYSTEM_DICTIONARY.MATCH_DIC_ID
	 * @ibatorgenerated
	 */
	public void setMatchDicId(String matchDicId) {
		this.matchDicId = matchDicId;
	}
}