package com.tyust.bean.pbs;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.tyust.common.IbatorGenExamplePageHelper;

public class PbsApplyInfoExample extends IbatorGenExamplePageHelper{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table PBS_APPLY_INFO
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table PBS_APPLY_INFO
     *
     * @ibatorgenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_APPLY_INFO
     *
     * @ibatorgenerated
     */
    public PbsApplyInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_APPLY_INFO
     *
     * @ibatorgenerated
     */
    protected PbsApplyInfoExample(PbsApplyInfoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_APPLY_INFO
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_APPLY_INFO
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_APPLY_INFO
     *
     * @ibatorgenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_APPLY_INFO
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_APPLY_INFO
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_APPLY_INFO
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_APPLY_INFO
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table PBS_APPLY_INFO
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andPbsApplyIdIsNull() {
            addCriterion("PBS_APPLY_ID is null");
            return this;
        }

        public Criteria andPbsApplyIdIsNotNull() {
            addCriterion("PBS_APPLY_ID is not null");
            return this;
        }

        public Criteria andPbsApplyIdEqualTo(String value) {
            addCriterion("PBS_APPLY_ID =", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdNotEqualTo(String value) {
            addCriterion("PBS_APPLY_ID <>", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdGreaterThan(String value) {
            addCriterion("PBS_APPLY_ID >", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdGreaterThanOrEqualTo(String value) {
            addCriterion("PBS_APPLY_ID >=", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdLessThan(String value) {
            addCriterion("PBS_APPLY_ID <", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdLessThanOrEqualTo(String value) {
            addCriterion("PBS_APPLY_ID <=", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdLike(String value) {
            addCriterion("PBS_APPLY_ID like", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdNotLike(String value) {
            addCriterion("PBS_APPLY_ID not like", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdIn(List<String> values) {
            addCriterion("PBS_APPLY_ID in", values, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdNotIn(List<String> values) {
            addCriterion("PBS_APPLY_ID not in", values, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdBetween(String value1, String value2) {
            addCriterion("PBS_APPLY_ID between", value1, value2, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdNotBetween(String value1, String value2) {
            addCriterion("PBS_APPLY_ID not between", value1, value2, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyUnitIdIsNull() {
            addCriterion("PBS_APPLY_UNIT_ID is null");
            return this;
        }

        public Criteria andPbsApplyUnitIdIsNotNull() {
            addCriterion("PBS_APPLY_UNIT_ID is not null");
            return this;
        }

        public Criteria andPbsApplyUnitIdEqualTo(String value) {
            addCriterion("PBS_APPLY_UNIT_ID =", value, "pbsApplyUnitId");
            return this;
        }

        public Criteria andPbsApplyUnitIdNotEqualTo(String value) {
            addCriterion("PBS_APPLY_UNIT_ID <>", value, "pbsApplyUnitId");
            return this;
        }

        public Criteria andPbsApplyUnitIdGreaterThan(String value) {
            addCriterion("PBS_APPLY_UNIT_ID >", value, "pbsApplyUnitId");
            return this;
        }

        public Criteria andPbsApplyUnitIdGreaterThanOrEqualTo(String value) {
            addCriterion("PBS_APPLY_UNIT_ID >=", value, "pbsApplyUnitId");
            return this;
        }

        public Criteria andPbsApplyUnitIdLessThan(String value) {
            addCriterion("PBS_APPLY_UNIT_ID <", value, "pbsApplyUnitId");
            return this;
        }

        public Criteria andPbsApplyUnitIdLessThanOrEqualTo(String value) {
            addCriterion("PBS_APPLY_UNIT_ID <=", value, "pbsApplyUnitId");
            return this;
        }

        public Criteria andPbsApplyUnitIdLike(String value) {
            addCriterion("PBS_APPLY_UNIT_ID like", value, "pbsApplyUnitId");
            return this;
        }

        public Criteria andPbsApplyUnitIdNotLike(String value) {
            addCriterion("PBS_APPLY_UNIT_ID not like", value, "pbsApplyUnitId");
            return this;
        }

        public Criteria andPbsApplyUnitIdIn(List<String> values) {
            addCriterion("PBS_APPLY_UNIT_ID in", values, "pbsApplyUnitId");
            return this;
        }

        public Criteria andPbsApplyUnitIdNotIn(List<String> values) {
            addCriterion("PBS_APPLY_UNIT_ID not in", values, "pbsApplyUnitId");
            return this;
        }

        public Criteria andPbsApplyUnitIdBetween(String value1, String value2) {
            addCriterion("PBS_APPLY_UNIT_ID between", value1, value2, "pbsApplyUnitId");
            return this;
        }

        public Criteria andPbsApplyUnitIdNotBetween(String value1, String value2) {
            addCriterion("PBS_APPLY_UNIT_ID not between", value1, value2, "pbsApplyUnitId");
            return this;
        }

        public Criteria andPbsApplyUserIdIsNull() {
            addCriterion("PBS_APPLY_USER_ID is null");
            return this;
        }

        public Criteria andPbsApplyUserIdIsNotNull() {
            addCriterion("PBS_APPLY_USER_ID is not null");
            return this;
        }

        public Criteria andPbsApplyUserIdEqualTo(String value) {
            addCriterion("PBS_APPLY_USER_ID =", value, "pbsApplyUserId");
            return this;
        }

        public Criteria andPbsApplyUserIdNotEqualTo(String value) {
            addCriterion("PBS_APPLY_USER_ID <>", value, "pbsApplyUserId");
            return this;
        }

        public Criteria andPbsApplyUserIdGreaterThan(String value) {
            addCriterion("PBS_APPLY_USER_ID >", value, "pbsApplyUserId");
            return this;
        }

        public Criteria andPbsApplyUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("PBS_APPLY_USER_ID >=", value, "pbsApplyUserId");
            return this;
        }

        public Criteria andPbsApplyUserIdLessThan(String value) {
            addCriterion("PBS_APPLY_USER_ID <", value, "pbsApplyUserId");
            return this;
        }

        public Criteria andPbsApplyUserIdLessThanOrEqualTo(String value) {
            addCriterion("PBS_APPLY_USER_ID <=", value, "pbsApplyUserId");
            return this;
        }

        public Criteria andPbsApplyUserIdLike(String value) {
            addCriterion("PBS_APPLY_USER_ID like", value, "pbsApplyUserId");
            return this;
        }

        public Criteria andPbsApplyUserIdNotLike(String value) {
            addCriterion("PBS_APPLY_USER_ID not like", value, "pbsApplyUserId");
            return this;
        }

        public Criteria andPbsApplyUserIdIn(List<String> values) {
            addCriterion("PBS_APPLY_USER_ID in", values, "pbsApplyUserId");
            return this;
        }

        public Criteria andPbsApplyUserIdNotIn(List<String> values) {
            addCriterion("PBS_APPLY_USER_ID not in", values, "pbsApplyUserId");
            return this;
        }

        public Criteria andPbsApplyUserIdBetween(String value1, String value2) {
            addCriterion("PBS_APPLY_USER_ID between", value1, value2, "pbsApplyUserId");
            return this;
        }

        public Criteria andPbsApplyUserIdNotBetween(String value1, String value2) {
            addCriterion("PBS_APPLY_USER_ID not between", value1, value2, "pbsApplyUserId");
            return this;
        }

        public Criteria andPbsApplyTelIsNull() {
            addCriterion("PBS_APPLY_TEL is null");
            return this;
        }

        public Criteria andPbsApplyTelIsNotNull() {
            addCriterion("PBS_APPLY_TEL is not null");
            return this;
        }

        public Criteria andPbsApplyTelEqualTo(String value) {
            addCriterion("PBS_APPLY_TEL =", value, "pbsApplyTel");
            return this;
        }

        public Criteria andPbsApplyTelNotEqualTo(String value) {
            addCriterion("PBS_APPLY_TEL <>", value, "pbsApplyTel");
            return this;
        }

        public Criteria andPbsApplyTelGreaterThan(String value) {
            addCriterion("PBS_APPLY_TEL >", value, "pbsApplyTel");
            return this;
        }

        public Criteria andPbsApplyTelGreaterThanOrEqualTo(String value) {
            addCriterion("PBS_APPLY_TEL >=", value, "pbsApplyTel");
            return this;
        }

        public Criteria andPbsApplyTelLessThan(String value) {
            addCriterion("PBS_APPLY_TEL <", value, "pbsApplyTel");
            return this;
        }

        public Criteria andPbsApplyTelLessThanOrEqualTo(String value) {
            addCriterion("PBS_APPLY_TEL <=", value, "pbsApplyTel");
            return this;
        }

        public Criteria andPbsApplyTelLike(String value) {
            addCriterion("PBS_APPLY_TEL like", value, "pbsApplyTel");
            return this;
        }

        public Criteria andPbsApplyTelNotLike(String value) {
            addCriterion("PBS_APPLY_TEL not like", value, "pbsApplyTel");
            return this;
        }

        public Criteria andPbsApplyTelIn(List<String> values) {
            addCriterion("PBS_APPLY_TEL in", values, "pbsApplyTel");
            return this;
        }

        public Criteria andPbsApplyTelNotIn(List<String> values) {
            addCriterion("PBS_APPLY_TEL not in", values, "pbsApplyTel");
            return this;
        }

        public Criteria andPbsApplyTelBetween(String value1, String value2) {
            addCriterion("PBS_APPLY_TEL between", value1, value2, "pbsApplyTel");
            return this;
        }

        public Criteria andPbsApplyTelNotBetween(String value1, String value2) {
            addCriterion("PBS_APPLY_TEL not between", value1, value2, "pbsApplyTel");
            return this;
        }

        public Criteria andPbsApplyDateIsNull() {
            addCriterion("PBS_APPLY_DATE is null");
            return this;
        }

        public Criteria andPbsApplyDateIsNotNull() {
            addCriterion("PBS_APPLY_DATE is not null");
            return this;
        }

        public Criteria andPbsApplyDateEqualTo(Date value) {
            addCriterion("PBS_APPLY_DATE =", value, "pbsApplyDate");
            return this;
        }

        public Criteria andPbsApplyDateNotEqualTo(Date value) {
            addCriterion("PBS_APPLY_DATE <>", value, "pbsApplyDate");
            return this;
        }

        public Criteria andPbsApplyDateGreaterThan(Date value) {
            addCriterion("PBS_APPLY_DATE >", value, "pbsApplyDate");
            return this;
        }

        public Criteria andPbsApplyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("PBS_APPLY_DATE >=", value, "pbsApplyDate");
            return this;
        }

        public Criteria andPbsApplyDateLessThan(Date value) {
            addCriterion("PBS_APPLY_DATE <", value, "pbsApplyDate");
            return this;
        }

        public Criteria andPbsApplyDateLessThanOrEqualTo(Date value) {
            addCriterion("PBS_APPLY_DATE <=", value, "pbsApplyDate");
            return this;
        }

        public Criteria andPbsApplyDateIn(List<Date> values) {
            addCriterion("PBS_APPLY_DATE in", values, "pbsApplyDate");
            return this;
        }

        public Criteria andPbsApplyDateNotIn(List<Date> values) {
            addCriterion("PBS_APPLY_DATE not in", values, "pbsApplyDate");
            return this;
        }

        public Criteria andPbsApplyDateBetween(Date value1, Date value2) {
            addCriterion("PBS_APPLY_DATE between", value1, value2, "pbsApplyDate");
            return this;
        }

        public Criteria andPbsApplyDateNotBetween(Date value1, Date value2) {
            addCriterion("PBS_APPLY_DATE not between", value1, value2, "pbsApplyDate");
            return this;
        }

        public Criteria andPbsApplyStatusIsNull() {
            addCriterion("PBS_APPLY_STATUS is null");
            return this;
        }

        public Criteria andPbsApplyStatusIsNotNull() {
            addCriterion("PBS_APPLY_STATUS is not null");
            return this;
        }

        public Criteria andPbsApplyStatusEqualTo(String value) {
            addCriterion("PBS_APPLY_STATUS =", value, "pbsApplyStatus");
            return this;
        }

        public Criteria andPbsApplyStatusNotEqualTo(String value) {
            addCriterion("PBS_APPLY_STATUS <>", value, "pbsApplyStatus");
            return this;
        }

        public Criteria andPbsApplyStatusGreaterThan(String value) {
            addCriterion("PBS_APPLY_STATUS >", value, "pbsApplyStatus");
            return this;
        }

        public Criteria andPbsApplyStatusGreaterThanOrEqualTo(String value) {
            addCriterion("PBS_APPLY_STATUS >=", value, "pbsApplyStatus");
            return this;
        }

        public Criteria andPbsApplyStatusLessThan(String value) {
            addCriterion("PBS_APPLY_STATUS <", value, "pbsApplyStatus");
            return this;
        }

        public Criteria andPbsApplyStatusLessThanOrEqualTo(String value) {
            addCriterion("PBS_APPLY_STATUS <=", value, "pbsApplyStatus");
            return this;
        }

        public Criteria andPbsApplyStatusLike(String value) {
            addCriterion("PBS_APPLY_STATUS like", value, "pbsApplyStatus");
            return this;
        }

        public Criteria andPbsApplyStatusNotLike(String value) {
            addCriterion("PBS_APPLY_STATUS not like", value, "pbsApplyStatus");
            return this;
        }

        public Criteria andPbsApplyStatusIn(List<String> values) {
            addCriterion("PBS_APPLY_STATUS in", values, "pbsApplyStatus");
            return this;
        }

        public Criteria andPbsApplyStatusNotIn(List<String> values) {
            addCriterion("PBS_APPLY_STATUS not in", values, "pbsApplyStatus");
            return this;
        }

        public Criteria andPbsApplyStatusBetween(String value1, String value2) {
            addCriterion("PBS_APPLY_STATUS between", value1, value2, "pbsApplyStatus");
            return this;
        }

        public Criteria andPbsApplyStatusNotBetween(String value1, String value2) {
            addCriterion("PBS_APPLY_STATUS not between", value1, value2, "pbsApplyStatus");
            return this;
        }

        public Criteria andPbsApplyUserNameIsNull() {
            addCriterion("PBS_APPLY_USER_NAME is null");
            return this;
        }

        public Criteria andPbsApplyUserNameIsNotNull() {
            addCriterion("PBS_APPLY_USER_NAME is not null");
            return this;
        }

        public Criteria andPbsApplyUserNameEqualTo(String value) {
            addCriterion("PBS_APPLY_USER_NAME =", value, "pbsApplyUserName");
            return this;
        }

        public Criteria andPbsApplyUserNameNotEqualTo(String value) {
            addCriterion("PBS_APPLY_USER_NAME <>", value, "pbsApplyUserName");
            return this;
        }

        public Criteria andPbsApplyUserNameGreaterThan(String value) {
            addCriterion("PBS_APPLY_USER_NAME >", value, "pbsApplyUserName");
            return this;
        }

        public Criteria andPbsApplyUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("PBS_APPLY_USER_NAME >=", value, "pbsApplyUserName");
            return this;
        }

        public Criteria andPbsApplyUserNameLessThan(String value) {
            addCriterion("PBS_APPLY_USER_NAME <", value, "pbsApplyUserName");
            return this;
        }

        public Criteria andPbsApplyUserNameLessThanOrEqualTo(String value) {
            addCriterion("PBS_APPLY_USER_NAME <=", value, "pbsApplyUserName");
            return this;
        }

        public Criteria andPbsApplyUserNameLike(String value) {
            addCriterion("PBS_APPLY_USER_NAME like", value, "pbsApplyUserName");
            return this;
        }

        public Criteria andPbsApplyUserNameNotLike(String value) {
            addCriterion("PBS_APPLY_USER_NAME not like", value, "pbsApplyUserName");
            return this;
        }

        public Criteria andPbsApplyUserNameIn(List<String> values) {
            addCriterion("PBS_APPLY_USER_NAME in", values, "pbsApplyUserName");
            return this;
        }

        public Criteria andPbsApplyUserNameNotIn(List<String> values) {
            addCriterion("PBS_APPLY_USER_NAME not in", values, "pbsApplyUserName");
            return this;
        }

        public Criteria andPbsApplyUserNameBetween(String value1, String value2) {
            addCriterion("PBS_APPLY_USER_NAME between", value1, value2, "pbsApplyUserName");
            return this;
        }

        public Criteria andPbsApplyUserNameNotBetween(String value1, String value2) {
            addCriterion("PBS_APPLY_USER_NAME not between", value1, value2, "pbsApplyUserName");
            return this;
        }
    }
}