package com.tyust.bean.pbs;

import java.util.Date;

public class PbsAttach {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PBS_ATTACH.pbs_attach_id
     *
     * @ibatorgenerated
     */
    private String pbsAttachId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PBS_ATTACH.pbs_apply_id
     *
     * @ibatorgenerated
     */
    private String pbsApplyId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PBS_ATTACH.pbs_attach_url
     *
     * @ibatorgenerated
     */
    private String pbsAttachUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PBS_ATTACH.pbs_attach_name
     *
     * @ibatorgenerated
     */
    private String pbsAttachName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PBS_ATTACH.pbs_attach_type
     *
     * @ibatorgenerated
     */
    private String pbsAttachType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PBS_ATTACH.pbs_attach_date
     *
     * @ibatorgenerated
     */
    private Date pbsAttachDate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_ATTACH.pbs_attach_id
     *
     * @return the value of PBS_ATTACH.pbs_attach_id
     *
     * @ibatorgenerated
     */
    public String getPbsAttachId() {
        return pbsAttachId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_ATTACH.pbs_attach_id
     *
     * @param pbsAttachId the value for PBS_ATTACH.pbs_attach_id
     *
     * @ibatorgenerated
     */
    public void setPbsAttachId(String pbsAttachId) {
        this.pbsAttachId = pbsAttachId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_ATTACH.pbs_apply_id
     *
     * @return the value of PBS_ATTACH.pbs_apply_id
     *
     * @ibatorgenerated
     */
    public String getPbsApplyId() {
        return pbsApplyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_ATTACH.pbs_apply_id
     *
     * @param pbsApplyId the value for PBS_ATTACH.pbs_apply_id
     *
     * @ibatorgenerated
     */
    public void setPbsApplyId(String pbsApplyId) {
        this.pbsApplyId = pbsApplyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_ATTACH.pbs_attach_url
     *
     * @return the value of PBS_ATTACH.pbs_attach_url
     *
     * @ibatorgenerated
     */
    public String getPbsAttachUrl() {
        return pbsAttachUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_ATTACH.pbs_attach_url
     *
     * @param pbsAttachUrl the value for PBS_ATTACH.pbs_attach_url
     *
     * @ibatorgenerated
     */
    public void setPbsAttachUrl(String pbsAttachUrl) {
        this.pbsAttachUrl = pbsAttachUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_ATTACH.pbs_attach_name
     *
     * @return the value of PBS_ATTACH.pbs_attach_name
     *
     * @ibatorgenerated
     */
    public String getPbsAttachName() {
        return pbsAttachName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_ATTACH.pbs_attach_name
     *
     * @param pbsAttachName the value for PBS_ATTACH.pbs_attach_name
     *
     * @ibatorgenerated
     */
    public void setPbsAttachName(String pbsAttachName) {
        this.pbsAttachName = pbsAttachName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_ATTACH.pbs_attach_type
     *
     * @return the value of PBS_ATTACH.pbs_attach_type
     *
     * @ibatorgenerated
     */
    public String getPbsAttachType() {
        return pbsAttachType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_ATTACH.pbs_attach_type
     *
     * @param pbsAttachType the value for PBS_ATTACH.pbs_attach_type
     *
     * @ibatorgenerated
     */
    public void setPbsAttachType(String pbsAttachType) {
        this.pbsAttachType = pbsAttachType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_ATTACH.pbs_attach_date
     *
     * @return the value of PBS_ATTACH.pbs_attach_date
     *
     * @ibatorgenerated
     */
    public Date getPbsAttachDate() {
        return pbsAttachDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_ATTACH.pbs_attach_date
     *
     * @param pbsAttachDate the value for PBS_ATTACH.pbs_attach_date
     *
     * @ibatorgenerated
     */
    public void setPbsAttachDate(Date pbsAttachDate) {
        this.pbsAttachDate = pbsAttachDate;
    }
}