package com.tyust.bean.pbs;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PbsAttachExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public PbsAttachExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    protected PbsAttachExample(PbsAttachExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andPbsAttachIdIsNull() {
            addCriterion("pbs_attach_id is null");
            return this;
        }

        public Criteria andPbsAttachIdIsNotNull() {
            addCriterion("pbs_attach_id is not null");
            return this;
        }

        public Criteria andPbsAttachIdEqualTo(String value) {
            addCriterion("pbs_attach_id =", value, "pbsAttachId");
            return this;
        }

        public Criteria andPbsAttachIdNotEqualTo(String value) {
            addCriterion("pbs_attach_id <>", value, "pbsAttachId");
            return this;
        }

        public Criteria andPbsAttachIdGreaterThan(String value) {
            addCriterion("pbs_attach_id >", value, "pbsAttachId");
            return this;
        }

        public Criteria andPbsAttachIdGreaterThanOrEqualTo(String value) {
            addCriterion("pbs_attach_id >=", value, "pbsAttachId");
            return this;
        }

        public Criteria andPbsAttachIdLessThan(String value) {
            addCriterion("pbs_attach_id <", value, "pbsAttachId");
            return this;
        }

        public Criteria andPbsAttachIdLessThanOrEqualTo(String value) {
            addCriterion("pbs_attach_id <=", value, "pbsAttachId");
            return this;
        }

        public Criteria andPbsAttachIdLike(String value) {
            addCriterion("pbs_attach_id like", value, "pbsAttachId");
            return this;
        }

        public Criteria andPbsAttachIdNotLike(String value) {
            addCriterion("pbs_attach_id not like", value, "pbsAttachId");
            return this;
        }

        public Criteria andPbsAttachIdIn(List<String> values) {
            addCriterion("pbs_attach_id in", values, "pbsAttachId");
            return this;
        }

        public Criteria andPbsAttachIdNotIn(List<String> values) {
            addCriterion("pbs_attach_id not in", values, "pbsAttachId");
            return this;
        }

        public Criteria andPbsAttachIdBetween(String value1, String value2) {
            addCriterion("pbs_attach_id between", value1, value2, "pbsAttachId");
            return this;
        }

        public Criteria andPbsAttachIdNotBetween(String value1, String value2) {
            addCriterion("pbs_attach_id not between", value1, value2, "pbsAttachId");
            return this;
        }

        public Criteria andPbsApplyIdIsNull() {
            addCriterion("pbs_apply_id is null");
            return this;
        }

        public Criteria andPbsApplyIdIsNotNull() {
            addCriterion("pbs_apply_id is not null");
            return this;
        }

        public Criteria andPbsApplyIdEqualTo(String value) {
            addCriterion("pbs_apply_id =", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdNotEqualTo(String value) {
            addCriterion("pbs_apply_id <>", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdGreaterThan(String value) {
            addCriterion("pbs_apply_id >", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdGreaterThanOrEqualTo(String value) {
            addCriterion("pbs_apply_id >=", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdLessThan(String value) {
            addCriterion("pbs_apply_id <", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdLessThanOrEqualTo(String value) {
            addCriterion("pbs_apply_id <=", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdLike(String value) {
            addCriterion("pbs_apply_id like", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdNotLike(String value) {
            addCriterion("pbs_apply_id not like", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdIn(List<String> values) {
            addCriterion("pbs_apply_id in", values, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdNotIn(List<String> values) {
            addCriterion("pbs_apply_id not in", values, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdBetween(String value1, String value2) {
            addCriterion("pbs_apply_id between", value1, value2, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdNotBetween(String value1, String value2) {
            addCriterion("pbs_apply_id not between", value1, value2, "pbsApplyId");
            return this;
        }

        public Criteria andPbsAttachUrlIsNull() {
            addCriterion("pbs_attach_url is null");
            return this;
        }

        public Criteria andPbsAttachUrlIsNotNull() {
            addCriterion("pbs_attach_url is not null");
            return this;
        }

        public Criteria andPbsAttachUrlEqualTo(String value) {
            addCriterion("pbs_attach_url =", value, "pbsAttachUrl");
            return this;
        }

        public Criteria andPbsAttachUrlNotEqualTo(String value) {
            addCriterion("pbs_attach_url <>", value, "pbsAttachUrl");
            return this;
        }

        public Criteria andPbsAttachUrlGreaterThan(String value) {
            addCriterion("pbs_attach_url >", value, "pbsAttachUrl");
            return this;
        }

        public Criteria andPbsAttachUrlGreaterThanOrEqualTo(String value) {
            addCriterion("pbs_attach_url >=", value, "pbsAttachUrl");
            return this;
        }

        public Criteria andPbsAttachUrlLessThan(String value) {
            addCriterion("pbs_attach_url <", value, "pbsAttachUrl");
            return this;
        }

        public Criteria andPbsAttachUrlLessThanOrEqualTo(String value) {
            addCriterion("pbs_attach_url <=", value, "pbsAttachUrl");
            return this;
        }

        public Criteria andPbsAttachUrlLike(String value) {
            addCriterion("pbs_attach_url like", value, "pbsAttachUrl");
            return this;
        }

        public Criteria andPbsAttachUrlNotLike(String value) {
            addCriterion("pbs_attach_url not like", value, "pbsAttachUrl");
            return this;
        }

        public Criteria andPbsAttachUrlIn(List<String> values) {
            addCriterion("pbs_attach_url in", values, "pbsAttachUrl");
            return this;
        }

        public Criteria andPbsAttachUrlNotIn(List<String> values) {
            addCriterion("pbs_attach_url not in", values, "pbsAttachUrl");
            return this;
        }

        public Criteria andPbsAttachUrlBetween(String value1, String value2) {
            addCriterion("pbs_attach_url between", value1, value2, "pbsAttachUrl");
            return this;
        }

        public Criteria andPbsAttachUrlNotBetween(String value1, String value2) {
            addCriterion("pbs_attach_url not between", value1, value2, "pbsAttachUrl");
            return this;
        }

        public Criteria andPbsAttachNameIsNull() {
            addCriterion("pbs_attach_name is null");
            return this;
        }

        public Criteria andPbsAttachNameIsNotNull() {
            addCriterion("pbs_attach_name is not null");
            return this;
        }

        public Criteria andPbsAttachNameEqualTo(String value) {
            addCriterion("pbs_attach_name =", value, "pbsAttachName");
            return this;
        }

        public Criteria andPbsAttachNameNotEqualTo(String value) {
            addCriterion("pbs_attach_name <>", value, "pbsAttachName");
            return this;
        }

        public Criteria andPbsAttachNameGreaterThan(String value) {
            addCriterion("pbs_attach_name >", value, "pbsAttachName");
            return this;
        }

        public Criteria andPbsAttachNameGreaterThanOrEqualTo(String value) {
            addCriterion("pbs_attach_name >=", value, "pbsAttachName");
            return this;
        }

        public Criteria andPbsAttachNameLessThan(String value) {
            addCriterion("pbs_attach_name <", value, "pbsAttachName");
            return this;
        }

        public Criteria andPbsAttachNameLessThanOrEqualTo(String value) {
            addCriterion("pbs_attach_name <=", value, "pbsAttachName");
            return this;
        }

        public Criteria andPbsAttachNameLike(String value) {
            addCriterion("pbs_attach_name like", value, "pbsAttachName");
            return this;
        }

        public Criteria andPbsAttachNameNotLike(String value) {
            addCriterion("pbs_attach_name not like", value, "pbsAttachName");
            return this;
        }

        public Criteria andPbsAttachNameIn(List<String> values) {
            addCriterion("pbs_attach_name in", values, "pbsAttachName");
            return this;
        }

        public Criteria andPbsAttachNameNotIn(List<String> values) {
            addCriterion("pbs_attach_name not in", values, "pbsAttachName");
            return this;
        }

        public Criteria andPbsAttachNameBetween(String value1, String value2) {
            addCriterion("pbs_attach_name between", value1, value2, "pbsAttachName");
            return this;
        }

        public Criteria andPbsAttachNameNotBetween(String value1, String value2) {
            addCriterion("pbs_attach_name not between", value1, value2, "pbsAttachName");
            return this;
        }

        public Criteria andPbsAttachTypeIsNull() {
            addCriterion("pbs_attach_type is null");
            return this;
        }

        public Criteria andPbsAttachTypeIsNotNull() {
            addCriterion("pbs_attach_type is not null");
            return this;
        }

        public Criteria andPbsAttachTypeEqualTo(String value) {
            addCriterion("pbs_attach_type =", value, "pbsAttachType");
            return this;
        }

        public Criteria andPbsAttachTypeNotEqualTo(String value) {
            addCriterion("pbs_attach_type <>", value, "pbsAttachType");
            return this;
        }

        public Criteria andPbsAttachTypeGreaterThan(String value) {
            addCriterion("pbs_attach_type >", value, "pbsAttachType");
            return this;
        }

        public Criteria andPbsAttachTypeGreaterThanOrEqualTo(String value) {
            addCriterion("pbs_attach_type >=", value, "pbsAttachType");
            return this;
        }

        public Criteria andPbsAttachTypeLessThan(String value) {
            addCriterion("pbs_attach_type <", value, "pbsAttachType");
            return this;
        }

        public Criteria andPbsAttachTypeLessThanOrEqualTo(String value) {
            addCriterion("pbs_attach_type <=", value, "pbsAttachType");
            return this;
        }

        public Criteria andPbsAttachTypeLike(String value) {
            addCriterion("pbs_attach_type like", value, "pbsAttachType");
            return this;
        }

        public Criteria andPbsAttachTypeNotLike(String value) {
            addCriterion("pbs_attach_type not like", value, "pbsAttachType");
            return this;
        }

        public Criteria andPbsAttachTypeIn(List<String> values) {
            addCriterion("pbs_attach_type in", values, "pbsAttachType");
            return this;
        }

        public Criteria andPbsAttachTypeNotIn(List<String> values) {
            addCriterion("pbs_attach_type not in", values, "pbsAttachType");
            return this;
        }

        public Criteria andPbsAttachTypeBetween(String value1, String value2) {
            addCriterion("pbs_attach_type between", value1, value2, "pbsAttachType");
            return this;
        }

        public Criteria andPbsAttachTypeNotBetween(String value1, String value2) {
            addCriterion("pbs_attach_type not between", value1, value2, "pbsAttachType");
            return this;
        }

        public Criteria andPbsAttachDateIsNull() {
            addCriterion("pbs_attach_date is null");
            return this;
        }

        public Criteria andPbsAttachDateIsNotNull() {
            addCriterion("pbs_attach_date is not null");
            return this;
        }

        public Criteria andPbsAttachDateEqualTo(Date value) {
            addCriterion("pbs_attach_date =", value, "pbsAttachDate");
            return this;
        }

        public Criteria andPbsAttachDateNotEqualTo(Date value) {
            addCriterion("pbs_attach_date <>", value, "pbsAttachDate");
            return this;
        }

        public Criteria andPbsAttachDateGreaterThan(Date value) {
            addCriterion("pbs_attach_date >", value, "pbsAttachDate");
            return this;
        }

        public Criteria andPbsAttachDateGreaterThanOrEqualTo(Date value) {
            addCriterion("pbs_attach_date >=", value, "pbsAttachDate");
            return this;
        }

        public Criteria andPbsAttachDateLessThan(Date value) {
            addCriterion("pbs_attach_date <", value, "pbsAttachDate");
            return this;
        }

        public Criteria andPbsAttachDateLessThanOrEqualTo(Date value) {
            addCriterion("pbs_attach_date <=", value, "pbsAttachDate");
            return this;
        }

        public Criteria andPbsAttachDateIn(List<Date> values) {
            addCriterion("pbs_attach_date in", values, "pbsAttachDate");
            return this;
        }

        public Criteria andPbsAttachDateNotIn(List<Date> values) {
            addCriterion("pbs_attach_date not in", values, "pbsAttachDate");
            return this;
        }

        public Criteria andPbsAttachDateBetween(Date value1, Date value2) {
            addCriterion("pbs_attach_date between", value1, value2, "pbsAttachDate");
            return this;
        }

        public Criteria andPbsAttachDateNotBetween(Date value1, Date value2) {
            addCriterion("pbs_attach_date not between", value1, value2, "pbsAttachDate");
            return this;
        }
    }
}