package com.tyust.bean.pbs;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PbsPicExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public PbsPicExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    protected PbsPicExample(PbsPicExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andPbsPicIdIsNull() {
            addCriterion("PBS_PIC_ID is null");
            return this;
        }

        public Criteria andPbsPicIdIsNotNull() {
            addCriterion("PBS_PIC_ID is not null");
            return this;
        }

        public Criteria andPbsPicIdEqualTo(String value) {
            addCriterion("PBS_PIC_ID =", value, "pbsPicId");
            return this;
        }

        public Criteria andPbsPicIdNotEqualTo(String value) {
            addCriterion("PBS_PIC_ID <>", value, "pbsPicId");
            return this;
        }

        public Criteria andPbsPicIdGreaterThan(String value) {
            addCriterion("PBS_PIC_ID >", value, "pbsPicId");
            return this;
        }

        public Criteria andPbsPicIdGreaterThanOrEqualTo(String value) {
            addCriterion("PBS_PIC_ID >=", value, "pbsPicId");
            return this;
        }

        public Criteria andPbsPicIdLessThan(String value) {
            addCriterion("PBS_PIC_ID <", value, "pbsPicId");
            return this;
        }

        public Criteria andPbsPicIdLessThanOrEqualTo(String value) {
            addCriterion("PBS_PIC_ID <=", value, "pbsPicId");
            return this;
        }

        public Criteria andPbsPicIdLike(String value) {
            addCriterion("PBS_PIC_ID like", value, "pbsPicId");
            return this;
        }

        public Criteria andPbsPicIdNotLike(String value) {
            addCriterion("PBS_PIC_ID not like", value, "pbsPicId");
            return this;
        }

        public Criteria andPbsPicIdIn(List<String> values) {
            addCriterion("PBS_PIC_ID in", values, "pbsPicId");
            return this;
        }

        public Criteria andPbsPicIdNotIn(List<String> values) {
            addCriterion("PBS_PIC_ID not in", values, "pbsPicId");
            return this;
        }

        public Criteria andPbsPicIdBetween(String value1, String value2) {
            addCriterion("PBS_PIC_ID between", value1, value2, "pbsPicId");
            return this;
        }

        public Criteria andPbsPicIdNotBetween(String value1, String value2) {
            addCriterion("PBS_PIC_ID not between", value1, value2, "pbsPicId");
            return this;
        }

        public Criteria andPbsApplyIdIsNull() {
            addCriterion("PBS_APPLY_ID is null");
            return this;
        }

        public Criteria andPbsApplyIdIsNotNull() {
            addCriterion("PBS_APPLY_ID is not null");
            return this;
        }

        public Criteria andPbsApplyIdEqualTo(String value) {
            addCriterion("PBS_APPLY_ID =", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdNotEqualTo(String value) {
            addCriterion("PBS_APPLY_ID <>", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdGreaterThan(String value) {
            addCriterion("PBS_APPLY_ID >", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdGreaterThanOrEqualTo(String value) {
            addCriterion("PBS_APPLY_ID >=", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdLessThan(String value) {
            addCriterion("PBS_APPLY_ID <", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdLessThanOrEqualTo(String value) {
            addCriterion("PBS_APPLY_ID <=", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdLike(String value) {
            addCriterion("PBS_APPLY_ID like", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdNotLike(String value) {
            addCriterion("PBS_APPLY_ID not like", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdIn(List<String> values) {
            addCriterion("PBS_APPLY_ID in", values, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdNotIn(List<String> values) {
            addCriterion("PBS_APPLY_ID not in", values, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdBetween(String value1, String value2) {
            addCriterion("PBS_APPLY_ID between", value1, value2, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdNotBetween(String value1, String value2) {
            addCriterion("PBS_APPLY_ID not between", value1, value2, "pbsApplyId");
            return this;
        }

        public Criteria andPbsPicUrlIsNull() {
            addCriterion("PBS_PIC_URL is null");
            return this;
        }

        public Criteria andPbsPicUrlIsNotNull() {
            addCriterion("PBS_PIC_URL is not null");
            return this;
        }

        public Criteria andPbsPicUrlEqualTo(String value) {
            addCriterion("PBS_PIC_URL =", value, "pbsPicUrl");
            return this;
        }

        public Criteria andPbsPicUrlNotEqualTo(String value) {
            addCriterion("PBS_PIC_URL <>", value, "pbsPicUrl");
            return this;
        }

        public Criteria andPbsPicUrlGreaterThan(String value) {
            addCriterion("PBS_PIC_URL >", value, "pbsPicUrl");
            return this;
        }

        public Criteria andPbsPicUrlGreaterThanOrEqualTo(String value) {
            addCriterion("PBS_PIC_URL >=", value, "pbsPicUrl");
            return this;
        }

        public Criteria andPbsPicUrlLessThan(String value) {
            addCriterion("PBS_PIC_URL <", value, "pbsPicUrl");
            return this;
        }

        public Criteria andPbsPicUrlLessThanOrEqualTo(String value) {
            addCriterion("PBS_PIC_URL <=", value, "pbsPicUrl");
            return this;
        }

        public Criteria andPbsPicUrlLike(String value) {
            addCriterion("PBS_PIC_URL like", value, "pbsPicUrl");
            return this;
        }

        public Criteria andPbsPicUrlNotLike(String value) {
            addCriterion("PBS_PIC_URL not like", value, "pbsPicUrl");
            return this;
        }

        public Criteria andPbsPicUrlIn(List<String> values) {
            addCriterion("PBS_PIC_URL in", values, "pbsPicUrl");
            return this;
        }

        public Criteria andPbsPicUrlNotIn(List<String> values) {
            addCriterion("PBS_PIC_URL not in", values, "pbsPicUrl");
            return this;
        }

        public Criteria andPbsPicUrlBetween(String value1, String value2) {
            addCriterion("PBS_PIC_URL between", value1, value2, "pbsPicUrl");
            return this;
        }

        public Criteria andPbsPicUrlNotBetween(String value1, String value2) {
            addCriterion("PBS_PIC_URL not between", value1, value2, "pbsPicUrl");
            return this;
        }

        public Criteria andPbsPicNameIsNull() {
            addCriterion("PBS_PIC_NAME is null");
            return this;
        }

        public Criteria andPbsPicNameIsNotNull() {
            addCriterion("PBS_PIC_NAME is not null");
            return this;
        }

        public Criteria andPbsPicNameEqualTo(String value) {
            addCriterion("PBS_PIC_NAME =", value, "pbsPicName");
            return this;
        }

        public Criteria andPbsPicNameNotEqualTo(String value) {
            addCriterion("PBS_PIC_NAME <>", value, "pbsPicName");
            return this;
        }

        public Criteria andPbsPicNameGreaterThan(String value) {
            addCriterion("PBS_PIC_NAME >", value, "pbsPicName");
            return this;
        }

        public Criteria andPbsPicNameGreaterThanOrEqualTo(String value) {
            addCriterion("PBS_PIC_NAME >=", value, "pbsPicName");
            return this;
        }

        public Criteria andPbsPicNameLessThan(String value) {
            addCriterion("PBS_PIC_NAME <", value, "pbsPicName");
            return this;
        }

        public Criteria andPbsPicNameLessThanOrEqualTo(String value) {
            addCriterion("PBS_PIC_NAME <=", value, "pbsPicName");
            return this;
        }

        public Criteria andPbsPicNameLike(String value) {
            addCriterion("PBS_PIC_NAME like", value, "pbsPicName");
            return this;
        }

        public Criteria andPbsPicNameNotLike(String value) {
            addCriterion("PBS_PIC_NAME not like", value, "pbsPicName");
            return this;
        }

        public Criteria andPbsPicNameIn(List<String> values) {
            addCriterion("PBS_PIC_NAME in", values, "pbsPicName");
            return this;
        }

        public Criteria andPbsPicNameNotIn(List<String> values) {
            addCriterion("PBS_PIC_NAME not in", values, "pbsPicName");
            return this;
        }

        public Criteria andPbsPicNameBetween(String value1, String value2) {
            addCriterion("PBS_PIC_NAME between", value1, value2, "pbsPicName");
            return this;
        }

        public Criteria andPbsPicNameNotBetween(String value1, String value2) {
            addCriterion("PBS_PIC_NAME not between", value1, value2, "pbsPicName");
            return this;
        }

        public Criteria andPbsPicTypeIsNull() {
            addCriterion("PBS_PIC_TYPE is null");
            return this;
        }

        public Criteria andPbsPicTypeIsNotNull() {
            addCriterion("PBS_PIC_TYPE is not null");
            return this;
        }

        public Criteria andPbsPicTypeEqualTo(String value) {
            addCriterion("PBS_PIC_TYPE =", value, "pbsPicType");
            return this;
        }

        public Criteria andPbsPicTypeNotEqualTo(String value) {
            addCriterion("PBS_PIC_TYPE <>", value, "pbsPicType");
            return this;
        }

        public Criteria andPbsPicTypeGreaterThan(String value) {
            addCriterion("PBS_PIC_TYPE >", value, "pbsPicType");
            return this;
        }

        public Criteria andPbsPicTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PBS_PIC_TYPE >=", value, "pbsPicType");
            return this;
        }

        public Criteria andPbsPicTypeLessThan(String value) {
            addCriterion("PBS_PIC_TYPE <", value, "pbsPicType");
            return this;
        }

        public Criteria andPbsPicTypeLessThanOrEqualTo(String value) {
            addCriterion("PBS_PIC_TYPE <=", value, "pbsPicType");
            return this;
        }

        public Criteria andPbsPicTypeLike(String value) {
            addCriterion("PBS_PIC_TYPE like", value, "pbsPicType");
            return this;
        }

        public Criteria andPbsPicTypeNotLike(String value) {
            addCriterion("PBS_PIC_TYPE not like", value, "pbsPicType");
            return this;
        }

        public Criteria andPbsPicTypeIn(List<String> values) {
            addCriterion("PBS_PIC_TYPE in", values, "pbsPicType");
            return this;
        }

        public Criteria andPbsPicTypeNotIn(List<String> values) {
            addCriterion("PBS_PIC_TYPE not in", values, "pbsPicType");
            return this;
        }

        public Criteria andPbsPicTypeBetween(String value1, String value2) {
            addCriterion("PBS_PIC_TYPE between", value1, value2, "pbsPicType");
            return this;
        }

        public Criteria andPbsPicTypeNotBetween(String value1, String value2) {
            addCriterion("PBS_PIC_TYPE not between", value1, value2, "pbsPicType");
            return this;
        }

        public Criteria andPbsPicDateIsNull() {
            addCriterion("PBS_PIC_DATE is null");
            return this;
        }

        public Criteria andPbsPicDateIsNotNull() {
            addCriterion("PBS_PIC_DATE is not null");
            return this;
        }

        public Criteria andPbsPicDateEqualTo(Date value) {
            addCriterion("PBS_PIC_DATE =", value, "pbsPicDate");
            return this;
        }

        public Criteria andPbsPicDateNotEqualTo(Date value) {
            addCriterion("PBS_PIC_DATE <>", value, "pbsPicDate");
            return this;
        }

        public Criteria andPbsPicDateGreaterThan(Date value) {
            addCriterion("PBS_PIC_DATE >", value, "pbsPicDate");
            return this;
        }

        public Criteria andPbsPicDateGreaterThanOrEqualTo(Date value) {
            addCriterion("PBS_PIC_DATE >=", value, "pbsPicDate");
            return this;
        }

        public Criteria andPbsPicDateLessThan(Date value) {
            addCriterion("PBS_PIC_DATE <", value, "pbsPicDate");
            return this;
        }

        public Criteria andPbsPicDateLessThanOrEqualTo(Date value) {
            addCriterion("PBS_PIC_DATE <=", value, "pbsPicDate");
            return this;
        }

        public Criteria andPbsPicDateIn(List<Date> values) {
            addCriterion("PBS_PIC_DATE in", values, "pbsPicDate");
            return this;
        }

        public Criteria andPbsPicDateNotIn(List<Date> values) {
            addCriterion("PBS_PIC_DATE not in", values, "pbsPicDate");
            return this;
        }

        public Criteria andPbsPicDateBetween(Date value1, Date value2) {
            addCriterion("PBS_PIC_DATE between", value1, value2, "pbsPicDate");
            return this;
        }

        public Criteria andPbsPicDateNotBetween(Date value1, Date value2) {
            addCriterion("PBS_PIC_DATE not between", value1, value2, "pbsPicDate");
            return this;
        }
    }
}