package com.tyust.bean.pbs;

import java.util.Date;

public class PbsPic {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PBS_PIC.PBS_PIC_ID
     *
     * @ibatorgenerated
     */
    private String pbsPicId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PBS_PIC.PBS_APPLY_ID
     *
     * @ibatorgenerated
     */
    private String pbsApplyId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PBS_PIC.PBS_PIC_URL
     *
     * @ibatorgenerated
     */
    private String pbsPicUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PBS_PIC.PBS_PIC_NAME
     *
     * @ibatorgenerated
     */
    private String pbsPicName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PBS_PIC.PBS_PIC_TYPE
     *
     * @ibatorgenerated
     */
    private String pbsPicType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PBS_PIC.PBS_PIC_DATE
     *
     * @ibatorgenerated
     */
    private Date pbsPicDate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_PIC.PBS_PIC_ID
     *
     * @return the value of PBS_PIC.PBS_PIC_ID
     *
     * @ibatorgenerated
     */
    public String getPbsPicId() {
        return pbsPicId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_PIC.PBS_PIC_ID
     *
     * @param pbsPicId the value for PBS_PIC.PBS_PIC_ID
     *
     * @ibatorgenerated
     */
    public void setPbsPicId(String pbsPicId) {
        this.pbsPicId = pbsPicId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_PIC.PBS_APPLY_ID
     *
     * @return the value of PBS_PIC.PBS_APPLY_ID
     *
     * @ibatorgenerated
     */
    public String getPbsApplyId() {
        return pbsApplyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_PIC.PBS_APPLY_ID
     *
     * @param pbsApplyId the value for PBS_PIC.PBS_APPLY_ID
     *
     * @ibatorgenerated
     */
    public void setPbsApplyId(String pbsApplyId) {
        this.pbsApplyId = pbsApplyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_PIC.PBS_PIC_URL
     *
     * @return the value of PBS_PIC.PBS_PIC_URL
     *
     * @ibatorgenerated
     */
    public String getPbsPicUrl() {
        return pbsPicUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_PIC.PBS_PIC_URL
     *
     * @param pbsPicUrl the value for PBS_PIC.PBS_PIC_URL
     *
     * @ibatorgenerated
     */
    public void setPbsPicUrl(String pbsPicUrl) {
        this.pbsPicUrl = pbsPicUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_PIC.PBS_PIC_NAME
     *
     * @return the value of PBS_PIC.PBS_PIC_NAME
     *
     * @ibatorgenerated
     */
    public String getPbsPicName() {
        return pbsPicName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_PIC.PBS_PIC_NAME
     *
     * @param pbsPicName the value for PBS_PIC.PBS_PIC_NAME
     *
     * @ibatorgenerated
     */
    public void setPbsPicName(String pbsPicName) {
        this.pbsPicName = pbsPicName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_PIC.PBS_PIC_TYPE
     *
     * @return the value of PBS_PIC.PBS_PIC_TYPE
     *
     * @ibatorgenerated
     */
    public String getPbsPicType() {
        return pbsPicType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_PIC.PBS_PIC_TYPE
     *
     * @param pbsPicType the value for PBS_PIC.PBS_PIC_TYPE
     *
     * @ibatorgenerated
     */
    public void setPbsPicType(String pbsPicType) {
        this.pbsPicType = pbsPicType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_PIC.PBS_PIC_DATE
     *
     * @return the value of PBS_PIC.PBS_PIC_DATE
     *
     * @ibatorgenerated
     */
    public Date getPbsPicDate() {
        return pbsPicDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_PIC.PBS_PIC_DATE
     *
     * @param pbsPicDate the value for PBS_PIC.PBS_PIC_DATE
     *
     * @ibatorgenerated
     */
    public void setPbsPicDate(Date pbsPicDate) {
        this.pbsPicDate = pbsPicDate;
    }
}