package com.tyust.bean.pbs;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.tyust.common.IbatorGenExamplePageHelper;

public class PbsTestReportExample extends IbatorGenExamplePageHelper{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public PbsTestReportExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    protected PbsTestReportExample(PbsTestReportExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andPbsTestReportIdIsNull() {
            addCriterion("pbs_test_report_id is null");
            return this;
        }

        public Criteria andPbsTestReportIdIsNotNull() {
            addCriterion("pbs_test_report_id is not null");
            return this;
        }

        public Criteria andPbsTestReportIdEqualTo(String value) {
            addCriterion("pbs_test_report_id =", value, "pbsTestReportId");
            return this;
        }

        public Criteria andPbsTestReportIdNotEqualTo(String value) {
            addCriterion("pbs_test_report_id <>", value, "pbsTestReportId");
            return this;
        }

        public Criteria andPbsTestReportIdGreaterThan(String value) {
            addCriterion("pbs_test_report_id >", value, "pbsTestReportId");
            return this;
        }

        public Criteria andPbsTestReportIdGreaterThanOrEqualTo(String value) {
            addCriterion("pbs_test_report_id >=", value, "pbsTestReportId");
            return this;
        }

        public Criteria andPbsTestReportIdLessThan(String value) {
            addCriterion("pbs_test_report_id <", value, "pbsTestReportId");
            return this;
        }

        public Criteria andPbsTestReportIdLessThanOrEqualTo(String value) {
            addCriterion("pbs_test_report_id <=", value, "pbsTestReportId");
            return this;
        }

        public Criteria andPbsTestReportIdLike(String value) {
            addCriterion("pbs_test_report_id like", value, "pbsTestReportId");
            return this;
        }

        public Criteria andPbsTestReportIdNotLike(String value) {
            addCriterion("pbs_test_report_id not like", value, "pbsTestReportId");
            return this;
        }

        public Criteria andPbsTestReportIdIn(List<String> values) {
            addCriterion("pbs_test_report_id in", values, "pbsTestReportId");
            return this;
        }

        public Criteria andPbsTestReportIdNotIn(List<String> values) {
            addCriterion("pbs_test_report_id not in", values, "pbsTestReportId");
            return this;
        }

        public Criteria andPbsTestReportIdBetween(String value1, String value2) {
            addCriterion("pbs_test_report_id between", value1, value2, "pbsTestReportId");
            return this;
        }

        public Criteria andPbsTestReportIdNotBetween(String value1, String value2) {
            addCriterion("pbs_test_report_id not between", value1, value2, "pbsTestReportId");
            return this;
        }

        public Criteria andPbsApplyIdIsNull() {
            addCriterion("pbs_apply_id is null");
            return this;
        }

        public Criteria andPbsApplyIdIsNotNull() {
            addCriterion("pbs_apply_id is not null");
            return this;
        }

        public Criteria andPbsApplyIdEqualTo(String value) {
            addCriterion("pbs_apply_id =", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdNotEqualTo(String value) {
            addCriterion("pbs_apply_id <>", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdGreaterThan(String value) {
            addCriterion("pbs_apply_id >", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdGreaterThanOrEqualTo(String value) {
            addCriterion("pbs_apply_id >=", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdLessThan(String value) {
            addCriterion("pbs_apply_id <", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdLessThanOrEqualTo(String value) {
            addCriterion("pbs_apply_id <=", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdLike(String value) {
            addCriterion("pbs_apply_id like", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdNotLike(String value) {
            addCriterion("pbs_apply_id not like", value, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdIn(List<String> values) {
            addCriterion("pbs_apply_id in", values, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdNotIn(List<String> values) {
            addCriterion("pbs_apply_id not in", values, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdBetween(String value1, String value2) {
            addCriterion("pbs_apply_id between", value1, value2, "pbsApplyId");
            return this;
        }

        public Criteria andPbsApplyIdNotBetween(String value1, String value2) {
            addCriterion("pbs_apply_id not between", value1, value2, "pbsApplyId");
            return this;
        }

        public Criteria andTestReportNumberIsNull() {
            addCriterion("test_report_number is null");
            return this;
        }

        public Criteria andTestReportNumberIsNotNull() {
            addCriterion("test_report_number is not null");
            return this;
        }

        public Criteria andTestReportNumberEqualTo(String value) {
            addCriterion("test_report_number =", value, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberNotEqualTo(String value) {
            addCriterion("test_report_number <>", value, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberGreaterThan(String value) {
            addCriterion("test_report_number >", value, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberGreaterThanOrEqualTo(String value) {
            addCriterion("test_report_number >=", value, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberLessThan(String value) {
            addCriterion("test_report_number <", value, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberLessThanOrEqualTo(String value) {
            addCriterion("test_report_number <=", value, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberLike(String value) {
            addCriterion("test_report_number like", value, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberNotLike(String value) {
            addCriterion("test_report_number not like", value, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberIn(List<String> values) {
            addCriterion("test_report_number in", values, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberNotIn(List<String> values) {
            addCriterion("test_report_number not in", values, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberBetween(String value1, String value2) {
            addCriterion("test_report_number between", value1, value2, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberNotBetween(String value1, String value2) {
            addCriterion("test_report_number not between", value1, value2, "testReportNumber");
            return this;
        }

        public Criteria andTestUserNameIsNull() {
            addCriterion("test_user_name is null");
            return this;
        }

        public Criteria andTestUserNameIsNotNull() {
            addCriterion("test_user_name is not null");
            return this;
        }

        public Criteria andTestUserNameEqualTo(String value) {
            addCriterion("test_user_name =", value, "testUserName");
            return this;
        }

        public Criteria andTestUserNameNotEqualTo(String value) {
            addCriterion("test_user_name <>", value, "testUserName");
            return this;
        }

        public Criteria andTestUserNameGreaterThan(String value) {
            addCriterion("test_user_name >", value, "testUserName");
            return this;
        }

        public Criteria andTestUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("test_user_name >=", value, "testUserName");
            return this;
        }

        public Criteria andTestUserNameLessThan(String value) {
            addCriterion("test_user_name <", value, "testUserName");
            return this;
        }

        public Criteria andTestUserNameLessThanOrEqualTo(String value) {
            addCriterion("test_user_name <=", value, "testUserName");
            return this;
        }

        public Criteria andTestUserNameLike(String value) {
            addCriterion("test_user_name like", value, "testUserName");
            return this;
        }

        public Criteria andTestUserNameNotLike(String value) {
            addCriterion("test_user_name not like", value, "testUserName");
            return this;
        }

        public Criteria andTestUserNameIn(List<String> values) {
            addCriterion("test_user_name in", values, "testUserName");
            return this;
        }

        public Criteria andTestUserNameNotIn(List<String> values) {
            addCriterion("test_user_name not in", values, "testUserName");
            return this;
        }

        public Criteria andTestUserNameBetween(String value1, String value2) {
            addCriterion("test_user_name between", value1, value2, "testUserName");
            return this;
        }

        public Criteria andTestUserNameNotBetween(String value1, String value2) {
            addCriterion("test_user_name not between", value1, value2, "testUserName");
            return this;
        }

        public Criteria andTestDateIsNull() {
            addCriterion("test_date is null");
            return this;
        }

        public Criteria andTestDateIsNotNull() {
            addCriterion("test_date is not null");
            return this;
        }

        public Criteria andTestDateEqualTo(Date value) {
            addCriterion("test_date =", value, "testDate");
            return this;
        }

        public Criteria andTestDateNotEqualTo(Date value) {
            addCriterion("test_date <>", value, "testDate");
            return this;
        }

        public Criteria andTestDateGreaterThan(Date value) {
            addCriterion("test_date >", value, "testDate");
            return this;
        }

        public Criteria andTestDateGreaterThanOrEqualTo(Date value) {
            addCriterion("test_date >=", value, "testDate");
            return this;
        }

        public Criteria andTestDateLessThan(Date value) {
            addCriterion("test_date <", value, "testDate");
            return this;
        }

        public Criteria andTestDateLessThanOrEqualTo(Date value) {
            addCriterion("test_date <=", value, "testDate");
            return this;
        }

        public Criteria andTestDateIn(List<Date> values) {
            addCriterion("test_date in", values, "testDate");
            return this;
        }

        public Criteria andTestDateNotIn(List<Date> values) {
            addCriterion("test_date not in", values, "testDate");
            return this;
        }

        public Criteria andTestDateBetween(Date value1, Date value2) {
            addCriterion("test_date between", value1, value2, "testDate");
            return this;
        }

        public Criteria andTestDateNotBetween(Date value1, Date value2) {
            addCriterion("test_date not between", value1, value2, "testDate");
            return this;
        }

        public Criteria andTestStatusIsNull() {
            addCriterion("test_status is null");
            return this;
        }

        public Criteria andTestStatusIsNotNull() {
            addCriterion("test_status is not null");
            return this;
        }

        public Criteria andTestStatusEqualTo(String value) {
            addCriterion("test_status =", value, "testStatus");
            return this;
        }

        public Criteria andTestStatusNotEqualTo(String value) {
            addCriterion("test_status <>", value, "testStatus");
            return this;
        }

        public Criteria andTestStatusGreaterThan(String value) {
            addCriterion("test_status >", value, "testStatus");
            return this;
        }

        public Criteria andTestStatusGreaterThanOrEqualTo(String value) {
            addCriterion("test_status >=", value, "testStatus");
            return this;
        }

        public Criteria andTestStatusLessThan(String value) {
            addCriterion("test_status <", value, "testStatus");
            return this;
        }

        public Criteria andTestStatusLessThanOrEqualTo(String value) {
            addCriterion("test_status <=", value, "testStatus");
            return this;
        }

        public Criteria andTestStatusLike(String value) {
            addCriterion("test_status like", value, "testStatus");
            return this;
        }

        public Criteria andTestStatusNotLike(String value) {
            addCriterion("test_status not like", value, "testStatus");
            return this;
        }

        public Criteria andTestStatusIn(List<String> values) {
            addCriterion("test_status in", values, "testStatus");
            return this;
        }

        public Criteria andTestStatusNotIn(List<String> values) {
            addCriterion("test_status not in", values, "testStatus");
            return this;
        }

        public Criteria andTestStatusBetween(String value1, String value2) {
            addCriterion("test_status between", value1, value2, "testStatus");
            return this;
        }

        public Criteria andTestStatusNotBetween(String value1, String value2) {
            addCriterion("test_status not between", value1, value2, "testStatus");
            return this;
        }
    }
}