package com.tyust.bean.pbs;

import java.util.Date;

public class PbsTestReport {

    private String pbsTestReportId;

    private String pbsApplyId;

    private String testReportNumber;

    private String testUserName;

    private Date testDate;

    private String testStatus;


    public String getPbsTestReportId() {
        return pbsTestReportId;
    }


    public void setPbsTestReportId(String pbsTestReportId) {
        this.pbsTestReportId = pbsTestReportId;
    }


    public String getPbsApplyId() {
        return pbsApplyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_TEST_REPORT.pbs_apply_id
     *
     * @param pbsApplyId the value for PBS_TEST_REPORT.pbs_apply_id
     *
     * @ibatorgenerated
     */
    public void setPbsApplyId(String pbsApplyId) {
        this.pbsApplyId = pbsApplyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_TEST_REPORT.test_report_number
     *
     * @return the value of PBS_TEST_REPORT.test_report_number
     *
     * @ibatorgenerated
     */
    public String getTestReportNumber() {
        return testReportNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_TEST_REPORT.test_report_number
     *
     * @param testReportNumber the value for PBS_TEST_REPORT.test_report_number
     *
     * @ibatorgenerated
     */
    public void setTestReportNumber(String testReportNumber) {
        this.testReportNumber = testReportNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_TEST_REPORT.test_user_name
     *
     * @return the value of PBS_TEST_REPORT.test_user_name
     *
     * @ibatorgenerated
     */
    public String getTestUserName() {
        return testUserName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_TEST_REPORT.test_user_name
     *
     * @param testUserName the value for PBS_TEST_REPORT.test_user_name
     *
     * @ibatorgenerated
     */
    public void setTestUserName(String testUserName) {
        this.testUserName = testUserName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_TEST_REPORT.test_date
     *
     * @return the value of PBS_TEST_REPORT.test_date
     *
     * @ibatorgenerated
     */
    public Date getTestDate() {
        return testDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_TEST_REPORT.test_date
     *
     * @param testDate the value for PBS_TEST_REPORT.test_date
     *
     * @ibatorgenerated
     */
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_TEST_REPORT.test_status
     *
     * @return the value of PBS_TEST_REPORT.test_status
     *
     * @ibatorgenerated
     */
    public String getTestStatus() {
        return testStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_TEST_REPORT.test_status
     *
     * @param testStatus the value for PBS_TEST_REPORT.test_status
     *
     * @ibatorgenerated
     */
    public void setTestStatus(String testStatus) {
        this.testStatus = testStatus;
    }
}