package com.tyust.bean.pbs;

import java.util.Date;

import org.apache.struts2.json.annotations.JSON;

public class PbsTestReport {
	
	/************ S ll 屏蔽室检测报告增加的字段**********/
	private String pbsTestSampleName;//样品名称

    private String pbsTestTypeSpecification;//型号规格

    private String pbsTestTemperature;//温度

    private String pbsTestHumidity;//湿度

    private String pbsTestProject;//检测项目

    private String pbsTestStandard;//依据标准

    private String pbsTestLocation;//检测位置

    private String pbsTestGrade;//符合性能依据（等级）

    private String pbsTestConclusion;//检测结论

    private Date pbsTestCompletionTime;//建成时间

    private String pbsTestPbsStatus;//状态

    private String pbsTestPbsSize;//尺寸
	/************ D ll 屏蔽室检测报告增加的字段**********/
	
    private String pbsTestReportId;

    private String pbsApplyId;

    private String testReportNumber;

    private String testUserName;

    private Date testDate;

    private String testStatus;


    public String getPbsTestReportId() {
        return pbsTestReportId;
    }


    public void setPbsTestReportId(String pbsTestReportId) {
        this.pbsTestReportId = pbsTestReportId;
    }


    public String getPbsApplyId() {
        return pbsApplyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_TEST_REPORT.pbs_apply_id
     *
     * @param pbsApplyId the value for PBS_TEST_REPORT.pbs_apply_id
     *
     * @ibatorgenerated
     */
    public void setPbsApplyId(String pbsApplyId) {
        this.pbsApplyId = pbsApplyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_TEST_REPORT.test_report_number
     *
     * @return the value of PBS_TEST_REPORT.test_report_number
     *
     * @ibatorgenerated
     */
    public String getTestReportNumber() {
        return testReportNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_TEST_REPORT.test_report_number
     *
     * @param testReportNumber the value for PBS_TEST_REPORT.test_report_number
     *
     * @ibatorgenerated
     */
    public void setTestReportNumber(String testReportNumber) {
        this.testReportNumber = testReportNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_TEST_REPORT.test_user_name
     *
     * @return the value of PBS_TEST_REPORT.test_user_name
     *
     * @ibatorgenerated
     */
    public String getTestUserName() {
        return testUserName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_TEST_REPORT.test_user_name
     *
     * @param testUserName the value for PBS_TEST_REPORT.test_user_name
     *
     * @ibatorgenerated
     */
    public void setTestUserName(String testUserName) {
        this.testUserName = testUserName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_TEST_REPORT.test_date
     *
     * @return the value of PBS_TEST_REPORT.test_date
     *
     * @ibatorgenerated
     */
    @JSON(format="yyyy-MM-dd")
    public Date getTestDate() {
        return testDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_TEST_REPORT.test_date
     *
     * @param testDate the value for PBS_TEST_REPORT.test_date
     *
     * @ibatorgenerated
     */
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PBS_TEST_REPORT.test_status
     *
     * @return the value of PBS_TEST_REPORT.test_status
     *
     * @ibatorgenerated
     */
    public String getTestStatus() {
        return testStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PBS_TEST_REPORT.test_status
     *
     * @param testStatus the value for PBS_TEST_REPORT.test_status
     *
     * @ibatorgenerated
     */
    public void setTestStatus(String testStatus) {
        this.testStatus = testStatus;
    }


	public String getPbsTestSampleName() {
		return pbsTestSampleName;
	}


	public void setPbsTestSampleName(String pbsTestSampleName) {
		this.pbsTestSampleName = pbsTestSampleName;
	}


	public String getPbsTestTypeSpecification() {
		return pbsTestTypeSpecification;
	}


	public void setPbsTestTypeSpecification(String pbsTestTypeSpecification) {
		this.pbsTestTypeSpecification = pbsTestTypeSpecification;
	}


	public String getPbsTestTemperature() {
		return pbsTestTemperature;
	}


	public void setPbsTestTemperature(String pbsTestTemperature) {
		this.pbsTestTemperature = pbsTestTemperature;
	}


	public String getPbsTestHumidity() {
		return pbsTestHumidity;
	}


	public void setPbsTestHumidity(String pbsTestHumidity) {
		this.pbsTestHumidity = pbsTestHumidity;
	}


	public String getPbsTestProject() {
		return pbsTestProject;
	}


	public void setPbsTestProject(String pbsTestProject) {
		this.pbsTestProject = pbsTestProject;
	}


	public String getPbsTestStandard() {
		return pbsTestStandard;
	}


	public void setPbsTestStandard(String pbsTestStandard) {
		this.pbsTestStandard = pbsTestStandard;
	}


	public String getPbsTestLocation() {
		return pbsTestLocation;
	}


	public void setPbsTestLocation(String pbsTestLocation) {
		this.pbsTestLocation = pbsTestLocation;
	}


	public String getPbsTestGrade() {
		return pbsTestGrade;
	}


	public void setPbsTestGrade(String pbsTestGrade) {
		this.pbsTestGrade = pbsTestGrade;
	}


	public String getPbsTestConclusion() {
		return pbsTestConclusion;
	}


	public void setPbsTestConclusion(String pbsTestConclusion) {
		this.pbsTestConclusion = pbsTestConclusion;
	}

	@JSON(format="yyyy-MM-dd")
	public Date getPbsTestCompletionTime() {
		return pbsTestCompletionTime;
	}


	public void setPbsTestCompletionTime(Date pbsTestCompletionTime) {
		this.pbsTestCompletionTime = pbsTestCompletionTime;
	}


	public String getPbsTestPbsStatus() {
		return pbsTestPbsStatus;
	}


	public void setPbsTestPbsStatus(String pbsTestPbsStatus) {
		this.pbsTestPbsStatus = pbsTestPbsStatus;
	}


	public String getPbsTestPbsSize() {
		return pbsTestPbsSize;
	}


	public void setPbsTestPbsSize(String pbsTestPbsSize) {
		this.pbsTestPbsSize = pbsTestPbsSize;
	}
    
    
}