package com.tyust.dao.device;

import com.tyust.bean.device.DeviceTestApplyAttach;
import com.tyust.bean.device.DeviceTestApplyAttachExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DeviceTestApplyAttachDAOImpl extends SqlMapClientDaoSupport implements DeviceTestApplyAttachDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public DeviceTestApplyAttachDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public int countByExample(DeviceTestApplyAttachExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("NT_DEVICE_TEST_APPLY_ATTACH.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public int deleteByExample(DeviceTestApplyAttachExample example) {
        int rows = getSqlMapClientTemplate().delete("NT_DEVICE_TEST_APPLY_ATTACH.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(String devAttachId) {
        DeviceTestApplyAttach key = new DeviceTestApplyAttach();
        key.setDevAttachId(devAttachId);
        int rows = getSqlMapClientTemplate().delete("NT_DEVICE_TEST_APPLY_ATTACH.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public void insert(DeviceTestApplyAttach record) {
        getSqlMapClientTemplate().insert("NT_DEVICE_TEST_APPLY_ATTACH.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public void insertSelective(DeviceTestApplyAttach record) {
        getSqlMapClientTemplate().insert("NT_DEVICE_TEST_APPLY_ATTACH.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<DeviceTestApplyAttach> selectByExample(DeviceTestApplyAttachExample example) {
        List<DeviceTestApplyAttach> list = getSqlMapClientTemplate().queryForList("NT_DEVICE_TEST_APPLY_ATTACH.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public DeviceTestApplyAttach selectByPrimaryKey(String devAttachId) {
        DeviceTestApplyAttach key = new DeviceTestApplyAttach();
        key.setDevAttachId(devAttachId);
        DeviceTestApplyAttach record = (DeviceTestApplyAttach) getSqlMapClientTemplate().queryForObject("NT_DEVICE_TEST_APPLY_ATTACH.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(DeviceTestApplyAttach record, DeviceTestApplyAttachExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("NT_DEVICE_TEST_APPLY_ATTACH.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public int updateByExample(DeviceTestApplyAttach record, DeviceTestApplyAttachExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("NT_DEVICE_TEST_APPLY_ATTACH.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(DeviceTestApplyAttach record) {
        int rows = getSqlMapClientTemplate().update("NT_DEVICE_TEST_APPLY_ATTACH.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(DeviceTestApplyAttach record) {
        int rows = getSqlMapClientTemplate().update("NT_DEVICE_TEST_APPLY_ATTACH.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends DeviceTestApplyAttachExample {
        private Object record;

        public UpdateByExampleParms(Object record, DeviceTestApplyAttachExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}