package com.tyust.dao.device;

import com.tyust.bean.device.DeviceTestApplyAttach;
import com.tyust.bean.device.DeviceTestApplyAttachExample;
import java.util.List;

public interface DeviceTestApplyAttachDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    int countByExample(DeviceTestApplyAttachExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    int deleteByExample(DeviceTestApplyAttachExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(String devAttachId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    void insert(DeviceTestApplyAttach record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    void insertSelective(DeviceTestApplyAttach record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    List<DeviceTestApplyAttach> selectByExample(DeviceTestApplyAttachExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    DeviceTestApplyAttach selectByPrimaryKey(String devAttachId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(DeviceTestApplyAttach record, DeviceTestApplyAttachExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    int updateByExample(DeviceTestApplyAttach record, DeviceTestApplyAttachExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(DeviceTestApplyAttach record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NT_DEVICE_TEST_APPLY_ATTACH
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(DeviceTestApplyAttach record);
}