package com.tyust.dao.dic;

import com.tyust.bean.dic.SystemDictionary;
import com.tyust.bean.dic.SystemDictionaryExample;
import com.tyust.dao.dic.SystemDictionaryDAO;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SystemDictionaryDAOImpl extends SqlMapClientDaoSupport implements SystemDictionaryDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DIC_SYSTEM_DICTIONARY
     *
     * @ibatorgenerated
     */
    public SystemDictionaryDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DIC_SYSTEM_DICTIONARY
     *
     * @ibatorgenerated
     */
    public int countByExample(SystemDictionaryExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("DIC_SYSTEM_DICTIONARY.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DIC_SYSTEM_DICTIONARY
     *
     * @ibatorgenerated
     */
    public int deleteByExample(SystemDictionaryExample example) {
        int rows = getSqlMapClientTemplate().delete("DIC_SYSTEM_DICTIONARY.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DIC_SYSTEM_DICTIONARY
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(String dictionaryOptionId) {
        SystemDictionary key = new SystemDictionary();
        key.setDictionaryOptionId(dictionaryOptionId);
        int rows = getSqlMapClientTemplate().delete("DIC_SYSTEM_DICTIONARY.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DIC_SYSTEM_DICTIONARY
     *
     * @ibatorgenerated
     */
    public void insert(SystemDictionary record) {
        getSqlMapClientTemplate().insert("DIC_SYSTEM_DICTIONARY.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DIC_SYSTEM_DICTIONARY
     *
     * @ibatorgenerated
     */
    public void insertSelective(SystemDictionary record) {
        getSqlMapClientTemplate().insert("DIC_SYSTEM_DICTIONARY.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DIC_SYSTEM_DICTIONARY
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<SystemDictionary> selectByExample(SystemDictionaryExample example) {
        List<SystemDictionary> list = getSqlMapClientTemplate().queryForList("DIC_SYSTEM_DICTIONARY.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DIC_SYSTEM_DICTIONARY
     *
     * @ibatorgenerated
     */
    public SystemDictionary selectByPrimaryKey(String dictionaryOptionId) {
        SystemDictionary key = new SystemDictionary();
        key.setDictionaryOptionId(dictionaryOptionId);
        SystemDictionary record = (SystemDictionary) getSqlMapClientTemplate().queryForObject("DIC_SYSTEM_DICTIONARY.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DIC_SYSTEM_DICTIONARY
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(SystemDictionary record, SystemDictionaryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("DIC_SYSTEM_DICTIONARY.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DIC_SYSTEM_DICTIONARY
     *
     * @ibatorgenerated
     */
    public int updateByExample(SystemDictionary record, SystemDictionaryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("DIC_SYSTEM_DICTIONARY.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DIC_SYSTEM_DICTIONARY
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(SystemDictionary record) {
        int rows = getSqlMapClientTemplate().update("DIC_SYSTEM_DICTIONARY.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DIC_SYSTEM_DICTIONARY
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(SystemDictionary record) {
        int rows = getSqlMapClientTemplate().update("DIC_SYSTEM_DICTIONARY.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table DIC_SYSTEM_DICTIONARY
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends SystemDictionaryExample {
        private Object record;

        public UpdateByExampleParms(Object record, SystemDictionaryExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    /**
	 * 根据上级id查字典表下级的list
	 * 如：002----》002001001
	 */
    public List<SystemDictionary> selectNextDicListByNewsId(Map map){
        List<SystemDictionary> list = getSqlMapClientTemplate().queryForList("DIC_SYSTEM_DICTIONARY.ibatorgenerated_selectNextDicListByNewsId", map);
        return list;
    }
}