package com.tyust.bean.en;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.tyust.common.IbatorGenExamplePageHelper;

public class EnApplyInfoExample extends IbatorGenExamplePageHelper{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    public EnApplyInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    protected EnApplyInfoExample(EnApplyInfoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andEnvironmentApplyIdIsNull() {
            addCriterion("ENVIRONMENT_APPLY_ID is null");
            return this;
        }

        public Criteria andEnvironmentApplyIdIsNotNull() {
            addCriterion("ENVIRONMENT_APPLY_ID is not null");
            return this;
        }

        public Criteria andEnvironmentApplyIdEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID =", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdNotEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID <>", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdGreaterThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID >", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdGreaterThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID >=", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdLessThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID <", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdLessThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID <=", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID like", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdNotLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID not like", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_ID in", values, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdNotIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_ID not in", values, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_ID between", value1, value2, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdNotBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_ID not between", value1, value2, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyUnitIdIsNull() {
            addCriterion("ENVIRONMENT_APPLY_UNIT_ID is null");
            return this;
        }

        public Criteria andEnvironmentApplyUnitIdIsNotNull() {
            addCriterion("ENVIRONMENT_APPLY_UNIT_ID is not null");
            return this;
        }

        public Criteria andEnvironmentApplyUnitIdEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_UNIT_ID =", value, "environmentApplyUnitId");
            return this;
        }

        public Criteria andEnvironmentApplyUnitIdNotEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_UNIT_ID <>", value, "environmentApplyUnitId");
            return this;
        }

        public Criteria andEnvironmentApplyUnitIdGreaterThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_UNIT_ID >", value, "environmentApplyUnitId");
            return this;
        }

        public Criteria andEnvironmentApplyUnitIdGreaterThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_UNIT_ID >=", value, "environmentApplyUnitId");
            return this;
        }

        public Criteria andEnvironmentApplyUnitIdLessThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_UNIT_ID <", value, "environmentApplyUnitId");
            return this;
        }

        public Criteria andEnvironmentApplyUnitIdLessThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_UNIT_ID <=", value, "environmentApplyUnitId");
            return this;
        }

        public Criteria andEnvironmentApplyUnitIdLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_UNIT_ID like", value, "environmentApplyUnitId");
            return this;
        }

        public Criteria andEnvironmentApplyUnitIdNotLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_UNIT_ID not like", value, "environmentApplyUnitId");
            return this;
        }

        public Criteria andEnvironmentApplyUnitIdIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_UNIT_ID in", values, "environmentApplyUnitId");
            return this;
        }

        public Criteria andEnvironmentApplyUnitIdNotIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_UNIT_ID not in", values, "environmentApplyUnitId");
            return this;
        }

        public Criteria andEnvironmentApplyUnitIdBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_UNIT_ID between", value1, value2, "environmentApplyUnitId");
            return this;
        }

        public Criteria andEnvironmentApplyUnitIdNotBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_UNIT_ID not between", value1, value2, "environmentApplyUnitId");
            return this;
        }

        public Criteria andEnvironmentApplyUserIdIsNull() {
            addCriterion("ENVIRONMENT_APPLY_USER_ID is null");
            return this;
        }

        public Criteria andEnvironmentApplyUserIdIsNotNull() {
            addCriterion("ENVIRONMENT_APPLY_USER_ID is not null");
            return this;
        }

        public Criteria andEnvironmentApplyUserIdEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_USER_ID =", value, "environmentApplyUserId");
            return this;
        }

        public Criteria andEnvironmentApplyUserIdNotEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_USER_ID <>", value, "environmentApplyUserId");
            return this;
        }

        public Criteria andEnvironmentApplyUserIdGreaterThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_USER_ID >", value, "environmentApplyUserId");
            return this;
        }

        public Criteria andEnvironmentApplyUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_USER_ID >=", value, "environmentApplyUserId");
            return this;
        }

        public Criteria andEnvironmentApplyUserIdLessThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_USER_ID <", value, "environmentApplyUserId");
            return this;
        }

        public Criteria andEnvironmentApplyUserIdLessThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_USER_ID <=", value, "environmentApplyUserId");
            return this;
        }

        public Criteria andEnvironmentApplyUserIdLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_USER_ID like", value, "environmentApplyUserId");
            return this;
        }

        public Criteria andEnvironmentApplyUserIdNotLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_USER_ID not like", value, "environmentApplyUserId");
            return this;
        }

        public Criteria andEnvironmentApplyUserIdIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_USER_ID in", values, "environmentApplyUserId");
            return this;
        }

        public Criteria andEnvironmentApplyUserIdNotIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_USER_ID not in", values, "environmentApplyUserId");
            return this;
        }

        public Criteria andEnvironmentApplyUserIdBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_USER_ID between", value1, value2, "environmentApplyUserId");
            return this;
        }

        public Criteria andEnvironmentApplyUserIdNotBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_USER_ID not between", value1, value2, "environmentApplyUserId");
            return this;
        }

        public Criteria andEnvironmentApplyTelIsNull() {
            addCriterion("ENVIRONMENT_APPLY_TEL is null");
            return this;
        }

        public Criteria andEnvironmentApplyTelIsNotNull() {
            addCriterion("ENVIRONMENT_APPLY_TEL is not null");
            return this;
        }

        public Criteria andEnvironmentApplyTelEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_TEL =", value, "environmentApplyTel");
            return this;
        }

        public Criteria andEnvironmentApplyTelNotEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_TEL <>", value, "environmentApplyTel");
            return this;
        }

        public Criteria andEnvironmentApplyTelGreaterThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_TEL >", value, "environmentApplyTel");
            return this;
        }

        public Criteria andEnvironmentApplyTelGreaterThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_TEL >=", value, "environmentApplyTel");
            return this;
        }

        public Criteria andEnvironmentApplyTelLessThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_TEL <", value, "environmentApplyTel");
            return this;
        }

        public Criteria andEnvironmentApplyTelLessThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_TEL <=", value, "environmentApplyTel");
            return this;
        }

        public Criteria andEnvironmentApplyTelLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_TEL like", value, "environmentApplyTel");
            return this;
        }

        public Criteria andEnvironmentApplyTelNotLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_TEL not like", value, "environmentApplyTel");
            return this;
        }

        public Criteria andEnvironmentApplyTelIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_TEL in", values, "environmentApplyTel");
            return this;
        }

        public Criteria andEnvironmentApplyTelNotIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_TEL not in", values, "environmentApplyTel");
            return this;
        }

        public Criteria andEnvironmentApplyTelBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_TEL between", value1, value2, "environmentApplyTel");
            return this;
        }

        public Criteria andEnvironmentApplyTelNotBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_TEL not between", value1, value2, "environmentApplyTel");
            return this;
        }

        public Criteria andEnvironmentApplyStatusIsNull() {
            addCriterion("ENVIRONMENT_APPLY_STATUS is null");
            return this;
        }

        public Criteria andEnvironmentApplyStatusIsNotNull() {
            addCriterion("ENVIRONMENT_APPLY_STATUS is not null");
            return this;
        }

        public Criteria andEnvironmentApplyStatusEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_STATUS =", value, "environmentApplyStatus");
            return this;
        }

        public Criteria andEnvironmentApplyStatusNotEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_STATUS <>", value, "environmentApplyStatus");
            return this;
        }

        public Criteria andEnvironmentApplyStatusGreaterThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_STATUS >", value, "environmentApplyStatus");
            return this;
        }

        public Criteria andEnvironmentApplyStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_STATUS >=", value, "environmentApplyStatus");
            return this;
        }

        public Criteria andEnvironmentApplyStatusLessThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_STATUS <", value, "environmentApplyStatus");
            return this;
        }

        public Criteria andEnvironmentApplyStatusLessThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_STATUS <=", value, "environmentApplyStatus");
            return this;
        }

        public Criteria andEnvironmentApplyStatusLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_STATUS like", value, "environmentApplyStatus");
            return this;
        }

        public Criteria andEnvironmentApplyStatusNotLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_STATUS not like", value, "environmentApplyStatus");
            return this;
        }

        public Criteria andEnvironmentApplyStatusIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_STATUS in", values, "environmentApplyStatus");
            return this;
        }

        public Criteria andEnvironmentApplyStatusNotIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_STATUS not in", values, "environmentApplyStatus");
            return this;
        }

        public Criteria andEnvironmentApplyStatusBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_STATUS between", value1, value2, "environmentApplyStatus");
            return this;
        }

        public Criteria andEnvironmentApplyStatusNotBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_STATUS not between", value1, value2, "environmentApplyStatus");
            return this;
        }

        public Criteria andEnvironmentApplyDateIsNull() {
            addCriterion("ENVIRONMENT_APPLY_DATE is null");
            return this;
        }

        public Criteria andEnvironmentApplyDateIsNotNull() {
            addCriterion("ENVIRONMENT_APPLY_DATE is not null");
            return this;
        }

        public Criteria andEnvironmentApplyDateEqualTo(Date value) {
            addCriterion("ENVIRONMENT_APPLY_DATE =", value, "environmentApplyDate");
            return this;
        }

        public Criteria andEnvironmentApplyDateNotEqualTo(Date value) {
            addCriterion("ENVIRONMENT_APPLY_DATE <>", value, "environmentApplyDate");
            return this;
        }

        public Criteria andEnvironmentApplyDateGreaterThan(Date value) {
            addCriterion("ENVIRONMENT_APPLY_DATE >", value, "environmentApplyDate");
            return this;
        }

        public Criteria andEnvironmentApplyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("ENVIRONMENT_APPLY_DATE >=", value, "environmentApplyDate");
            return this;
        }

        public Criteria andEnvironmentApplyDateLessThan(Date value) {
            addCriterion("ENVIRONMENT_APPLY_DATE <", value, "environmentApplyDate");
            return this;
        }

        public Criteria andEnvironmentApplyDateLessThanOrEqualTo(Date value) {
            addCriterion("ENVIRONMENT_APPLY_DATE <=", value, "environmentApplyDate");
            return this;
        }

        public Criteria andEnvironmentApplyDateIn(List<Date> values) {
            addCriterion("ENVIRONMENT_APPLY_DATE in", values, "environmentApplyDate");
            return this;
        }

        public Criteria andEnvironmentApplyDateNotIn(List<Date> values) {
            addCriterion("ENVIRONMENT_APPLY_DATE not in", values, "environmentApplyDate");
            return this;
        }

        public Criteria andEnvironmentApplyDateBetween(Date value1, Date value2) {
            addCriterion("ENVIRONMENT_APPLY_DATE between", value1, value2, "environmentApplyDate");
            return this;
        }

        public Criteria andEnvironmentApplyDateNotBetween(Date value1, Date value2) {
            addCriterion("ENVIRONMENT_APPLY_DATE not between", value1, value2, "environmentApplyDate");
            return this;
        }

        public Criteria andEnvironmentApplyOpinionIsNull() {
            addCriterion("ENVIRONMENT_APPLY_OPINION is null");
            return this;
        }

        public Criteria andEnvironmentApplyOpinionIsNotNull() {
            addCriterion("ENVIRONMENT_APPLY_OPINION is not null");
            return this;
        }

        public Criteria andEnvironmentApplyOpinionEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_OPINION =", value, "environmentApplyOpinion");
            return this;
        }

        public Criteria andEnvironmentApplyOpinionNotEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_OPINION <>", value, "environmentApplyOpinion");
            return this;
        }

        public Criteria andEnvironmentApplyOpinionGreaterThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_OPINION >", value, "environmentApplyOpinion");
            return this;
        }

        public Criteria andEnvironmentApplyOpinionGreaterThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_OPINION >=", value, "environmentApplyOpinion");
            return this;
        }

        public Criteria andEnvironmentApplyOpinionLessThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_OPINION <", value, "environmentApplyOpinion");
            return this;
        }

        public Criteria andEnvironmentApplyOpinionLessThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_OPINION <=", value, "environmentApplyOpinion");
            return this;
        }

        public Criteria andEnvironmentApplyOpinionLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_OPINION like", value, "environmentApplyOpinion");
            return this;
        }

        public Criteria andEnvironmentApplyOpinionNotLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_OPINION not like", value, "environmentApplyOpinion");
            return this;
        }

        public Criteria andEnvironmentApplyOpinionIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_OPINION in", values, "environmentApplyOpinion");
            return this;
        }

        public Criteria andEnvironmentApplyOpinionNotIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_OPINION not in", values, "environmentApplyOpinion");
            return this;
        }

        public Criteria andEnvironmentApplyOpinionBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_OPINION between", value1, value2, "environmentApplyOpinion");
            return this;
        }

        public Criteria andEnvironmentApplyOpinionNotBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_OPINION not between", value1, value2, "environmentApplyOpinion");
            return this;
        }

        public Criteria andEnvironmentApplySamplyIsNull() {
            addCriterion("ENVIRONMENT_APPLY_SAMPLY is null");
            return this;
        }

        public Criteria andEnvironmentApplySamplyIsNotNull() {
            addCriterion("ENVIRONMENT_APPLY_SAMPLY is not null");
            return this;
        }

        public Criteria andEnvironmentApplySamplyEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_SAMPLY =", value, "environmentApplySamply");
            return this;
        }

        public Criteria andEnvironmentApplySamplyNotEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_SAMPLY <>", value, "environmentApplySamply");
            return this;
        }

        public Criteria andEnvironmentApplySamplyGreaterThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_SAMPLY >", value, "environmentApplySamply");
            return this;
        }

        public Criteria andEnvironmentApplySamplyGreaterThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_SAMPLY >=", value, "environmentApplySamply");
            return this;
        }

        public Criteria andEnvironmentApplySamplyLessThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_SAMPLY <", value, "environmentApplySamply");
            return this;
        }

        public Criteria andEnvironmentApplySamplyLessThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_SAMPLY <=", value, "environmentApplySamply");
            return this;
        }

        public Criteria andEnvironmentApplySamplyLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_SAMPLY like", value, "environmentApplySamply");
            return this;
        }

        public Criteria andEnvironmentApplySamplyNotLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_SAMPLY not like", value, "environmentApplySamply");
            return this;
        }

        public Criteria andEnvironmentApplySamplyIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_SAMPLY in", values, "environmentApplySamply");
            return this;
        }

        public Criteria andEnvironmentApplySamplyNotIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_SAMPLY not in", values, "environmentApplySamply");
            return this;
        }

        public Criteria andEnvironmentApplySamplyBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_SAMPLY between", value1, value2, "environmentApplySamply");
            return this;
        }

        public Criteria andEnvironmentApplySamplyNotBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_SAMPLY not between", value1, value2, "environmentApplySamply");
            return this;
        }

        public Criteria andEnvironmentApplyProductionIsNull() {
            addCriterion("ENVIRONMENT_APPLY_PRODUCTION is null");
            return this;
        }

        public Criteria andEnvironmentApplyProductionIsNotNull() {
            addCriterion("ENVIRONMENT_APPLY_PRODUCTION is not null");
            return this;
        }

        public Criteria andEnvironmentApplyProductionEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_PRODUCTION =", value, "environmentApplyProduction");
            return this;
        }

        public Criteria andEnvironmentApplyProductionNotEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_PRODUCTION <>", value, "environmentApplyProduction");
            return this;
        }

        public Criteria andEnvironmentApplyProductionGreaterThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_PRODUCTION >", value, "environmentApplyProduction");
            return this;
        }

        public Criteria andEnvironmentApplyProductionGreaterThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_PRODUCTION >=", value, "environmentApplyProduction");
            return this;
        }

        public Criteria andEnvironmentApplyProductionLessThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_PRODUCTION <", value, "environmentApplyProduction");
            return this;
        }

        public Criteria andEnvironmentApplyProductionLessThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_PRODUCTION <=", value, "environmentApplyProduction");
            return this;
        }

        public Criteria andEnvironmentApplyProductionLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_PRODUCTION like", value, "environmentApplyProduction");
            return this;
        }

        public Criteria andEnvironmentApplyProductionNotLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_PRODUCTION not like", value, "environmentApplyProduction");
            return this;
        }

        public Criteria andEnvironmentApplyProductionIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_PRODUCTION in", values, "environmentApplyProduction");
            return this;
        }

        public Criteria andEnvironmentApplyProductionNotIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_PRODUCTION not in", values, "environmentApplyProduction");
            return this;
        }

        public Criteria andEnvironmentApplyProductionBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_PRODUCTION between", value1, value2, "environmentApplyProduction");
            return this;
        }

        public Criteria andEnvironmentApplyProductionNotBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_PRODUCTION not between", value1, value2, "environmentApplyProduction");
            return this;
        }

        public Criteria andEnvironmentApplyUserNameIsNull() {
            addCriterion("ENVIRONMENT_APPLY_USER_NAME is null");
            return this;
        }

        public Criteria andEnvironmentApplyUserNameIsNotNull() {
            addCriterion("ENVIRONMENT_APPLY_USER_NAME is not null");
            return this;
        }

        public Criteria andEnvironmentApplyUserNameEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_USER_NAME =", value, "environmentApplyUserName");
            return this;
        }

        public Criteria andEnvironmentApplyUserNameNotEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_USER_NAME <>", value, "environmentApplyUserName");
            return this;
        }

        public Criteria andEnvironmentApplyUserNameGreaterThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_USER_NAME >", value, "environmentApplyUserName");
            return this;
        }

        public Criteria andEnvironmentApplyUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_USER_NAME >=", value, "environmentApplyUserName");
            return this;
        }

        public Criteria andEnvironmentApplyUserNameLessThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_USER_NAME <", value, "environmentApplyUserName");
            return this;
        }

        public Criteria andEnvironmentApplyUserNameLessThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_USER_NAME <=", value, "environmentApplyUserName");
            return this;
        }

        public Criteria andEnvironmentApplyUserNameLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_USER_NAME like", value, "environmentApplyUserName");
            return this;
        }

        public Criteria andEnvironmentApplyUserNameNotLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_USER_NAME not like", value, "environmentApplyUserName");
            return this;
        }

        public Criteria andEnvironmentApplyUserNameIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_USER_NAME in", values, "environmentApplyUserName");
            return this;
        }

        public Criteria andEnvironmentApplyUserNameNotIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_USER_NAME not in", values, "environmentApplyUserName");
            return this;
        }

        public Criteria andEnvironmentApplyUserNameBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_USER_NAME between", value1, value2, "environmentApplyUserName");
            return this;
        }

        public Criteria andEnvironmentApplyUserNameNotBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_USER_NAME not between", value1, value2, "environmentApplyUserName");
            return this;
        }
    }
}