package com.tyust.bean.en;

import java.util.Date;

public class EnAttach {

	private String environmentAttachId;

	private String environmentApplyId;

	private String environmentAttachUrl;

	private String environmentAttachName;

	private String environmentAttachType;

	private Date environmentAttachDate;

	public String getEnvironmentAttachId() {
		return environmentAttachId;
	}

	public void setEnvironmentAttachId(String environmentAttachId) {
		this.environmentAttachId = environmentAttachId;
	}

	public String getEnvironmentApplyId() {
		return environmentApplyId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column ENVIRONMENT_ATTACH.ENVIRONMENT_APPLY_ID
	 *
	 * @param environmentApplyId
	 *            the value for ENVIRONMENT_ATTACH.ENVIRONMENT_APPLY_ID
	 *
	 * @ibatorgenerated
	 */
	public void setEnvironmentApplyId(String environmentApplyId) {
		this.environmentApplyId = environmentApplyId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column
	 * ENVIRONMENT_ATTACH.ENVIRONMENT_ATTACH_URL
	 *
	 * @return the value of ENVIRONMENT_ATTACH.ENVIRONMENT_ATTACH_URL
	 *
	 * @ibatorgenerated
	 */
	public String getEnvironmentAttachUrl() {
		return environmentAttachUrl;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column ENVIRONMENT_ATTACH.ENVIRONMENT_ATTACH_URL
	 *
	 * @param environmentAttachUrl
	 *            the value for ENVIRONMENT_ATTACH.ENVIRONMENT_ATTACH_URL
	 *
	 * @ibatorgenerated
	 */
	public void setEnvironmentAttachUrl(String environmentAttachUrl) {
		this.environmentAttachUrl = environmentAttachUrl;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column
	 * ENVIRONMENT_ATTACH.ENVIRONMENT_ATTACH_NAME
	 *
	 * @return the value of ENVIRONMENT_ATTACH.ENVIRONMENT_ATTACH_NAME
	 *
	 * @ibatorgenerated
	 */
	public String getEnvironmentAttachName() {
		return environmentAttachName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column ENVIRONMENT_ATTACH.ENVIRONMENT_ATTACH_NAME
	 *
	 * @param environmentAttachName
	 *            the value for ENVIRONMENT_ATTACH.ENVIRONMENT_ATTACH_NAME
	 *
	 * @ibatorgenerated
	 */
	public void setEnvironmentAttachName(String environmentAttachName) {
		this.environmentAttachName = environmentAttachName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column
	 * ENVIRONMENT_ATTACH.ENVIRONMENT_ATTACH_TYPE
	 *
	 * @return the value of ENVIRONMENT_ATTACH.ENVIRONMENT_ATTACH_TYPE
	 *
	 * @ibatorgenerated
	 */
	public String getEnvironmentAttachType() {
		return environmentAttachType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column ENVIRONMENT_ATTACH.ENVIRONMENT_ATTACH_TYPE
	 *
	 * @param environmentAttachType
	 *            the value for ENVIRONMENT_ATTACH.ENVIRONMENT_ATTACH_TYPE
	 *
	 * @ibatorgenerated
	 */
	public void setEnvironmentAttachType(String environmentAttachType) {
		this.environmentAttachType = environmentAttachType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column
	 * ENVIRONMENT_ATTACH.ENVIRONMENT_ATTACH_DATE
	 *
	 * @return the value of ENVIRONMENT_ATTACH.ENVIRONMENT_ATTACH_DATE
	 *
	 * @ibatorgenerated
	 */
	public Date getEnvironmentAttachDate() {
		return environmentAttachDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column ENVIRONMENT_ATTACH.ENVIRONMENT_ATTACH_DATE
	 *
	 * @param environmentAttachDate
	 *            the value for ENVIRONMENT_ATTACH.ENVIRONMENT_ATTACH_DATE
	 *
	 * @ibatorgenerated
	 */
	public void setEnvironmentAttachDate(Date environmentAttachDate) {
		this.environmentAttachDate = environmentAttachDate;
	}
}