package com.tyust.bean.en;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EnAttachExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public EnAttachExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    protected EnAttachExample(EnAttachExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andEnvironmentAttachIdIsNull() {
            addCriterion("ENVIRONMENT_ATTACH_ID is null");
            return this;
        }

        public Criteria andEnvironmentAttachIdIsNotNull() {
            addCriterion("ENVIRONMENT_ATTACH_ID is not null");
            return this;
        }

        public Criteria andEnvironmentAttachIdEqualTo(String value) {
            addCriterion("ENVIRONMENT_ATTACH_ID =", value, "environmentAttachId");
            return this;
        }

        public Criteria andEnvironmentAttachIdNotEqualTo(String value) {
            addCriterion("ENVIRONMENT_ATTACH_ID <>", value, "environmentAttachId");
            return this;
        }

        public Criteria andEnvironmentAttachIdGreaterThan(String value) {
            addCriterion("ENVIRONMENT_ATTACH_ID >", value, "environmentAttachId");
            return this;
        }

        public Criteria andEnvironmentAttachIdGreaterThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_ATTACH_ID >=", value, "environmentAttachId");
            return this;
        }

        public Criteria andEnvironmentAttachIdLessThan(String value) {
            addCriterion("ENVIRONMENT_ATTACH_ID <", value, "environmentAttachId");
            return this;
        }

        public Criteria andEnvironmentAttachIdLessThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_ATTACH_ID <=", value, "environmentAttachId");
            return this;
        }

        public Criteria andEnvironmentAttachIdLike(String value) {
            addCriterion("ENVIRONMENT_ATTACH_ID like", value, "environmentAttachId");
            return this;
        }

        public Criteria andEnvironmentAttachIdNotLike(String value) {
            addCriterion("ENVIRONMENT_ATTACH_ID not like", value, "environmentAttachId");
            return this;
        }

        public Criteria andEnvironmentAttachIdIn(List<String> values) {
            addCriterion("ENVIRONMENT_ATTACH_ID in", values, "environmentAttachId");
            return this;
        }

        public Criteria andEnvironmentAttachIdNotIn(List<String> values) {
            addCriterion("ENVIRONMENT_ATTACH_ID not in", values, "environmentAttachId");
            return this;
        }

        public Criteria andEnvironmentAttachIdBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_ATTACH_ID between", value1, value2, "environmentAttachId");
            return this;
        }

        public Criteria andEnvironmentAttachIdNotBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_ATTACH_ID not between", value1, value2, "environmentAttachId");
            return this;
        }

        public Criteria andEnvironmentApplyIdIsNull() {
            addCriterion("ENVIRONMENT_APPLY_ID is null");
            return this;
        }

        public Criteria andEnvironmentApplyIdIsNotNull() {
            addCriterion("ENVIRONMENT_APPLY_ID is not null");
            return this;
        }

        public Criteria andEnvironmentApplyIdEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID =", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdNotEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID <>", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdGreaterThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID >", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdGreaterThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID >=", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdLessThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID <", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdLessThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID <=", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID like", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdNotLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID not like", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_ID in", values, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdNotIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_ID not in", values, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_ID between", value1, value2, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdNotBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_ID not between", value1, value2, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentAttachUrlIsNull() {
            addCriterion("ENVIRONMENT_ATTACH_URL is null");
            return this;
        }

        public Criteria andEnvironmentAttachUrlIsNotNull() {
            addCriterion("ENVIRONMENT_ATTACH_URL is not null");
            return this;
        }

        public Criteria andEnvironmentAttachUrlEqualTo(String value) {
            addCriterion("ENVIRONMENT_ATTACH_URL =", value, "environmentAttachUrl");
            return this;
        }

        public Criteria andEnvironmentAttachUrlNotEqualTo(String value) {
            addCriterion("ENVIRONMENT_ATTACH_URL <>", value, "environmentAttachUrl");
            return this;
        }

        public Criteria andEnvironmentAttachUrlGreaterThan(String value) {
            addCriterion("ENVIRONMENT_ATTACH_URL >", value, "environmentAttachUrl");
            return this;
        }

        public Criteria andEnvironmentAttachUrlGreaterThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_ATTACH_URL >=", value, "environmentAttachUrl");
            return this;
        }

        public Criteria andEnvironmentAttachUrlLessThan(String value) {
            addCriterion("ENVIRONMENT_ATTACH_URL <", value, "environmentAttachUrl");
            return this;
        }

        public Criteria andEnvironmentAttachUrlLessThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_ATTACH_URL <=", value, "environmentAttachUrl");
            return this;
        }

        public Criteria andEnvironmentAttachUrlLike(String value) {
            addCriterion("ENVIRONMENT_ATTACH_URL like", value, "environmentAttachUrl");
            return this;
        }

        public Criteria andEnvironmentAttachUrlNotLike(String value) {
            addCriterion("ENVIRONMENT_ATTACH_URL not like", value, "environmentAttachUrl");
            return this;
        }

        public Criteria andEnvironmentAttachUrlIn(List<String> values) {
            addCriterion("ENVIRONMENT_ATTACH_URL in", values, "environmentAttachUrl");
            return this;
        }

        public Criteria andEnvironmentAttachUrlNotIn(List<String> values) {
            addCriterion("ENVIRONMENT_ATTACH_URL not in", values, "environmentAttachUrl");
            return this;
        }

        public Criteria andEnvironmentAttachUrlBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_ATTACH_URL between", value1, value2, "environmentAttachUrl");
            return this;
        }

        public Criteria andEnvironmentAttachUrlNotBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_ATTACH_URL not between", value1, value2, "environmentAttachUrl");
            return this;
        }

        public Criteria andEnvironmentAttachNameIsNull() {
            addCriterion("ENVIRONMENT_ATTACH_NAME is null");
            return this;
        }

        public Criteria andEnvironmentAttachNameIsNotNull() {
            addCriterion("ENVIRONMENT_ATTACH_NAME is not null");
            return this;
        }

        public Criteria andEnvironmentAttachNameEqualTo(String value) {
            addCriterion("ENVIRONMENT_ATTACH_NAME =", value, "environmentAttachName");
            return this;
        }

        public Criteria andEnvironmentAttachNameNotEqualTo(String value) {
            addCriterion("ENVIRONMENT_ATTACH_NAME <>", value, "environmentAttachName");
            return this;
        }

        public Criteria andEnvironmentAttachNameGreaterThan(String value) {
            addCriterion("ENVIRONMENT_ATTACH_NAME >", value, "environmentAttachName");
            return this;
        }

        public Criteria andEnvironmentAttachNameGreaterThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_ATTACH_NAME >=", value, "environmentAttachName");
            return this;
        }

        public Criteria andEnvironmentAttachNameLessThan(String value) {
            addCriterion("ENVIRONMENT_ATTACH_NAME <", value, "environmentAttachName");
            return this;
        }

        public Criteria andEnvironmentAttachNameLessThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_ATTACH_NAME <=", value, "environmentAttachName");
            return this;
        }

        public Criteria andEnvironmentAttachNameLike(String value) {
            addCriterion("ENVIRONMENT_ATTACH_NAME like", value, "environmentAttachName");
            return this;
        }

        public Criteria andEnvironmentAttachNameNotLike(String value) {
            addCriterion("ENVIRONMENT_ATTACH_NAME not like", value, "environmentAttachName");
            return this;
        }

        public Criteria andEnvironmentAttachNameIn(List<String> values) {
            addCriterion("ENVIRONMENT_ATTACH_NAME in", values, "environmentAttachName");
            return this;
        }

        public Criteria andEnvironmentAttachNameNotIn(List<String> values) {
            addCriterion("ENVIRONMENT_ATTACH_NAME not in", values, "environmentAttachName");
            return this;
        }

        public Criteria andEnvironmentAttachNameBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_ATTACH_NAME between", value1, value2, "environmentAttachName");
            return this;
        }

        public Criteria andEnvironmentAttachNameNotBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_ATTACH_NAME not between", value1, value2, "environmentAttachName");
            return this;
        }

        public Criteria andEnvironmentAttachTypeIsNull() {
            addCriterion("ENVIRONMENT_ATTACH_TYPE is null");
            return this;
        }

        public Criteria andEnvironmentAttachTypeIsNotNull() {
            addCriterion("ENVIRONMENT_ATTACH_TYPE is not null");
            return this;
        }

        public Criteria andEnvironmentAttachTypeEqualTo(String value) {
            addCriterion("ENVIRONMENT_ATTACH_TYPE =", value, "environmentAttachType");
            return this;
        }

        public Criteria andEnvironmentAttachTypeNotEqualTo(String value) {
            addCriterion("ENVIRONMENT_ATTACH_TYPE <>", value, "environmentAttachType");
            return this;
        }

        public Criteria andEnvironmentAttachTypeGreaterThan(String value) {
            addCriterion("ENVIRONMENT_ATTACH_TYPE >", value, "environmentAttachType");
            return this;
        }

        public Criteria andEnvironmentAttachTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_ATTACH_TYPE >=", value, "environmentAttachType");
            return this;
        }

        public Criteria andEnvironmentAttachTypeLessThan(String value) {
            addCriterion("ENVIRONMENT_ATTACH_TYPE <", value, "environmentAttachType");
            return this;
        }

        public Criteria andEnvironmentAttachTypeLessThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_ATTACH_TYPE <=", value, "environmentAttachType");
            return this;
        }

        public Criteria andEnvironmentAttachTypeLike(String value) {
            addCriterion("ENVIRONMENT_ATTACH_TYPE like", value, "environmentAttachType");
            return this;
        }

        public Criteria andEnvironmentAttachTypeNotLike(String value) {
            addCriterion("ENVIRONMENT_ATTACH_TYPE not like", value, "environmentAttachType");
            return this;
        }

        public Criteria andEnvironmentAttachTypeIn(List<String> values) {
            addCriterion("ENVIRONMENT_ATTACH_TYPE in", values, "environmentAttachType");
            return this;
        }

        public Criteria andEnvironmentAttachTypeNotIn(List<String> values) {
            addCriterion("ENVIRONMENT_ATTACH_TYPE not in", values, "environmentAttachType");
            return this;
        }

        public Criteria andEnvironmentAttachTypeBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_ATTACH_TYPE between", value1, value2, "environmentAttachType");
            return this;
        }

        public Criteria andEnvironmentAttachTypeNotBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_ATTACH_TYPE not between", value1, value2, "environmentAttachType");
            return this;
        }

        public Criteria andEnvironmentAttachDateIsNull() {
            addCriterion("ENVIRONMENT_ATTACH_DATE is null");
            return this;
        }

        public Criteria andEnvironmentAttachDateIsNotNull() {
            addCriterion("ENVIRONMENT_ATTACH_DATE is not null");
            return this;
        }

        public Criteria andEnvironmentAttachDateEqualTo(Date value) {
            addCriterion("ENVIRONMENT_ATTACH_DATE =", value, "environmentAttachDate");
            return this;
        }

        public Criteria andEnvironmentAttachDateNotEqualTo(Date value) {
            addCriterion("ENVIRONMENT_ATTACH_DATE <>", value, "environmentAttachDate");
            return this;
        }

        public Criteria andEnvironmentAttachDateGreaterThan(Date value) {
            addCriterion("ENVIRONMENT_ATTACH_DATE >", value, "environmentAttachDate");
            return this;
        }

        public Criteria andEnvironmentAttachDateGreaterThanOrEqualTo(Date value) {
            addCriterion("ENVIRONMENT_ATTACH_DATE >=", value, "environmentAttachDate");
            return this;
        }

        public Criteria andEnvironmentAttachDateLessThan(Date value) {
            addCriterion("ENVIRONMENT_ATTACH_DATE <", value, "environmentAttachDate");
            return this;
        }

        public Criteria andEnvironmentAttachDateLessThanOrEqualTo(Date value) {
            addCriterion("ENVIRONMENT_ATTACH_DATE <=", value, "environmentAttachDate");
            return this;
        }

        public Criteria andEnvironmentAttachDateIn(List<Date> values) {
            addCriterion("ENVIRONMENT_ATTACH_DATE in", values, "environmentAttachDate");
            return this;
        }

        public Criteria andEnvironmentAttachDateNotIn(List<Date> values) {
            addCriterion("ENVIRONMENT_ATTACH_DATE not in", values, "environmentAttachDate");
            return this;
        }

        public Criteria andEnvironmentAttachDateBetween(Date value1, Date value2) {
            addCriterion("ENVIRONMENT_ATTACH_DATE between", value1, value2, "environmentAttachDate");
            return this;
        }

        public Criteria andEnvironmentAttachDateNotBetween(Date value1, Date value2) {
            addCriterion("ENVIRONMENT_ATTACH_DATE not between", value1, value2, "environmentAttachDate");
            return this;
        }
    }
}