package com.tyust.bean.en;

import java.util.Date;

public class EnPic {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EN_PIC.EN_PIC_ID
     *
     * @ibatorgenerated
     */
    private String enPicId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EN_PIC.EN_APPLY_ID
     *
     * @ibatorgenerated
     */
    private String enApplyId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EN_PIC.EN_PIC_URL
     *
     * @ibatorgenerated
     */
    private String enPicUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EN_PIC.EN_PIC_NAME
     *
     * @ibatorgenerated
     */
    private String enPicName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EN_PIC.EN_PIC_TYPE
     *
     * @ibatorgenerated
     */
    private String enPicType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EN_PIC.EN_PIC_DATE
     *
     * @ibatorgenerated
     */
    private Date enPicDate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EN_PIC.EN_PIC_ID
     *
     * @return the value of EN_PIC.EN_PIC_ID
     *
     * @ibatorgenerated
     */
    public String getEnPicId() {
        return enPicId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EN_PIC.EN_PIC_ID
     *
     * @param enPicId the value for EN_PIC.EN_PIC_ID
     *
     * @ibatorgenerated
     */
    public void setEnPicId(String enPicId) {
        this.enPicId = enPicId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EN_PIC.EN_APPLY_ID
     *
     * @return the value of EN_PIC.EN_APPLY_ID
     *
     * @ibatorgenerated
     */
    public String getEnApplyId() {
        return enApplyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EN_PIC.EN_APPLY_ID
     *
     * @param enApplyId the value for EN_PIC.EN_APPLY_ID
     *
     * @ibatorgenerated
     */
    public void setEnApplyId(String enApplyId) {
        this.enApplyId = enApplyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EN_PIC.EN_PIC_URL
     *
     * @return the value of EN_PIC.EN_PIC_URL
     *
     * @ibatorgenerated
     */
    public String getEnPicUrl() {
        return enPicUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EN_PIC.EN_PIC_URL
     *
     * @param enPicUrl the value for EN_PIC.EN_PIC_URL
     *
     * @ibatorgenerated
     */
    public void setEnPicUrl(String enPicUrl) {
        this.enPicUrl = enPicUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EN_PIC.EN_PIC_NAME
     *
     * @return the value of EN_PIC.EN_PIC_NAME
     *
     * @ibatorgenerated
     */
    public String getEnPicName() {
        return enPicName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EN_PIC.EN_PIC_NAME
     *
     * @param enPicName the value for EN_PIC.EN_PIC_NAME
     *
     * @ibatorgenerated
     */
    public void setEnPicName(String enPicName) {
        this.enPicName = enPicName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EN_PIC.EN_PIC_TYPE
     *
     * @return the value of EN_PIC.EN_PIC_TYPE
     *
     * @ibatorgenerated
     */
    public String getEnPicType() {
        return enPicType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EN_PIC.EN_PIC_TYPE
     *
     * @param enPicType the value for EN_PIC.EN_PIC_TYPE
     *
     * @ibatorgenerated
     */
    public void setEnPicType(String enPicType) {
        this.enPicType = enPicType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EN_PIC.EN_PIC_DATE
     *
     * @return the value of EN_PIC.EN_PIC_DATE
     *
     * @ibatorgenerated
     */
    public Date getEnPicDate() {
        return enPicDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EN_PIC.EN_PIC_DATE
     *
     * @param enPicDate the value for EN_PIC.EN_PIC_DATE
     *
     * @ibatorgenerated
     */
    public void setEnPicDate(Date enPicDate) {
        this.enPicDate = enPicDate;
    }
}