package com.tyust.bean.en;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EnPicExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public EnPicExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    protected EnPicExample(EnPicExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andEnPicIdIsNull() {
            addCriterion("EN_PIC_ID is null");
            return this;
        }

        public Criteria andEnPicIdIsNotNull() {
            addCriterion("EN_PIC_ID is not null");
            return this;
        }

        public Criteria andEnPicIdEqualTo(String value) {
            addCriterion("EN_PIC_ID =", value, "enPicId");
            return this;
        }

        public Criteria andEnPicIdNotEqualTo(String value) {
            addCriterion("EN_PIC_ID <>", value, "enPicId");
            return this;
        }

        public Criteria andEnPicIdGreaterThan(String value) {
            addCriterion("EN_PIC_ID >", value, "enPicId");
            return this;
        }

        public Criteria andEnPicIdGreaterThanOrEqualTo(String value) {
            addCriterion("EN_PIC_ID >=", value, "enPicId");
            return this;
        }

        public Criteria andEnPicIdLessThan(String value) {
            addCriterion("EN_PIC_ID <", value, "enPicId");
            return this;
        }

        public Criteria andEnPicIdLessThanOrEqualTo(String value) {
            addCriterion("EN_PIC_ID <=", value, "enPicId");
            return this;
        }

        public Criteria andEnPicIdLike(String value) {
            addCriterion("EN_PIC_ID like", value, "enPicId");
            return this;
        }

        public Criteria andEnPicIdNotLike(String value) {
            addCriterion("EN_PIC_ID not like", value, "enPicId");
            return this;
        }

        public Criteria andEnPicIdIn(List<String> values) {
            addCriterion("EN_PIC_ID in", values, "enPicId");
            return this;
        }

        public Criteria andEnPicIdNotIn(List<String> values) {
            addCriterion("EN_PIC_ID not in", values, "enPicId");
            return this;
        }

        public Criteria andEnPicIdBetween(String value1, String value2) {
            addCriterion("EN_PIC_ID between", value1, value2, "enPicId");
            return this;
        }

        public Criteria andEnPicIdNotBetween(String value1, String value2) {
            addCriterion("EN_PIC_ID not between", value1, value2, "enPicId");
            return this;
        }

        public Criteria andEnApplyIdIsNull() {
            addCriterion("EN_APPLY_ID is null");
            return this;
        }

        public Criteria andEnApplyIdIsNotNull() {
            addCriterion("EN_APPLY_ID is not null");
            return this;
        }

        public Criteria andEnApplyIdEqualTo(String value) {
            addCriterion("EN_APPLY_ID =", value, "enApplyId");
            return this;
        }

        public Criteria andEnApplyIdNotEqualTo(String value) {
            addCriterion("EN_APPLY_ID <>", value, "enApplyId");
            return this;
        }

        public Criteria andEnApplyIdGreaterThan(String value) {
            addCriterion("EN_APPLY_ID >", value, "enApplyId");
            return this;
        }

        public Criteria andEnApplyIdGreaterThanOrEqualTo(String value) {
            addCriterion("EN_APPLY_ID >=", value, "enApplyId");
            return this;
        }

        public Criteria andEnApplyIdLessThan(String value) {
            addCriterion("EN_APPLY_ID <", value, "enApplyId");
            return this;
        }

        public Criteria andEnApplyIdLessThanOrEqualTo(String value) {
            addCriterion("EN_APPLY_ID <=", value, "enApplyId");
            return this;
        }

        public Criteria andEnApplyIdLike(String value) {
            addCriterion("EN_APPLY_ID like", value, "enApplyId");
            return this;
        }

        public Criteria andEnApplyIdNotLike(String value) {
            addCriterion("EN_APPLY_ID not like", value, "enApplyId");
            return this;
        }

        public Criteria andEnApplyIdIn(List<String> values) {
            addCriterion("EN_APPLY_ID in", values, "enApplyId");
            return this;
        }

        public Criteria andEnApplyIdNotIn(List<String> values) {
            addCriterion("EN_APPLY_ID not in", values, "enApplyId");
            return this;
        }

        public Criteria andEnApplyIdBetween(String value1, String value2) {
            addCriterion("EN_APPLY_ID between", value1, value2, "enApplyId");
            return this;
        }

        public Criteria andEnApplyIdNotBetween(String value1, String value2) {
            addCriterion("EN_APPLY_ID not between", value1, value2, "enApplyId");
            return this;
        }

        public Criteria andEnPicUrlIsNull() {
            addCriterion("EN_PIC_URL is null");
            return this;
        }

        public Criteria andEnPicUrlIsNotNull() {
            addCriterion("EN_PIC_URL is not null");
            return this;
        }

        public Criteria andEnPicUrlEqualTo(String value) {
            addCriterion("EN_PIC_URL =", value, "enPicUrl");
            return this;
        }

        public Criteria andEnPicUrlNotEqualTo(String value) {
            addCriterion("EN_PIC_URL <>", value, "enPicUrl");
            return this;
        }

        public Criteria andEnPicUrlGreaterThan(String value) {
            addCriterion("EN_PIC_URL >", value, "enPicUrl");
            return this;
        }

        public Criteria andEnPicUrlGreaterThanOrEqualTo(String value) {
            addCriterion("EN_PIC_URL >=", value, "enPicUrl");
            return this;
        }

        public Criteria andEnPicUrlLessThan(String value) {
            addCriterion("EN_PIC_URL <", value, "enPicUrl");
            return this;
        }

        public Criteria andEnPicUrlLessThanOrEqualTo(String value) {
            addCriterion("EN_PIC_URL <=", value, "enPicUrl");
            return this;
        }

        public Criteria andEnPicUrlLike(String value) {
            addCriterion("EN_PIC_URL like", value, "enPicUrl");
            return this;
        }

        public Criteria andEnPicUrlNotLike(String value) {
            addCriterion("EN_PIC_URL not like", value, "enPicUrl");
            return this;
        }

        public Criteria andEnPicUrlIn(List<String> values) {
            addCriterion("EN_PIC_URL in", values, "enPicUrl");
            return this;
        }

        public Criteria andEnPicUrlNotIn(List<String> values) {
            addCriterion("EN_PIC_URL not in", values, "enPicUrl");
            return this;
        }

        public Criteria andEnPicUrlBetween(String value1, String value2) {
            addCriterion("EN_PIC_URL between", value1, value2, "enPicUrl");
            return this;
        }

        public Criteria andEnPicUrlNotBetween(String value1, String value2) {
            addCriterion("EN_PIC_URL not between", value1, value2, "enPicUrl");
            return this;
        }

        public Criteria andEnPicNameIsNull() {
            addCriterion("EN_PIC_NAME is null");
            return this;
        }

        public Criteria andEnPicNameIsNotNull() {
            addCriterion("EN_PIC_NAME is not null");
            return this;
        }

        public Criteria andEnPicNameEqualTo(String value) {
            addCriterion("EN_PIC_NAME =", value, "enPicName");
            return this;
        }

        public Criteria andEnPicNameNotEqualTo(String value) {
            addCriterion("EN_PIC_NAME <>", value, "enPicName");
            return this;
        }

        public Criteria andEnPicNameGreaterThan(String value) {
            addCriterion("EN_PIC_NAME >", value, "enPicName");
            return this;
        }

        public Criteria andEnPicNameGreaterThanOrEqualTo(String value) {
            addCriterion("EN_PIC_NAME >=", value, "enPicName");
            return this;
        }

        public Criteria andEnPicNameLessThan(String value) {
            addCriterion("EN_PIC_NAME <", value, "enPicName");
            return this;
        }

        public Criteria andEnPicNameLessThanOrEqualTo(String value) {
            addCriterion("EN_PIC_NAME <=", value, "enPicName");
            return this;
        }

        public Criteria andEnPicNameLike(String value) {
            addCriterion("EN_PIC_NAME like", value, "enPicName");
            return this;
        }

        public Criteria andEnPicNameNotLike(String value) {
            addCriterion("EN_PIC_NAME not like", value, "enPicName");
            return this;
        }

        public Criteria andEnPicNameIn(List<String> values) {
            addCriterion("EN_PIC_NAME in", values, "enPicName");
            return this;
        }

        public Criteria andEnPicNameNotIn(List<String> values) {
            addCriterion("EN_PIC_NAME not in", values, "enPicName");
            return this;
        }

        public Criteria andEnPicNameBetween(String value1, String value2) {
            addCriterion("EN_PIC_NAME between", value1, value2, "enPicName");
            return this;
        }

        public Criteria andEnPicNameNotBetween(String value1, String value2) {
            addCriterion("EN_PIC_NAME not between", value1, value2, "enPicName");
            return this;
        }

        public Criteria andEnPicTypeIsNull() {
            addCriterion("EN_PIC_TYPE is null");
            return this;
        }

        public Criteria andEnPicTypeIsNotNull() {
            addCriterion("EN_PIC_TYPE is not null");
            return this;
        }

        public Criteria andEnPicTypeEqualTo(String value) {
            addCriterion("EN_PIC_TYPE =", value, "enPicType");
            return this;
        }

        public Criteria andEnPicTypeNotEqualTo(String value) {
            addCriterion("EN_PIC_TYPE <>", value, "enPicType");
            return this;
        }

        public Criteria andEnPicTypeGreaterThan(String value) {
            addCriterion("EN_PIC_TYPE >", value, "enPicType");
            return this;
        }

        public Criteria andEnPicTypeGreaterThanOrEqualTo(String value) {
            addCriterion("EN_PIC_TYPE >=", value, "enPicType");
            return this;
        }

        public Criteria andEnPicTypeLessThan(String value) {
            addCriterion("EN_PIC_TYPE <", value, "enPicType");
            return this;
        }

        public Criteria andEnPicTypeLessThanOrEqualTo(String value) {
            addCriterion("EN_PIC_TYPE <=", value, "enPicType");
            return this;
        }

        public Criteria andEnPicTypeLike(String value) {
            addCriterion("EN_PIC_TYPE like", value, "enPicType");
            return this;
        }

        public Criteria andEnPicTypeNotLike(String value) {
            addCriterion("EN_PIC_TYPE not like", value, "enPicType");
            return this;
        }

        public Criteria andEnPicTypeIn(List<String> values) {
            addCriterion("EN_PIC_TYPE in", values, "enPicType");
            return this;
        }

        public Criteria andEnPicTypeNotIn(List<String> values) {
            addCriterion("EN_PIC_TYPE not in", values, "enPicType");
            return this;
        }

        public Criteria andEnPicTypeBetween(String value1, String value2) {
            addCriterion("EN_PIC_TYPE between", value1, value2, "enPicType");
            return this;
        }

        public Criteria andEnPicTypeNotBetween(String value1, String value2) {
            addCriterion("EN_PIC_TYPE not between", value1, value2, "enPicType");
            return this;
        }

        public Criteria andEnPicDateIsNull() {
            addCriterion("EN_PIC_DATE is null");
            return this;
        }

        public Criteria andEnPicDateIsNotNull() {
            addCriterion("EN_PIC_DATE is not null");
            return this;
        }

        public Criteria andEnPicDateEqualTo(Date value) {
            addCriterion("EN_PIC_DATE =", value, "enPicDate");
            return this;
        }

        public Criteria andEnPicDateNotEqualTo(Date value) {
            addCriterion("EN_PIC_DATE <>", value, "enPicDate");
            return this;
        }

        public Criteria andEnPicDateGreaterThan(Date value) {
            addCriterion("EN_PIC_DATE >", value, "enPicDate");
            return this;
        }

        public Criteria andEnPicDateGreaterThanOrEqualTo(Date value) {
            addCriterion("EN_PIC_DATE >=", value, "enPicDate");
            return this;
        }

        public Criteria andEnPicDateLessThan(Date value) {
            addCriterion("EN_PIC_DATE <", value, "enPicDate");
            return this;
        }

        public Criteria andEnPicDateLessThanOrEqualTo(Date value) {
            addCriterion("EN_PIC_DATE <=", value, "enPicDate");
            return this;
        }

        public Criteria andEnPicDateIn(List<Date> values) {
            addCriterion("EN_PIC_DATE in", values, "enPicDate");
            return this;
        }

        public Criteria andEnPicDateNotIn(List<Date> values) {
            addCriterion("EN_PIC_DATE not in", values, "enPicDate");
            return this;
        }

        public Criteria andEnPicDateBetween(Date value1, Date value2) {
            addCriterion("EN_PIC_DATE between", value1, value2, "enPicDate");
            return this;
        }

        public Criteria andEnPicDateNotBetween(Date value1, Date value2) {
            addCriterion("EN_PIC_DATE not between", value1, value2, "enPicDate");
            return this;
        }
    }
}