package com.tyust.bean.en;

import java.util.Date;

public class EnTestReport {

    private String environmentTestReportId;


    private String environmentApplyId;


    private String testReportNumber;

    private String testUserName;


    private Date testDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ENVIRONMENT_TEST_REPORT.TEST_UNIT_NAME
     *
     * @ibatorgenerated
     */
    private String testUnitName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ENVIRONMENT_TEST_REPORT.TEST_STATUS
     *
     * @ibatorgenerated
     */
    private String testStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ENVIRONMENT_TEST_REPORT.TEST_SAMPLE_NAME
     *
     * @ibatorgenerated
     */
    private String testSampleName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ENVIRONMENT_TEST_REPORT.TEST_RESULT
     *
     * @ibatorgenerated
     */
    private String testResult;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ENVIRONMENT_TEST_REPORT.ENVIRONMENT_TEST_REPORT_ID
     *
     * @return the value of ENVIRONMENT_TEST_REPORT.ENVIRONMENT_TEST_REPORT_ID
     *
     * @ibatorgenerated
     */
    public String getEnvironmentTestReportId() {
        return environmentTestReportId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ENVIRONMENT_TEST_REPORT.ENVIRONMENT_TEST_REPORT_ID
     *
     * @param environmentTestReportId the value for ENVIRONMENT_TEST_REPORT.ENVIRONMENT_TEST_REPORT_ID
     *
     * @ibatorgenerated
     */
    public void setEnvironmentTestReportId(String environmentTestReportId) {
        this.environmentTestReportId = environmentTestReportId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ENVIRONMENT_TEST_REPORT.ENVIRONMENT_APPLY_ID
     *
     * @return the value of ENVIRONMENT_TEST_REPORT.ENVIRONMENT_APPLY_ID
     *
     * @ibatorgenerated
     */
    public String getEnvironmentApplyId() {
        return environmentApplyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ENVIRONMENT_TEST_REPORT.ENVIRONMENT_APPLY_ID
     *
     * @param environmentApplyId the value for ENVIRONMENT_TEST_REPORT.ENVIRONMENT_APPLY_ID
     *
     * @ibatorgenerated
     */
    public void setEnvironmentApplyId(String environmentApplyId) {
        this.environmentApplyId = environmentApplyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ENVIRONMENT_TEST_REPORT.TEST_REPORT_NUMBER
     *
     * @return the value of ENVIRONMENT_TEST_REPORT.TEST_REPORT_NUMBER
     *
     * @ibatorgenerated
     */
    public String getTestReportNumber() {
        return testReportNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ENVIRONMENT_TEST_REPORT.TEST_REPORT_NUMBER
     *
     * @param testReportNumber the value for ENVIRONMENT_TEST_REPORT.TEST_REPORT_NUMBER
     *
     * @ibatorgenerated
     */
    public void setTestReportNumber(String testReportNumber) {
        this.testReportNumber = testReportNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ENVIRONMENT_TEST_REPORT.TEST_USER_NAME
     *
     * @return the value of ENVIRONMENT_TEST_REPORT.TEST_USER_NAME
     *
     * @ibatorgenerated
     */
    public String getTestUserName() {
        return testUserName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ENVIRONMENT_TEST_REPORT.TEST_USER_NAME
     *
     * @param testUserName the value for ENVIRONMENT_TEST_REPORT.TEST_USER_NAME
     *
     * @ibatorgenerated
     */
    public void setTestUserName(String testUserName) {
        this.testUserName = testUserName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ENVIRONMENT_TEST_REPORT.TEST_DATE
     *
     * @return the value of ENVIRONMENT_TEST_REPORT.TEST_DATE
     *
     * @ibatorgenerated
     */
    public Date getTestDate() {
        return testDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ENVIRONMENT_TEST_REPORT.TEST_DATE
     *
     * @param testDate the value for ENVIRONMENT_TEST_REPORT.TEST_DATE
     *
     * @ibatorgenerated
     */
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ENVIRONMENT_TEST_REPORT.TEST_UNIT_NAME
     *
     * @return the value of ENVIRONMENT_TEST_REPORT.TEST_UNIT_NAME
     *
     * @ibatorgenerated
     */
    public String getTestUnitName() {
        return testUnitName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ENVIRONMENT_TEST_REPORT.TEST_UNIT_NAME
     *
     * @param testUnitName the value for ENVIRONMENT_TEST_REPORT.TEST_UNIT_NAME
     *
     * @ibatorgenerated
     */
    public void setTestUnitName(String testUnitName) {
        this.testUnitName = testUnitName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ENVIRONMENT_TEST_REPORT.TEST_STATUS
     *
     * @return the value of ENVIRONMENT_TEST_REPORT.TEST_STATUS
     *
     * @ibatorgenerated
     */
    public String getTestStatus() {
        return testStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ENVIRONMENT_TEST_REPORT.TEST_STATUS
     *
     * @param testStatus the value for ENVIRONMENT_TEST_REPORT.TEST_STATUS
     *
     * @ibatorgenerated
     */
    public void setTestStatus(String testStatus) {
        this.testStatus = testStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ENVIRONMENT_TEST_REPORT.TEST_SAMPLE_NAME
     *
     * @return the value of ENVIRONMENT_TEST_REPORT.TEST_SAMPLE_NAME
     *
     * @ibatorgenerated
     */
    public String getTestSampleName() {
        return testSampleName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ENVIRONMENT_TEST_REPORT.TEST_SAMPLE_NAME
     *
     * @param testSampleName the value for ENVIRONMENT_TEST_REPORT.TEST_SAMPLE_NAME
     *
     * @ibatorgenerated
     */
    public void setTestSampleName(String testSampleName) {
        this.testSampleName = testSampleName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ENVIRONMENT_TEST_REPORT.TEST_RESULT
     *
     * @return the value of ENVIRONMENT_TEST_REPORT.TEST_RESULT
     *
     * @ibatorgenerated
     */
    public String getTestResult() {
        return testResult;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ENVIRONMENT_TEST_REPORT.TEST_RESULT
     *
     * @param testResult the value for ENVIRONMENT_TEST_REPORT.TEST_RESULT
     *
     * @ibatorgenerated
     */
    public void setTestResult(String testResult) {
        this.testResult = testResult;
    }
}