package com.tyust.bean.en;

public class EnTestInstrument {


	private String etiId;

	private String environmentTestReportId;

	private String instrumentId;


	public String getEtiId() {
		return etiId;
	}

	public void setEtiId(String etiId) {
		this.etiId = etiId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column ENVIRONMENT_TEST_INSTRUMENT.ENVIRONMENT_TEST_REPORT_ID
	 * @return  the value of ENVIRONMENT_TEST_INSTRUMENT.ENVIRONMENT_TEST_REPORT_ID
	 * @ibatorgenerated
	 */
	public String getEnvironmentTestReportId() {
		return environmentTestReportId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column ENVIRONMENT_TEST_INSTRUMENT.ENVIRONMENT_TEST_REPORT_ID
	 * @param environmentTestReportId  the value for ENVIRONMENT_TEST_INSTRUMENT.ENVIRONMENT_TEST_REPORT_ID
	 * @ibatorgenerated
	 */
	public void setEnvironmentTestReportId(String environmentTestReportId) {
		this.environmentTestReportId = environmentTestReportId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column ENVIRONMENT_TEST_INSTRUMENT.INSTRUMENT_ID
	 * @return  the value of ENVIRONMENT_TEST_INSTRUMENT.INSTRUMENT_ID
	 * @ibatorgenerated
	 */
	public String getInstrumentId() {
		return instrumentId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column ENVIRONMENT_TEST_INSTRUMENT.INSTRUMENT_ID
	 * @param instrumentId  the value for ENVIRONMENT_TEST_INSTRUMENT.INSTRUMENT_ID
	 * @ibatorgenerated
	 */
	public void setInstrumentId(String instrumentId) {
		this.instrumentId = instrumentId;
	}
}