package com.tyust.bean.en;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.tyust.common.IbatorGenExamplePageHelper;

public class EnTestReportExample extends IbatorGenExamplePageHelper{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ENVIRONMENT_TEST_REPORT
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ENVIRONMENT_TEST_REPORT
     *
     * @ibatorgenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public EnTestReportExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_TEST_REPORT
     *
     * @ibatorgenerated
     */
    protected EnTestReportExample(EnTestReportExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_TEST_REPORT
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ENVIRONMENT_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andEnvironmentTestReportIdIsNull() {
            addCriterion("ENVIRONMENT_TEST_REPORT_ID is null");
            return this;
        }

        public Criteria andEnvironmentTestReportIdIsNotNull() {
            addCriterion("ENVIRONMENT_TEST_REPORT_ID is not null");
            return this;
        }

        public Criteria andEnvironmentTestReportIdEqualTo(String value) {
            addCriterion("ENVIRONMENT_TEST_REPORT_ID =", value, "environmentTestReportId");
            return this;
        }

        public Criteria andEnvironmentTestReportIdNotEqualTo(String value) {
            addCriterion("ENVIRONMENT_TEST_REPORT_ID <>", value, "environmentTestReportId");
            return this;
        }

        public Criteria andEnvironmentTestReportIdGreaterThan(String value) {
            addCriterion("ENVIRONMENT_TEST_REPORT_ID >", value, "environmentTestReportId");
            return this;
        }

        public Criteria andEnvironmentTestReportIdGreaterThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_TEST_REPORT_ID >=", value, "environmentTestReportId");
            return this;
        }

        public Criteria andEnvironmentTestReportIdLessThan(String value) {
            addCriterion("ENVIRONMENT_TEST_REPORT_ID <", value, "environmentTestReportId");
            return this;
        }

        public Criteria andEnvironmentTestReportIdLessThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_TEST_REPORT_ID <=", value, "environmentTestReportId");
            return this;
        }

        public Criteria andEnvironmentTestReportIdLike(String value) {
            addCriterion("ENVIRONMENT_TEST_REPORT_ID like", value, "environmentTestReportId");
            return this;
        }

        public Criteria andEnvironmentTestReportIdNotLike(String value) {
            addCriterion("ENVIRONMENT_TEST_REPORT_ID not like", value, "environmentTestReportId");
            return this;
        }

        public Criteria andEnvironmentTestReportIdIn(List<String> values) {
            addCriterion("ENVIRONMENT_TEST_REPORT_ID in", values, "environmentTestReportId");
            return this;
        }

        public Criteria andEnvironmentTestReportIdNotIn(List<String> values) {
            addCriterion("ENVIRONMENT_TEST_REPORT_ID not in", values, "environmentTestReportId");
            return this;
        }

        public Criteria andEnvironmentTestReportIdBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_TEST_REPORT_ID between", value1, value2, "environmentTestReportId");
            return this;
        }

        public Criteria andEnvironmentTestReportIdNotBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_TEST_REPORT_ID not between", value1, value2, "environmentTestReportId");
            return this;
        }

        public Criteria andEnvironmentApplyIdIsNull() {
            addCriterion("ENVIRONMENT_APPLY_ID is null");
            return this;
        }

        public Criteria andEnvironmentApplyIdIsNotNull() {
            addCriterion("ENVIRONMENT_APPLY_ID is not null");
            return this;
        }

        public Criteria andEnvironmentApplyIdEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID =", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdNotEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID <>", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdGreaterThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID >", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdGreaterThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID >=", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdLessThan(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID <", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdLessThanOrEqualTo(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID <=", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID like", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdNotLike(String value) {
            addCriterion("ENVIRONMENT_APPLY_ID not like", value, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_ID in", values, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdNotIn(List<String> values) {
            addCriterion("ENVIRONMENT_APPLY_ID not in", values, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_ID between", value1, value2, "environmentApplyId");
            return this;
        }

        public Criteria andEnvironmentApplyIdNotBetween(String value1, String value2) {
            addCriterion("ENVIRONMENT_APPLY_ID not between", value1, value2, "environmentApplyId");
            return this;
        }

        public Criteria andTestReportNumberIsNull() {
            addCriterion("TEST_REPORT_NUMBER is null");
            return this;
        }

        public Criteria andTestReportNumberIsNotNull() {
            addCriterion("TEST_REPORT_NUMBER is not null");
            return this;
        }

        public Criteria andTestReportNumberEqualTo(String value) {
            addCriterion("TEST_REPORT_NUMBER =", value, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberNotEqualTo(String value) {
            addCriterion("TEST_REPORT_NUMBER <>", value, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberGreaterThan(String value) {
            addCriterion("TEST_REPORT_NUMBER >", value, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberGreaterThanOrEqualTo(String value) {
            addCriterion("TEST_REPORT_NUMBER >=", value, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberLessThan(String value) {
            addCriterion("TEST_REPORT_NUMBER <", value, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberLessThanOrEqualTo(String value) {
            addCriterion("TEST_REPORT_NUMBER <=", value, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberLike(String value) {
            addCriterion("TEST_REPORT_NUMBER like", value, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberNotLike(String value) {
            addCriterion("TEST_REPORT_NUMBER not like", value, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberIn(List<String> values) {
            addCriterion("TEST_REPORT_NUMBER in", values, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberNotIn(List<String> values) {
            addCriterion("TEST_REPORT_NUMBER not in", values, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberBetween(String value1, String value2) {
            addCriterion("TEST_REPORT_NUMBER between", value1, value2, "testReportNumber");
            return this;
        }

        public Criteria andTestReportNumberNotBetween(String value1, String value2) {
            addCriterion("TEST_REPORT_NUMBER not between", value1, value2, "testReportNumber");
            return this;
        }

        public Criteria andTestUserNameIsNull() {
            addCriterion("TEST_USER_NAME is null");
            return this;
        }

        public Criteria andTestUserNameIsNotNull() {
            addCriterion("TEST_USER_NAME is not null");
            return this;
        }

        public Criteria andTestUserNameEqualTo(String value) {
            addCriterion("TEST_USER_NAME =", value, "testUserName");
            return this;
        }

        public Criteria andTestUserNameNotEqualTo(String value) {
            addCriterion("TEST_USER_NAME <>", value, "testUserName");
            return this;
        }

        public Criteria andTestUserNameGreaterThan(String value) {
            addCriterion("TEST_USER_NAME >", value, "testUserName");
            return this;
        }

        public Criteria andTestUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("TEST_USER_NAME >=", value, "testUserName");
            return this;
        }

        public Criteria andTestUserNameLessThan(String value) {
            addCriterion("TEST_USER_NAME <", value, "testUserName");
            return this;
        }

        public Criteria andTestUserNameLessThanOrEqualTo(String value) {
            addCriterion("TEST_USER_NAME <=", value, "testUserName");
            return this;
        }

        public Criteria andTestUserNameLike(String value) {
            addCriterion("TEST_USER_NAME like", value, "testUserName");
            return this;
        }

        public Criteria andTestUserNameNotLike(String value) {
            addCriterion("TEST_USER_NAME not like", value, "testUserName");
            return this;
        }

        public Criteria andTestUserNameIn(List<String> values) {
            addCriterion("TEST_USER_NAME in", values, "testUserName");
            return this;
        }

        public Criteria andTestUserNameNotIn(List<String> values) {
            addCriterion("TEST_USER_NAME not in", values, "testUserName");
            return this;
        }

        public Criteria andTestUserNameBetween(String value1, String value2) {
            addCriterion("TEST_USER_NAME between", value1, value2, "testUserName");
            return this;
        }

        public Criteria andTestUserNameNotBetween(String value1, String value2) {
            addCriterion("TEST_USER_NAME not between", value1, value2, "testUserName");
            return this;
        }

        public Criteria andTestDateIsNull() {
            addCriterion("TEST_DATE is null");
            return this;
        }

        public Criteria andTestDateIsNotNull() {
            addCriterion("TEST_DATE is not null");
            return this;
        }

        public Criteria andTestDateEqualTo(Date value) {
            addCriterion("TEST_DATE =", value, "testDate");
            return this;
        }

        public Criteria andTestDateNotEqualTo(Date value) {
            addCriterion("TEST_DATE <>", value, "testDate");
            return this;
        }

        public Criteria andTestDateGreaterThan(Date value) {
            addCriterion("TEST_DATE >", value, "testDate");
            return this;
        }

        public Criteria andTestDateGreaterThanOrEqualTo(Date value) {
            addCriterion("TEST_DATE >=", value, "testDate");
            return this;
        }

        public Criteria andTestDateLessThan(Date value) {
            addCriterion("TEST_DATE <", value, "testDate");
            return this;
        }

        public Criteria andTestDateLessThanOrEqualTo(Date value) {
            addCriterion("TEST_DATE <=", value, "testDate");
            return this;
        }

        public Criteria andTestDateIn(List<Date> values) {
            addCriterion("TEST_DATE in", values, "testDate");
            return this;
        }

        public Criteria andTestDateNotIn(List<Date> values) {
            addCriterion("TEST_DATE not in", values, "testDate");
            return this;
        }

        public Criteria andTestDateBetween(Date value1, Date value2) {
            addCriterion("TEST_DATE between", value1, value2, "testDate");
            return this;
        }

        public Criteria andTestDateNotBetween(Date value1, Date value2) {
            addCriterion("TEST_DATE not between", value1, value2, "testDate");
            return this;
        }

        public Criteria andTestUnitNameIsNull() {
            addCriterion("TEST_UNIT_NAME is null");
            return this;
        }

        public Criteria andTestUnitNameIsNotNull() {
            addCriterion("TEST_UNIT_NAME is not null");
            return this;
        }

        public Criteria andTestUnitNameEqualTo(String value) {
            addCriterion("TEST_UNIT_NAME =", value, "testUnitName");
            return this;
        }

        public Criteria andTestUnitNameNotEqualTo(String value) {
            addCriterion("TEST_UNIT_NAME <>", value, "testUnitName");
            return this;
        }

        public Criteria andTestUnitNameGreaterThan(String value) {
            addCriterion("TEST_UNIT_NAME >", value, "testUnitName");
            return this;
        }

        public Criteria andTestUnitNameGreaterThanOrEqualTo(String value) {
            addCriterion("TEST_UNIT_NAME >=", value, "testUnitName");
            return this;
        }

        public Criteria andTestUnitNameLessThan(String value) {
            addCriterion("TEST_UNIT_NAME <", value, "testUnitName");
            return this;
        }

        public Criteria andTestUnitNameLessThanOrEqualTo(String value) {
            addCriterion("TEST_UNIT_NAME <=", value, "testUnitName");
            return this;
        }

        public Criteria andTestUnitNameLike(String value) {
            addCriterion("TEST_UNIT_NAME like", value, "testUnitName");
            return this;
        }

        public Criteria andTestUnitNameNotLike(String value) {
            addCriterion("TEST_UNIT_NAME not like", value, "testUnitName");
            return this;
        }

        public Criteria andTestUnitNameIn(List<String> values) {
            addCriterion("TEST_UNIT_NAME in", values, "testUnitName");
            return this;
        }

        public Criteria andTestUnitNameNotIn(List<String> values) {
            addCriterion("TEST_UNIT_NAME not in", values, "testUnitName");
            return this;
        }

        public Criteria andTestUnitNameBetween(String value1, String value2) {
            addCriterion("TEST_UNIT_NAME between", value1, value2, "testUnitName");
            return this;
        }

        public Criteria andTestUnitNameNotBetween(String value1, String value2) {
            addCriterion("TEST_UNIT_NAME not between", value1, value2, "testUnitName");
            return this;
        }

        public Criteria andTestStatusIsNull() {
            addCriterion("TEST_STATUS is null");
            return this;
        }

        public Criteria andTestStatusIsNotNull() {
            addCriterion("TEST_STATUS is not null");
            return this;
        }

        public Criteria andTestStatusEqualTo(String value) {
            addCriterion("TEST_STATUS =", value, "testStatus");
            return this;
        }

        public Criteria andTestStatusNotEqualTo(String value) {
            addCriterion("TEST_STATUS <>", value, "testStatus");
            return this;
        }

        public Criteria andTestStatusGreaterThan(String value) {
            addCriterion("TEST_STATUS >", value, "testStatus");
            return this;
        }

        public Criteria andTestStatusGreaterThanOrEqualTo(String value) {
            addCriterion("TEST_STATUS >=", value, "testStatus");
            return this;
        }

        public Criteria andTestStatusLessThan(String value) {
            addCriterion("TEST_STATUS <", value, "testStatus");
            return this;
        }

        public Criteria andTestStatusLessThanOrEqualTo(String value) {
            addCriterion("TEST_STATUS <=", value, "testStatus");
            return this;
        }

        public Criteria andTestStatusLike(String value) {
            addCriterion("TEST_STATUS like", value, "testStatus");
            return this;
        }

        public Criteria andTestStatusNotLike(String value) {
            addCriterion("TEST_STATUS not like", value, "testStatus");
            return this;
        }

        public Criteria andTestStatusIn(List<String> values) {
            addCriterion("TEST_STATUS in", values, "testStatus");
            return this;
        }

        public Criteria andTestStatusNotIn(List<String> values) {
            addCriterion("TEST_STATUS not in", values, "testStatus");
            return this;
        }

        public Criteria andTestStatusBetween(String value1, String value2) {
            addCriterion("TEST_STATUS between", value1, value2, "testStatus");
            return this;
        }

        public Criteria andTestStatusNotBetween(String value1, String value2) {
            addCriterion("TEST_STATUS not between", value1, value2, "testStatus");
            return this;
        }

        public Criteria andTestSampleNameIsNull() {
            addCriterion("TEST_SAMPLE_NAME is null");
            return this;
        }

        public Criteria andTestSampleNameIsNotNull() {
            addCriterion("TEST_SAMPLE_NAME is not null");
            return this;
        }

        public Criteria andTestSampleNameEqualTo(String value) {
            addCriterion("TEST_SAMPLE_NAME =", value, "testSampleName");
            return this;
        }

        public Criteria andTestSampleNameNotEqualTo(String value) {
            addCriterion("TEST_SAMPLE_NAME <>", value, "testSampleName");
            return this;
        }

        public Criteria andTestSampleNameGreaterThan(String value) {
            addCriterion("TEST_SAMPLE_NAME >", value, "testSampleName");
            return this;
        }

        public Criteria andTestSampleNameGreaterThanOrEqualTo(String value) {
            addCriterion("TEST_SAMPLE_NAME >=", value, "testSampleName");
            return this;
        }

        public Criteria andTestSampleNameLessThan(String value) {
            addCriterion("TEST_SAMPLE_NAME <", value, "testSampleName");
            return this;
        }

        public Criteria andTestSampleNameLessThanOrEqualTo(String value) {
            addCriterion("TEST_SAMPLE_NAME <=", value, "testSampleName");
            return this;
        }

        public Criteria andTestSampleNameLike(String value) {
            addCriterion("TEST_SAMPLE_NAME like", value, "testSampleName");
            return this;
        }

        public Criteria andTestSampleNameNotLike(String value) {
            addCriterion("TEST_SAMPLE_NAME not like", value, "testSampleName");
            return this;
        }

        public Criteria andTestSampleNameIn(List<String> values) {
            addCriterion("TEST_SAMPLE_NAME in", values, "testSampleName");
            return this;
        }

        public Criteria andTestSampleNameNotIn(List<String> values) {
            addCriterion("TEST_SAMPLE_NAME not in", values, "testSampleName");
            return this;
        }

        public Criteria andTestSampleNameBetween(String value1, String value2) {
            addCriterion("TEST_SAMPLE_NAME between", value1, value2, "testSampleName");
            return this;
        }

        public Criteria andTestSampleNameNotBetween(String value1, String value2) {
            addCriterion("TEST_SAMPLE_NAME not between", value1, value2, "testSampleName");
            return this;
        }

        public Criteria andTestResultIsNull() {
            addCriterion("TEST_RESULT is null");
            return this;
        }

        public Criteria andTestResultIsNotNull() {
            addCriterion("TEST_RESULT is not null");
            return this;
        }

        public Criteria andTestResultEqualTo(String value) {
            addCriterion("TEST_RESULT =", value, "testResult");
            return this;
        }

        public Criteria andTestResultNotEqualTo(String value) {
            addCriterion("TEST_RESULT <>", value, "testResult");
            return this;
        }

        public Criteria andTestResultGreaterThan(String value) {
            addCriterion("TEST_RESULT >", value, "testResult");
            return this;
        }

        public Criteria andTestResultGreaterThanOrEqualTo(String value) {
            addCriterion("TEST_RESULT >=", value, "testResult");
            return this;
        }

        public Criteria andTestResultLessThan(String value) {
            addCriterion("TEST_RESULT <", value, "testResult");
            return this;
        }

        public Criteria andTestResultLessThanOrEqualTo(String value) {
            addCriterion("TEST_RESULT <=", value, "testResult");
            return this;
        }

        public Criteria andTestResultLike(String value) {
            addCriterion("TEST_RESULT like", value, "testResult");
            return this;
        }

        public Criteria andTestResultNotLike(String value) {
            addCriterion("TEST_RESULT not like", value, "testResult");
            return this;
        }

        public Criteria andTestResultIn(List<String> values) {
            addCriterion("TEST_RESULT in", values, "testResult");
            return this;
        }

        public Criteria andTestResultNotIn(List<String> values) {
            addCriterion("TEST_RESULT not in", values, "testResult");
            return this;
        }

        public Criteria andTestResultBetween(String value1, String value2) {
            addCriterion("TEST_RESULT between", value1, value2, "testResult");
            return this;
        }

        public Criteria andTestResultNotBetween(String value1, String value2) {
            addCriterion("TEST_RESULT not between", value1, value2, "testResult");
            return this;
        }
    }
}