
  CREATE TABLE "SBGL"."NT_DEVICE_TEST_APPLY_ATTACH" 
   (	"DEV_ATTACH_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DEV_APPLY_ID" VARCHAR2(50 BYTE), 
	"DEV_ATTACH_URL" VARCHAR2(50 BYTE), 
	"DEV_ATTACH_NAME" VARCHAR2(200 BYTE), 
	"DEV_ATTACH_TYPE" CHAR(1 BYTE) DEFAULT 1, 
	"DEV_ATTACH_DATE" TIMESTAMP (6),
	constraint PK_NT_DEVICE_TEST_APPLY_ATTACH primary key (DEV_ATTACH_ID)
);
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "SBGL"."NT_DEVICE_TEST_APPLY_ATTACH"."DEV_ATTACH_ID" IS '主键，UUID生成';
 
   COMMENT ON COLUMN "SBGL"."NT_DEVICE_TEST_APPLY_ATTACH"."DEV_APPLY_ID" IS '设备检测申请编号，引用NT_DEVICE_APPLY的主键';
 
   COMMENT ON COLUMN "SBGL"."NT_DEVICE_TEST_APPLY_ATTACH"."DEV_ATTACH_URL" IS '附件路径';
 
   COMMENT ON COLUMN "SBGL"."NT_DEVICE_TEST_APPLY_ATTACH"."DEV_ATTACH_NAME" IS '附件原名';
 
   COMMENT ON COLUMN "SBGL"."NT_DEVICE_TEST_APPLY_ATTACH"."DEV_ATTACH_TYPE" IS '附件类型：默认为1，其余保留';
 
   COMMENT ON COLUMN "SBGL"."NT_DEVICE_TEST_APPLY_ATTACH"."DEV_ATTACH_DATE" IS '上传日期';
 
