package com.tyust.dao.en;

import com.tyust.bean.en.EnApplyInfo;
import com.tyust.bean.en.EnApplyInfoExample;
import java.util.List;

public interface EnApplyInfoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    int countByExample(EnApplyInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    int deleteByExample(EnApplyInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(String environmentApplyId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    void insert(EnApplyInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    void insertSelective(EnApplyInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    List<EnApplyInfo> selectByExample(EnApplyInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    EnApplyInfo selectByPrimaryKey(String environmentApplyId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(EnApplyInfo record, EnApplyInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    int updateByExample(EnApplyInfo record, EnApplyInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(EnApplyInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_APPLY_INFO
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(EnApplyInfo record);
}