package com.tyust.dao.en;

import com.tyust.bean.en.EnAttach;
import com.tyust.bean.en.EnAttachExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EnAttachDAOImpl extends SqlMapClientDaoSupport implements EnAttachDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public EnAttachDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public int countByExample(EnAttachExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("ENVIRONMENT_ATTACH.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public int deleteByExample(EnAttachExample example) {
        int rows = getSqlMapClientTemplate().delete("ENVIRONMENT_ATTACH.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(String environmentAttachId) {
        EnAttach key = new EnAttach();
        key.setEnvironmentAttachId(environmentAttachId);
        int rows = getSqlMapClientTemplate().delete("ENVIRONMENT_ATTACH.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public void insert(EnAttach record) {
        getSqlMapClientTemplate().insert("ENVIRONMENT_ATTACH.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public void insertSelective(EnAttach record) {
        getSqlMapClientTemplate().insert("ENVIRONMENT_ATTACH.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<EnAttach> selectByExample(EnAttachExample example) {
        List<EnAttach> list = getSqlMapClientTemplate().queryForList("ENVIRONMENT_ATTACH.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public EnAttach selectByPrimaryKey(String environmentAttachId) {
        EnAttach key = new EnAttach();
        key.setEnvironmentAttachId(environmentAttachId);
        EnAttach record = (EnAttach) getSqlMapClientTemplate().queryForObject("ENVIRONMENT_ATTACH.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(EnAttach record, EnAttachExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ENVIRONMENT_ATTACH.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public int updateByExample(EnAttach record, EnAttachExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ENVIRONMENT_ATTACH.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(EnAttach record) {
        int rows = getSqlMapClientTemplate().update("ENVIRONMENT_ATTACH.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(EnAttach record) {
        int rows = getSqlMapClientTemplate().update("ENVIRONMENT_ATTACH.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ENVIRONMENT_ATTACH
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends EnAttachExample {
        private Object record;

        public UpdateByExampleParms(Object record, EnAttachExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}