package com.tyust.dao.en;

import com.tyust.bean.en.EnPic;
import com.tyust.bean.en.EnPicExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EnPicDAOImpl extends SqlMapClientDaoSupport implements EnPicDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public EnPicDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public int countByExample(EnPicExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EN_PIC.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public int deleteByExample(EnPicExample example) {
        int rows = getSqlMapClientTemplate().delete("EN_PIC.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(String enPicId) {
        EnPic key = new EnPic();
        key.setEnPicId(enPicId);
        int rows = getSqlMapClientTemplate().delete("EN_PIC.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public void insert(EnPic record) {
        getSqlMapClientTemplate().insert("EN_PIC.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public void insertSelective(EnPic record) {
        getSqlMapClientTemplate().insert("EN_PIC.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<EnPic> selectByExample(EnPicExample example) {
        List<EnPic> list = getSqlMapClientTemplate().queryForList("EN_PIC.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public EnPic selectByPrimaryKey(String enPicId) {
        EnPic key = new EnPic();
        key.setEnPicId(enPicId);
        EnPic record = (EnPic) getSqlMapClientTemplate().queryForObject("EN_PIC.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(EnPic record, EnPicExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EN_PIC.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public int updateByExample(EnPic record, EnPicExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EN_PIC.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(EnPic record) {
        int rows = getSqlMapClientTemplate().update("EN_PIC.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(EnPic record) {
        int rows = getSqlMapClientTemplate().update("EN_PIC.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table EN_PIC
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends EnPicExample {
        private Object record;

        public UpdateByExampleParms(Object record, EnPicExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}