package com.tyust.dao.en;

import com.tyust.bean.en.EnTestInstrument;
import com.tyust.bean.en.EnTestInstrumentExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EnTestInstrumentDAOImpl extends SqlMapClientDaoSupport implements EnTestInstrumentDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	public EnTestInstrumentDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	public int countByExample(EnTestInstrumentExample example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("ENVIRONMENT_TEST_INSTRUMENT.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	public int deleteByExample(EnTestInstrumentExample example) {
		int rows = getSqlMapClientTemplate().delete("ENVIRONMENT_TEST_INSTRUMENT.ibatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(String etiId) {
		EnTestInstrument key = new EnTestInstrument();
		key.setEtiId(etiId);
		int rows = getSqlMapClientTemplate().delete("ENVIRONMENT_TEST_INSTRUMENT.ibatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	public void insert(EnTestInstrument record) {
		getSqlMapClientTemplate().insert("ENVIRONMENT_TEST_INSTRUMENT.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	public void insertSelective(EnTestInstrument record) {
		getSqlMapClientTemplate().insert("ENVIRONMENT_TEST_INSTRUMENT.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<EnTestInstrument> selectByExample(EnTestInstrumentExample example) {
		List<EnTestInstrument> list = getSqlMapClientTemplate()
				.queryForList("ENVIRONMENT_TEST_INSTRUMENT.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	public EnTestInstrument selectByPrimaryKey(String etiId) {
		EnTestInstrument key = new EnTestInstrument();
		key.setEtiId(etiId);
		EnTestInstrument record = (EnTestInstrument) getSqlMapClientTemplate()
				.queryForObject("ENVIRONMENT_TEST_INSTRUMENT.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(EnTestInstrument record, EnTestInstrumentExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("ENVIRONMENT_TEST_INSTRUMENT.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	public int updateByExample(EnTestInstrument record, EnTestInstrumentExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("ENVIRONMENT_TEST_INSTRUMENT.ibatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(EnTestInstrument record) {
		int rows = getSqlMapClientTemplate()
				.update("ENVIRONMENT_TEST_INSTRUMENT.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(EnTestInstrument record) {
		int rows = getSqlMapClientTemplate().update("ENVIRONMENT_TEST_INSTRUMENT.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends EnTestInstrumentExample {
		private Object record;

		public UpdateByExampleParms(Object record, EnTestInstrumentExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}