package com.tyust.dao.en;

import com.tyust.bean.en.EnTestInstrument;
import com.tyust.bean.en.EnTestInstrumentExample;
import java.util.List;

public interface EnTestInstrumentDAO {


	int countByExample(EnTestInstrumentExample example);

	int deleteByExample(EnTestInstrumentExample example);


	int deleteByPrimaryKey(String etiId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	void insert(EnTestInstrument record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	void insertSelective(EnTestInstrument record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	List<EnTestInstrument> selectByExample(EnTestInstrumentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	EnTestInstrument selectByPrimaryKey(String etiId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(EnTestInstrument record, EnTestInstrumentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	int updateByExample(EnTestInstrument record, EnTestInstrumentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(EnTestInstrument record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ENVIRONMENT_TEST_INSTRUMENT
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(EnTestInstrument record);
}