package com.tyust.dao.pbs;

import com.tyust.bean.pbs.PbsAttach;
import com.tyust.bean.pbs.PbsAttachExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PbsAttachDAOImpl extends SqlMapClientDaoSupport implements PbsAttachDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public PbsAttachDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public int countByExample(PbsAttachExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("PBS_ATTACH.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public int deleteByExample(PbsAttachExample example) {
        int rows = getSqlMapClientTemplate().delete("PBS_ATTACH.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(String pbsAttachId) {
        PbsAttach key = new PbsAttach();
        key.setPbsAttachId(pbsAttachId);
        int rows = getSqlMapClientTemplate().delete("PBS_ATTACH.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public void insert(PbsAttach record) {
        getSqlMapClientTemplate().insert("PBS_ATTACH.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public void insertSelective(PbsAttach record) {
        getSqlMapClientTemplate().insert("PBS_ATTACH.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<PbsAttach> selectByExample(PbsAttachExample example) {
        List<PbsAttach> list = getSqlMapClientTemplate().queryForList("PBS_ATTACH.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public PbsAttach selectByPrimaryKey(String pbsAttachId) {
        PbsAttach key = new PbsAttach();
        key.setPbsAttachId(pbsAttachId);
        PbsAttach record = (PbsAttach) getSqlMapClientTemplate().queryForObject("PBS_ATTACH.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(PbsAttach record, PbsAttachExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("PBS_ATTACH.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public int updateByExample(PbsAttach record, PbsAttachExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("PBS_ATTACH.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(PbsAttach record) {
        int rows = getSqlMapClientTemplate().update("PBS_ATTACH.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(PbsAttach record) {
        int rows = getSqlMapClientTemplate().update("PBS_ATTACH.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends PbsAttachExample {
        private Object record;

        public UpdateByExampleParms(Object record, PbsAttachExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}