package com.tyust.dao.pbs;

import com.tyust.bean.pbs.PbsAttach;
import com.tyust.bean.pbs.PbsAttachExample;
import java.util.List;

public interface PbsAttachDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    int countByExample(PbsAttachExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    int deleteByExample(PbsAttachExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(String pbsAttachId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    void insert(PbsAttach record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    void insertSelective(PbsAttach record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    List<PbsAttach> selectByExample(PbsAttachExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    PbsAttach selectByPrimaryKey(String pbsAttachId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(PbsAttach record, PbsAttachExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    int updateByExample(PbsAttach record, PbsAttachExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(PbsAttach record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_ATTACH
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(PbsAttach record);
}