package com.tyust.dao.pbs;

import com.tyust.bean.pbs.PbsPic;
import com.tyust.bean.pbs.PbsPicExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PbsPicDAOImpl extends SqlMapClientDaoSupport implements PbsPicDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public PbsPicDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public int countByExample(PbsPicExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("PBS_PIC.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public int deleteByExample(PbsPicExample example) {
        int rows = getSqlMapClientTemplate().delete("PBS_PIC.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(String pbsPicId) {
        PbsPic key = new PbsPic();
        key.setPbsPicId(pbsPicId);
        int rows = getSqlMapClientTemplate().delete("PBS_PIC.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public void insert(PbsPic record) {
        getSqlMapClientTemplate().insert("PBS_PIC.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public void insertSelective(PbsPic record) {
        getSqlMapClientTemplate().insert("PBS_PIC.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<PbsPic> selectByExample(PbsPicExample example) {
        List<PbsPic> list = getSqlMapClientTemplate().queryForList("PBS_PIC.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public PbsPic selectByPrimaryKey(String pbsPicId) {
        PbsPic key = new PbsPic();
        key.setPbsPicId(pbsPicId);
        PbsPic record = (PbsPic) getSqlMapClientTemplate().queryForObject("PBS_PIC.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(PbsPic record, PbsPicExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("PBS_PIC.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public int updateByExample(PbsPic record, PbsPicExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("PBS_PIC.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(PbsPic record) {
        int rows = getSqlMapClientTemplate().update("PBS_PIC.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(PbsPic record) {
        int rows = getSqlMapClientTemplate().update("PBS_PIC.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends PbsPicExample {
        private Object record;

        public UpdateByExampleParms(Object record, PbsPicExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}