package com.tyust.dao.pbs;

import com.tyust.bean.pbs.PbsPic;
import com.tyust.bean.pbs.PbsPicExample;
import java.util.List;

public interface PbsPicDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    int countByExample(PbsPicExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    int deleteByExample(PbsPicExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(String pbsPicId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    void insert(PbsPic record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    void insertSelective(PbsPic record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    List<PbsPic> selectByExample(PbsPicExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    PbsPic selectByPrimaryKey(String pbsPicId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(PbsPic record, PbsPicExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    int updateByExample(PbsPic record, PbsPicExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(PbsPic record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_PIC
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(PbsPic record);
}