package com.tyust.dao.pbs;

import com.tyust.bean.pbs.PbsTestReport;
import com.tyust.bean.pbs.PbsTestReportExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PbsTestReportDAOImpl extends SqlMapClientDaoSupport implements PbsTestReportDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public PbsTestReportDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public int countByExample(PbsTestReportExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("PBS_TEST_REPORT.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public int deleteByExample(PbsTestReportExample example) {
        int rows = getSqlMapClientTemplate().delete("PBS_TEST_REPORT.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(String pbsTestReportId) {
        PbsTestReport key = new PbsTestReport();
        key.setPbsTestReportId(pbsTestReportId);
        int rows = getSqlMapClientTemplate().delete("PBS_TEST_REPORT.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public void insert(PbsTestReport record) {
        getSqlMapClientTemplate().insert("PBS_TEST_REPORT.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public void insertSelective(PbsTestReport record) {
        getSqlMapClientTemplate().insert("PBS_TEST_REPORT.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<PbsTestReport> selectByExample(PbsTestReportExample example) {
        List<PbsTestReport> list = getSqlMapClientTemplate().queryForList("PBS_TEST_REPORT.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public PbsTestReport selectByPrimaryKey(String pbsTestReportId) {
        PbsTestReport key = new PbsTestReport();
        key.setPbsTestReportId(pbsTestReportId);
        PbsTestReport record = (PbsTestReport) getSqlMapClientTemplate().queryForObject("PBS_TEST_REPORT.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(PbsTestReport record, PbsTestReportExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("PBS_TEST_REPORT.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public int updateByExample(PbsTestReport record, PbsTestReportExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("PBS_TEST_REPORT.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(PbsTestReport record) {
        int rows = getSqlMapClientTemplate().update("PBS_TEST_REPORT.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(PbsTestReport record) {
        int rows = getSqlMapClientTemplate().update("PBS_TEST_REPORT.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends PbsTestReportExample {
        private Object record;

        public UpdateByExampleParms(Object record, PbsTestReportExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}