package com.tyust.dao.pbs;

import com.tyust.bean.pbs.PbsTestReport;
import com.tyust.bean.pbs.PbsTestReportExample;
import java.util.List;

public interface PbsTestReportDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    int countByExample(PbsTestReportExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    int deleteByExample(PbsTestReportExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(String pbsTestReportId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    void insert(PbsTestReport record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    void insertSelective(PbsTestReport record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    List<PbsTestReport> selectByExample(PbsTestReportExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    PbsTestReport selectByPrimaryKey(String pbsTestReportId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(PbsTestReport record, PbsTestReportExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    int updateByExample(PbsTestReport record, PbsTestReportExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(PbsTestReport record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PBS_TEST_REPORT
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(PbsTestReport record);
    
}